### ISSUE TITLE
I get only displayed 3 speakers but the total count says there are 4

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#1003]
https://staging-speakerinnen-liste.herokuapp.com/en/profiles?utf8=%E2%9C%93&search=katja&button=

<img width="1008" alt="Bildschirmfoto 2020-01-13 um 20 27 57" src="https://user-images.githubusercontent.com/2119496/72285361-3fd73a80-3643-11ea-8391-25973161cb52.png">

in this branch: https://github.com/rubymonsters/speakerinnen_liste/tree/anja-add-new-tag-filter

**Comment by netagonen** [comment]
Fixed with #1038
