### ISSUE TITLE
Please check: Forgot password not working anymore?

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#1007]
We got the following email. Could someone please try to reproduce the error and if so, try to fix it? --> please give me feedback to whatever comes out, so I can answer the email.

Hallo, ich habe mein Passwort vergessen und habe einen Link angefordert, und wie angegeben diesen geklickt und ein neues Passwort eingegeben, und dieses bestaetigt. Nachdem ich 'new password' geklickt habe, kam ich aber wieder auf die selbe Seite (change password) und ich kann mich auch nicht einloggen. Ich nehme an, dass das Konto jetzt nach mehreren Versuchen blockiert ist. Wie kann ich mein Password neu setzen bzw mich einloggen?

**Comment by sabrina-ulbrich** [comment]
I tried it out and it works, so I close this issue. Maybe you can ask for the email and we look in the database? @zaziemo
