### ISSUE TITLE
Too many tags?

### ISSUE THREAD

**Issue by sabrina-ulbrich** [rubymonsters/speakerinnen_liste#1011]
Main problem Salit noticed last Monday was the huge amount of tags each category has. No one wants to scroll through a incredible list of 1000 tags or more. So, should we reduce the amount? But wich number of tags is acceptable? I guess even 100 are uncomfortable. What do you think? But even if we reduce the tags up to 100 per category then we lose all the diverse topics. Another idea could be to create a fix subcategory system with maybe 20 subcategories ordered under the main categories so that just these could be choosed by someone looking for profiles. This has the advantage to keep track of all possible topics, but it takes a lot of extra effort by us and it is not clear whether we cover all existing topics and whether 3 kinds of category/tagging things would be more confusing.

Another impression I had, when I compared the "old way" of searching with the "new way" is, that the last one is completely abstract: I don't see a personal face but only words adding and deleting in my filter. On the other hand (the "old way") I start with a search term, get some profiles that fit more or less, but I get other collections of tags that are ordered in a semantic way, because every woman has created her tags inside of a meaningful context. So when I search for profiles I can get inspired by these collections and can use these tags as links to go further. ... Just a thought ...

I think the problem is that the tags are supposed to fulfill at least two functions, but they are contradictory:

1. tags should give a quick overview of the speaker's topics on the profile page and serve as keywords for the search, from which conference organizers can choose.

2. tags should represent the whole range of possible topics offered by the women. Of course we want to expect an increasing number of profiles.

At the 1st point it makes sense that there are not too many tags: maximum 10 per speaker or 50 (? is still too much in a list, I think) per category.
For the 2nd point it is important that unusual topics are also listed and that there is no upper limit. For a conference organizer it might be more interesting to see different tag lists as always the same keywords. Maybe we should also think about other/supplementary structures to present the information. I have a few general ideas about this:

Problems
1. Single tags are very long, which goes beyond the meaning of a short keyword (e.g.: nicht mit mir! souveränität statt fassungslosigkeit. vortrag und workshop zum buch <- that's one(!) tag, there are more like that)
2. There are tags that do not relate to a content topic (category) but to a form of communication, e.g.
  - moderation (28 different tags in different categories), moderatorin (7)
  - workshop (28), seminar (5)
  - vortrag (2), keynote (2), speaker (5 incl. speakerinnen.org ;))
  - training (57), coaching (43)
  - beratung (35)
3. Search results are not correct, because
  3.1. there are different tags with the same meaning (e.g. workshop and workshops, blogger and blog and blogs and bloggen and blogging), but each tag gives different search results: "workshop" finds 29 women, "workshops" finds 69 women
  3.2 Unusual/individual spelling with only one profile (e.g. "mutter*schaft" but not found in "mutterschaft")
4. Topics/tags are only displayed if that correspond to the selected language. Most people will probably not be aware of this. Is that described somewhere?

Proposed solutions
about 1. limitation of the tag length to a maximum of 20 characters and the number of tags to a maximum of 10
about 2. such tags are removed and instead of that a new attribute "offer" (or something similar) is created, for which the following can be selected by multiple select: Lecture/speech, moderation, workshop/seminar management, consulting, training/coaching.
about 3.1. merging obvious synonyms, e.g. blogger and blog and blogs and bloggen and blogging
about 3.2 Additional text field (with text limitation) for 1-2 sentences: a slogan or motto. Here women can write in something personal, which is currently written in the tags (like the example under 1.), because there is no other possibility (or the "biography" is not seen as the right place, maybe we should rename it to "About me"?) This text also appears in the short profile. 

We should agree on a few simple rules for consistency of tags and then write this down for orientation on the profile page (and FAQ):
- either singular or plural
- either nouns or adjektives or verbs
- incorporated symbols (*/&) or not
- no more than 2 words (better 1)

**Comment by tyranja** [comment]
Thank you for the effort you put into this.

Some more thoughts:
- we talked about not letting the speakerinnen to create new tags 
- Salit also proposed to add a field named "personal note" that could be the "about me" you suggested and I really like that idea
- that "main topic" field we already have should cover the slogan or motto you talked about?

**Comment by tyranja** [comment]
Just found you old tag issue :( https://github.com/rubymonsters/speakerinnen_liste/issues/918

**Comment by sabrina-ulbrich** [comment]
Good point @tyranja! I realized that there are different problems, one is about search algorithm (get same results with "workshop" and "workshops") - for that is #918 now. Another one is here with the question what function are the tags for.

**Comment by netagonen** [comment]
Hi, interesting and important discussion! 
In general I think it is important to let speakers have their own topics so they could express themselves best. BUT, there should be limitations.  I am for the solutions @sabrina-ulbrich and @tyranja suggested, considering we keep letting speakers make their own tags: 
1. Add a personal note, so the speaker could tel about herself, there should be the motto/slogen or explanations about uniq topics. 
2. Limit length of tags to 20 chars.
3. Limit number of tags per speaker to 10 or even less (7?).  
4. Tags should be 1-2 words long. 
5. Tags should be a noun.
6. Merge synonyms. 
7. Tags should be singular.  
8. Create a new attribute "offer" (or something similar) for Lecture/speech, moderation, workshop/seminar management, consulting, training/coaching.
9. Improve search algorithm to have results for similar words.
10. Improve search to present profiles from both languages.
11. Add an explanation to creating a profile: what is the purpose  of tags (searchability), the limitation of tags, the purpose of the personal note and so on. 

Open points:
- I am on the fence with regarding special characters in tags.
- Can we find a way to merge tags automatically? 
- Can we Inform existing speakers about the change? it would be great to inform them about new features in general.
- Do we still  need the gem ActAsTaggable? 
- What should we do with the existing tags? 
- If we decide to not let speakers make their on tags, what would be the alternative? we make the topics? how?

**Comment by alonpeer** [comment]
Hi everyone. 
I read all of the discussion so far and I have some thoughts to share:

1. I think speakers should be allowed to enter any tags they want. I do think that, since the website is aimed to be an international one, all tags should be in the English language. However, we cannot really enforce that (see my next point), so we can just encourage them to do so by having some instructions related to tags, like Neta suggested.
1. IMO tags should not be individually approved by an admin. It's the speaker's responsibility to check for typos and such. 
1. When searching for some text, it should be searched within tags and also within the free text fields of the profile (name, bio, and any other sections that might be added in the future).
1. Elasticsearch is capable of performing a [fuzzy search](https://qbox.io/blog/elasticsearch-optimization-fuzziness-performance) and partial matches (e.g. singular/plural), so if someone searches the term "workshop", it'll show results for "workshops" as well. I'm not sure exactly how to configure it to do so, but I know it's possible, and we can take advantage of it, instead of limiting speakers to a specific form of a tag, and people who search as well.
1. Given the point above, I think we can avoid doing any merging of current tags, because Elasticsearch will take care of this for us.
1. I find the tag cloud at the bottom of the page (and the one on staging when searching within a category) not very useful. When I search, I prefer to just enter my search term in a text field, instead of scanning a huge cloud of words for the word I want.
1. I agree that adding another "offer" attribute can be useful, and is a good way for an organizer to filter by. I think another possible name to be considered for that attribute is "services".
1. As an organizer, I think my optimal search experience would be one of two:
a. Pick a top-level category, then within it narrow down the list by choosing filters (language, country, service) and entering free text search.
b. Enter free text search, then narrow down the list by choosing a category and other filters.

**Comment by sabrina-ulbrich** [comment]
Thanks a lot for your thoughts and suggestions @tyranja @netagonen @alonpeer 🎉 

I want to summarize here some points to have a starting point for the discussion.

1. I don't think we can solve the problem, which is why the topic with the tags came up in the first place: the new search for profiles, which Salit presented. According to the usability tests it is too confusing to search in a list of 1000 tags (or more). All ideas to reduce the number of tags only have a relatively small effect. The alternative would be, as @alonpeer suggested, a free search with different filter options.

2. I like the idea don't spend effort in merging and limiting tags but to improve elasticsearch, so similar written tags are found anyway.

3. Add new attributes "offer/services" and "personal note/about me".

4. Limit for tags (up to 7 or 10) and for a single one not longer than 20 chars are good for a better overview on the profile page (but not important for the search).

5. Whatever we decide we should explain it in the profile form and FAQ.

What do you think? Please complete if I have forgotten anything.

**Comment by tyranja** [comment]
Just talked about it, we can rename the label from `My topics as tags, please don't choose more than 10 tags:`  to `Topics I want to talk about` or `Meine Themen als Tags, wähle bitte nicht mehr als 10 Tags:` to `Themen über die ich reden möchte` Gonna make a new ticket for that.

**Comment by tyranja** [comment]
We have to many tags ( for what )

we gonna leave the 2 ways of finding a speakerin:

-> concrete search ==> search in tags, bio, etc

-> exploratory search ==> go via categories -> here you have the categories with the 100 or 50 most used tags per category ( the user can choose if they want to see all the tags or just the limited 100 or 50 tags ) and you can choose tags or categories 



How many profile have more than 10 tags?
How many tags have nmore then 2 words?
How many new tags are created?
How many tags are used by more then 1 person?

Write a better FAQ

**Comment by zaziemo** [comment]
> 3\. When searching for some text, it should be searched within tags and also within the free text fields of the profile (name, bio, and any other sections that might be added in the future).

@alonpeer concerning your point above: we already have included many profile fields in the elasticsearch index - with different weightings:
```
'fullname^1.7',
'twitter_de',
'twitter_en',
'iso_languages',
'cities.standard^1.3',
'country',
'topic_list^1.4',
'main_topic_en^1.6',
'main_topic_de^1.6'
```

**Comment by zaziemo** [comment]
FYI: I copied all the relevant feedback to improve elasticsearch into this issue #918

**Comment by sabrina-ulbrich** [comment]
I closed this issue because the new design is done. 💯
