### ISSUE TITLE
Add new attributes

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#1014]
`willing_to_travel_for_talk`
`willing_to_talk_for_nonprofit`

and make them visible when hovering over an profile 

![Screenshot from 2020-02-10 18-15-08](https://user-images.githubusercontent.com/1218914/74172894-574d1780-4c31-11ea-95a0-dd80d31731e4.png)

**Comment by netagonen** [comment]
Merged with #999
