### ISSUE TITLE
Add a new attribute `personal infos` 

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#1015]
It should be a text field
![Screenshot from 2020-02-10 18-20-29](https://user-images.githubusercontent.com/1218914/74173351-45b83f80-4c32-11ea-9bd2-c9f5a04daf9a.png)

**Comment by sabrina-ulbrich** [comment]
Where would it be in relation to the other fields? Above the "Bio".
What about the existing profiles? Do we inform the speakers about it so they could add this? Yes, it should be described in a mail to all speakers #1019 and also in a blogpost.
I would suggest, no more than 175 characters to show it in the short profile view.

**Comment by netagonen** [comment]
Merged with #999
