### ISSUE TITLE
Show copyright

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#1027]
when hover over a pic in the single profile view 

#1006

- [x] is it in the profile form
- [x] show on profile view

**Comment by tyranja** [comment]
![Screenshot from 2020-02-17 20-10-19](https://user-images.githubusercontent.com/1218914/74680645-8f200600-51c1-11ea-89d2-3d95b3596b9d.png)

**Comment by netagonen** [comment]
I think I am doing it in issue #999? Is it just the hover? That I didn't do. 
@Powerglove, I will push my branch so you can work on it

**Comment by Powerglove** [comment]
@netagonen I only volunteered to do it, because no one else had time. If you are working on this anyways and have capacity, please go for it. There's other things I can work on ;)
