### ISSUE TITLE
New text  for the startpage and category_filter page

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#1029]
- [x] Add new english text to **start page**

- [x] Add new english text to **sub menu**

- [x] Add bilingual version to **start page**
- [x] Add bilingual version to **sub menu**

in **app/views/pages/home.html.erb**

— Teaser oben — 

Englische Version

Get inspired! (Achtung: klein schreiben)
Browse almost 3.000 women speakers to find your expert!

Browse by category
Find the right female speaker in 10 categories!

About us
Learn more about the Speakerinnen.org team!

Our blog
Find exciting interviews and lots of news!

Deutsche Version

Lass dich inspirieren!
Jetzt aus fast 3.000 Speakerinnen auswählen!

Nach Kategorien durchsuchen
Finde die passende Speakerin in 10 Kategorien!

Über uns
Erfahre mehr über das Team von Speakerinnen.org!

Unser Blog
Hier findest du spannende Interviews und viele Neuigkeiten!

— Neueste Speakerinnen — 

Ein herzliches Willkommen!
Hier findest du unsere Neuzugänge

A warm welcome!
Here you can find our latest registrations

---

in **app/views/admin/tags/_filter_categories.html.erb**
— Nach Kategorien durchsuchen — 

Nach Kategorien und Themen durchsuchen
Finde deine Speakerin in 10 Kategorien oder filtere nach ganz konkreten Themen! 

Browse by categories and topics
Find your female speaker in 10 categories or filter by specific topics!

**Comment by Powerglove** [comment]
working on branch new-text-for-starpage

**Comment by tyranja** [comment]
Thank you!
