### ISSUE TITLE
Change looks of attributes 'willing_to_travel' and 'non_profit'

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#1035]
When `willing_to_travel` and `non_profit` is not filled in,  it should show an empty square or the attributes not at all. I was wrong! @zaziemo what do you think? empty checkfield or don't show the attributes at all?

![Screenshot from 2020-02-25 20-54-20](https://user-images.githubusercontent.com/1218914/75282411-527f8a80-5811-11ea-92df-12975fde7e28.png)

**Comment by zaziemo** [comment]
How do we deal with other information that is not provided. We should stick with that logic. If we display an empty field, we should do that here as well. But showing an empty checkfield would suggest you can click it, doesn't it? And that you can't do in the show view. Probably we should display k.A. or n/a. So people can see that there is no information provided by the speaker and they could ask.

**Comment by tyranja** [comment]
We do show the label only when when the field is filled in. So we would not show the 2 attribute when there are empty.
