### ISSUE TITLE
Search button under search field

### ISSUE THREAD

**Issue by sabrina-ulbrich** [rubymonsters/speakerinnen_liste#1048]
on staging it looks like expected `<div class="col-lg-6 col-dm-12">`:
![Screen Shot 2020-03-05 at 00 59 30](https://user-images.githubusercontent.com/372649/75934612-40d75c00-5e7d-11ea-98d2-7e89ca050b4e.png)
but on production the search button goes down under the search field `<div class="col-lg-6 col-dm-12 ml-2">`:
![Screen Shot 2020-03-05 at 00 59 53](https://user-images.githubusercontent.com/372649/75934678-77ad7200-5e7d-11ea-938c-f2f372d92846.png)
I don't know, if the div class makes this difference and I wonder why staging differs from production.

**Comment by sabrina-ulbrich** [comment]
Am I the only one where the search form with button looks like this (the second picture)? Maybe it's because of my small screen (11,6 inch)

**Comment by tyranja** [comment]
I think I have seen it, but only on a very special size. But if you see it then we shoud change it!

**Comment by alonpeer** [comment]
I can reproduce this. PR on the way.
