### ISSUE TITLE
Colours of categories "chart" partial

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#1050]
@tyranja did you change the colors of the bars?
Before the were more pastel (if I do remember it right).

Besides orange and purple are used twice.
<img width="1108" alt="Bildschirmfoto 2020-03-05 um 08 15 31" src="https://user-images.githubusercontent.com/2119496/75957175-be20c200-5eb9-11ea-91dd-d0870dc601c4.png">

**Comment by tyranja** [comment]
Should be ok now
