### ISSUE TITLE
Mobile view: categories partial

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#1051]
- numbers on the right hand side get lost
- Category names are not aligned in the middle

<img width="509" alt="Bildschirmfoto 2020-03-05 um 08 17 48" src="https://user-images.githubusercontent.com/2119496/75957286-ff18d680-5eb9-11ea-833e-fb33bd0b9c7c.png">

**Comment by tyranja** [comment]
The numbers vanish in smaller devises or else they overlap. It is a feature . Should they overlap the stripes when they are aligned in the middle?

**Comment by tyranja** [comment]
@zaziemo Can you have a look at my comment?  I have the day of today :tada: So I can go on your nerves :laughing:

**Comment by zaziemo** [comment]
@tyranja with alignment I mean vertical alignment.
<img width="498" alt="Speakerinnen_org" src="https://user-images.githubusercontent.com/2119496/102215041-6f3c9a00-3ed9-11eb-9805-446540326cf6.png">

And with the numbers: I think it is not a problem if they overlap the stripes.
