### ISSUE TITLE
Profile edit: different button size when logged in

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#1053]
As the contact button was stretched to the same size as the picture, the other buttons I see, when logged in ("Profil bearbeiten" etc.) are too  small
<img width="1239" alt="Bildschirmfoto 2020-03-05 um 08 38 07" src="https://user-images.githubusercontent.com/2119496/75958646-efe75800-5ebc-11ea-86df-273a2b27807d.png">

Ideas: 
* don't show the contact button on the own profile when logged in (because I don't want to write an email to myself
* put the edit buttons back to top right corner

**Comment by tyranja** [comment]
done
