### ISSUE TITLE
Change female to women on profile page

### ISSUE THREAD

**Issue by netagonen** [rubymonsters/speakerinnen_liste#1066]
Here we use women-
![image](https://user-images.githubusercontent.com/22200510/76796323-74927a00-67cb-11ea-9675-cbb43c525a43.png)

And here we use female:
![image](https://user-images.githubusercontent.com/22200510/76796476-cd621280-67cb-11ea-9a1f-8688bf59f07f.png)

-> Change the wording to womwn

**Comment by n3k00n3** [comment]
I think this issue was solved!
![issue_1066](https://user-images.githubusercontent.com/7244777/88073393-8060c500-cb4c-11ea-9359-1a054b8beb26.png)

**Comment by sabrina-ulbrich** [comment]
Yess, issue is solved, thanks for noticing @n3k00n3 !
