### ISSUE TITLE
Tooltip problems

### ISSUE THREAD

**Issue by netagonen** [rubymonsters/speakerinnen_liste#1087]
1. in mobile the bootstrap green checks - `'fa-check-square'` - are not visible . 
2. When a speaker doesn't have any of the fields that are shown in the tooltip in her profile (city, language, wiiling to travel, willing to speak nonprofit), all that is shown is a tiny little triangle above the profile when hovering.
3. In mobile, the tooltip is shown when tapping on the profile, but that's already directing to the profile's page: maybe there is no point on having the tooltip on mobile, whereas there is no hover in mobile?
4. Regarding the "willing to speak for non-profit": maybe we can remove it all together from the tooltip and add it as a filter? That way we answer to event organizers needs and this attribute is not super visible.

**Comment by athomschke** [comment]
**1. in mobile the bootstrap green checks - 'fa-check-square' - are not visible .**
Is that still reproducable? I used Safari and Chrome on mobile and saw the checkboxes.

**When a speaker doesn't have any of the fields that are shown in the tooltip in her profile (city, language, wiiling to travel, willing to speak nonprofit), all that is shown is a tiny little triangle above the profile when hovering.**
Addressing in https://github.com/rubymonsters/speakerinnen_liste/pull/1102

**In mobile, the tooltip is shown when tapping on the profile, but that's already directing to the profile's page: maybe there is no point on having the tooltip on mobile, whereas there is no hover in mobile?**
Not yet addressed.
When tapping the image, we directly direct to the profile page. But, when tapping the topics below, we only show the tooltip and don't redirect to the profile. Should this behavior be preserved?

**Regarding the "willing to speak for non-profit": maybe we can remove it all together from the tooltip and add it as a filter? That way we answer to event organizers needs and this attribute is not super visible.**
Not yet addressed.

**Comment by netagonen** [comment]
HI @athomschke, thanks for the remarks!  

1. great!
2. great * 2!
3 + 4: I think it would be best to discuss in the team meeting.
5. There is a search test that fails. I think it would be good to upgrade for new search version which now available on master.

**Comment by athomschke** [comment]
As mentioned by @tyranja , this is not fixed yet after merging https://github.com/rubymonsters/speakerinnen_liste/pull/1102 . Checking.

**Comment by athomschke** [comment]
Hmpf, there must be something I am missing, since I'm failing to reproduce this locally. Is it possible to get a data dump for one of the profiles where it shows the empty triangle? I'm assuming there's some edge-case in which my condition returns a false negative.

**Comment by tyranja** [comment]
@athomschke can you move you mouse over the 4th speakerinnen in the feature block? https://staging-speakerinnen-liste.herokuapp.com/

![Uploading staging_speak.png…]()

**Comment by athomschke** [comment]
Yes, sorry, I didn't make myself clear. I am trying to reproduce this behavior locally on my machine, so I can debug it better - however, if I create a profile without additional data here, it does not show the tooltip triangle. So I'm thinking the difference is in the configuration of profiles that I test with locally and the one on staging. Since I don't have admin credentials to the staging environment, I can't see how the profile is configured though.

**Comment by tyranja** [comment]
oh ok. Adding you to heroku would be helpful I guess :D

**Comment by tyranja** [comment]
Solltest jetzt heroku staging zugang haben....

**Comment by zaziemo** [comment]
@tyranja @athomschke is that issue done?
