### ISSUE TITLE
App crashes while admin updates profile (add comment)

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#1088]
We again get an 500 error, when we try to update a profile as an admin

This ist the error message 
```
An ActionView::Template::Error occurred in profiles#admin_update:

 undefined method `total_pages' for nil:NilClass
 app/views/admin/profiles/index.html.erb:15:in `_app_views_admin_profiles_index_html_erb__1020815350242919371_38116080'


-------------------------------
Request:
-------------------------------

 * URL        : https://speakerinnen.org/de/admin/profiles/5445/admin_update
 * HTTP Method: POST
 * IP address : 92.73.53.109
 * Parameters : {"utf8"=>"✓", "authenticity_token"=>"EkwMehE08UCIDUM1dweXtcu0+f+22qwOAhOfedI8Y0SO6FHjFkPSEsYj0MiWO2VLAdRv2DSbNEv8lBRZyxegKg==", "profile"=>{"admin_comment"=>"test"}, "commit"=>"Kommentar speichern", "controller"=>"admin/profiles", "action"=>"admin_update", "locale"=>"de", "id"=>"5445"}
 * Timestamp  : 2020-08-15 14:17:49 UTC
 * Server : aa4da7c3-54d9-4f98-be31-33b6c29a6b1d
 * Rails root : /app
 * Process: 7
```

These are the profiles where the problem occured recently
https://speakerinnen.org/de/admin/profiles/franziska-hilfenhaus
https://speakerinnen.org/de/admin/profiles/barbara-janczer 
https://speakerinnen.org/de/admin/profiles/cornelia-lindner

**Comment by tyranja** [comment]
When I try to update via console I get that error message:

Traceback (most recent call last):
        1: from (irb):4
ActiveRecord::RecordInvalid (Validation failed: The image is too big. Only pictures up to 2 MB are allowed.)

**Comment by tyranja** [comment]
I have added smaller pics to those profiles myself and now it should work.

**Comment by zaziemo** [comment]
@tyranja ist das Ticket damit abgeschlossen?
