### ISSUE TITLE
Category box changes after selection of a topic

### ISSUE THREAD

**Issue by sabrina-ulbrich** [rubymonsters/speakerinnen_liste#1095]
1. Go to https://speakerinnen.org/profiles and choose a category, i.e. "Körper und Geist"
2. Select a topic, i.e. "abenteuer"
3. Click "Speakerinnen mit diesem Thema"

Result: Speakerinnen are shown, but the selected Category at the top is not any more "Körper und Geist" as expected, but "Beruf und Bildung". It doesn't matter which category you choose, you will always see category "Beruf und Bildung" afterwards.

**Comment by tyranja** [comment]
Done
