### ISSUE TITLE
Change page: if search has 0 matches

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#1098]
If your search result has 0 matches we want to give a hint where the search could go on.

The hints to similar names or topics didn't work well. The idea (as currently implemented) to link to the "Filter by Themes" is a good one. But the link should be placed more prominentely with a hint:

"Discover in which fields our speakers are experts in:" 

<img width="1122" alt="speakerinnen_org" src="https://user-images.githubusercontent.com/2119496/97225368-db045f80-17d2-11eb-90bc-973fddac2996.png">

**Comment by tyranja** [comment]
:partying_face: @athomschke
