### ISSUE TITLE
When filtering via tags you get redirected to the english version

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#1110]
On the speaker index page: https://speakerinnen.org/profiles

-> you choose a tag 
-> click on the button "speaker for this topic" 
-> get the correct profiles but redirected to the english page.

![Screenshot from 2020-12-15 12-41-54](https://user-images.githubusercontent.com/1218914/102210862-07835080-3ed3-11eb-87ed-0870086c2b07.png)

**Comment by sabrina-ulbrich** [comment]
@tyranja I guess you fixed the bug, so this issue can be closed, right?
