### ISSUE TITLE
Contact form: add link to Code of Conduct

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#1115]
As a person who contacts a speaker or the team
I should see a link to the Code of conduct.

<img width="401" alt="Speakerinnen_org" src="https://user-images.githubusercontent.com/2119496/102819650-25b9e680-43d4-11eb-92ad-93ab72de4bc5.png">

**Comment by Aaryanpal** [comment]
Hi @zaziemo,
 could u assign this to me i would like to give it a shot

**Comment by zaziemo** [comment]
@Aaryanpal thanks for offering your help!
I'm sorry but this issue is already done but was apparently forgotten to close (see merged PR linked above). Is there another issue that could be interesting for you?
