### ISSUE TITLE
Profile edit: Add checkbox to Code of Conduct

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#1116]
Add new checkbox and link to the Code of Conduct (should open in a new tab) to the profile form.
Also add a validation so that everyone who signs up or saves her profile is forced to check this field and hopefully reads the CoC.

<img width="846" alt="Speakerinnen_org" src="https://user-images.githubusercontent.com/2119496/102820093-f657a980-43d4-11eb-8241-4173207f6dfd.png">

**Comment by athomschke** [comment]
Should this be saved as a setting ("User already accepted CoC") or will Speakerinnen need to accept the CoC each time they edit their profile?

If it's stored as a setting, do Speakerinnen need to re-accept when the CoC changes?
