### ISSUE TITLE
Prevent app to cause H12 - Request Timeout errors

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#1120]
https://devcenter.heroku.com/articles/h12-request-timeout-in-ruby-mri

Find out which processes are slow.

**Comment by zaziemo** [comment]
mal checken: 
```
A Rack::Timeout::RequestTimeoutException occurred in profiles#index:

 Request waited 28064ms, then ran for longer than 1936ms 
 app/views/shared/_tagbox.html.erb:1:in `_app_views_shared__tagbox_html_erb___4057451778339204059_81720620'


-------------------------------
Request:
-------------------------------

 * URL        : https://speakerinnen-liste.herokuapp.com/de/topics?page=114&topic=home%2Bstudies
 * HTTP Method: GET
 * IP address : 185.191.171.12
 * Parameters : {"page"=>"114", "topic"=>"home+studies", "controller"=>"profiles", "action"=>"index", "locale"=>"de"}
 * Timestamp  : 2021-01-13 18:24:16 UTC
 * Server : 69929568-d8c0-4f9a-a2f6-677f761713e3
 * Rails root : /app
 * Process: 7
```
````
A Rack::Timeout::RequestTimeoutException occurred in profiles#index:

 Request waited 28959ms, then ran for longer than 1041ms 
 app/controllers/profiles_controller.rb:40:in `index'


-------------------------------
Request:
-------------------------------

 * URL        : https://www.speakerinnen.org/en/topics?page=5&topic=linux
 * HTTP Method: GET
 * IP address : 216.244.66.249
 * Parameters : {"page"=>"5", "topic"=>"linux", "controller"=>"profiles", "action"=>"index", "locale"=>"en"}
 * Timestamp  : 2021-01-13 18:24:37 UTC
 * Server : 69929568-d8c0-4f9a-a2f6-677f761713e3
 * Rails root : /app
 * Process: 7

````
A Rack::Timeout::RequestTimeoutException occurred in profiles#index:

 Request waited 22912ms, then ran for longer than 7088ms 
 app/views/shared/_tagbox.html.erb:1:in `_app_views_shared__tagbox_html_erb___4057451778339204059_46812640'


-------------------------------
Request:
-------------------------------

 * URL        : https://speakerinnen-liste.herokuapp.com/de/categories/9?page=5
 * HTTP Method: GET
 * IP address : 173.231.59.199
 * Parameters : {"page"=>"5", "controller"=>"profiles", "action"=>"index", "locale"=>"de", "category_id"=>"9"}
 * Timestamp  : 2021-01-13 15:42:08 UTC
 * Server : 69929568-d8c0-4f9a-a2f6-677f761713e3
 * Rails root : /app
 * Process: 7

**Comment by tyranja** [comment]
https://devcenter.heroku.com/articles/ruby-memory-use

**Comment by zaziemo** [comment]
done with new database plan.
