### ISSUE TITLE
Frontpage - design changes

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#1122]
1) Make the search bar bigger so the words are fully readable
2) Add an empty square to the list of speakerinnen
3) Add titles to the category bars

![Screenshot from 2021-01-01 16-36-55](https://user-images.githubusercontent.com/1218914/103441635-9de3a000-4c4f-11eb-88e8-cf1c8e3da2f7.png)
![Screenshot from 2021-01-01 16-36-48](https://user-images.githubusercontent.com/1218914/103441636-9e7c3680-4c4f-11eb-9e65-adeea2c63c71.png)
![Screenshot from 2021-01-01 16-36-41](https://user-images.githubusercontent.com/1218914/103441640-9f14cd00-4c4f-11eb-811f-423f339b9935.png)

**Comment by tyranja** [comment]
![Screenshot from 2021-02-01 20-10-07](https://user-images.githubusercontent.com/1218914/106506272-c9b1aa00-64c9-11eb-9cd2-ca36cce2b59f.png)
@madny can you look though the texts in this page? they need to be made nice and translated. That would be great. 
It is also on the figma page https://www.figma.com/file/aPmSe86hz49J8n1daelWUBDp/Speakerinnen?node-id=1071%3A2846

**Comment by dieberlinerin** [comment]
I don't understand very well (sry): what do you need exactly? Translate the text which are there now (because sometimes we already have the texts, e.g. for the categories, did you change them? and why?) Or: companies & start-ups - this is a category that we already have. Why change it?
p.s. I'm not "madny" ;-) but "dieberlinerin"

**Comment by tyranja** [comment]
Sorry, for the confusions :confused: 

1. We need a better subtitle for the "browse by categories" to tell people what to do here. ( we added a new 2.sentence, but we are not sure if that is good description )

2. and in the new empty speakerinnen field we added new text which should be looked at.

we can also just talk about it next meeting :smiley:

**Comment by tyranja** [comment]
https://github.com/rubymonsters/speakerinnen_liste/pull/1143

**Comment by dieberlinerin** [comment]
I left some comments and a text suggestion for the new empty field.
