### ISSUE TITLE
mail to team speakerinnen in FAQ doesn't work

### ISSUE THREAD

**Issue by sabrina-ulbrich** [rubymonsters/speakerinnen_liste#1132]
1. Go to https://speakerinnen.org/de/faq and to the topic "Why is my profile not yet published?"
2. Click on team@speakerinnen.org and you are redirected to the homepage with the text "Sorry, die Seite, die du gesucht hast, existiert nicht." Same in german locale.

It should instead redirect to the contact form or open an email.

**Comment by sabrina-ulbrich** [comment]
wow cool that's fast 💯  thanks to @tyranja 😄

**Comment by tyranja** [comment]
Haha, and you where fast in creating and closing this ticket. Thank you. 

It was a bit tricky because I did not see the different quotes in the beginning.
