### ISSUE TITLE
Fix link and change picture on about-page (Mandy section)

### ISSUE THREAD

**Issue by dieberlinerin** [rubymonsters/speakerinnen_liste#1133]
In the short description on Mandy on the about-Page (https://speakerinnen.org/de/about) I would like to have the link fixed behind: Dr. Madny Read (2 times). 

The correct link is: https://madnyread.tumblr.com/

And could anyone please change the picture - new picture attached here:
![DW_P6B1533_klein-quadrat](https://user-images.githubusercontent.com/75301058/104444673-68687c00-5598-11eb-8d73-16038fd6cc3e.jpg)

Thank you very much for this!

**Comment by KanchanPrasad** [comment]
I would like to work on this project.

**Comment by zaziemo** [comment]
@KanchanPrasad yes sure, go for it :)

The changes have to be applied in `about.de.html.erb` and `about.en.html.erb`

If you need help with anything, let me know.

**Comment by KanchanPrasad** [comment]
Okay mam

**Comment by KanchanPrasad** [comment]
Mam done

**Comment by tyranja** [comment]
Unfortunately I just redesigned the "about us" page here: https://github.com/rubymonsters/speakerinnen_liste/pull/1140 

So you might put the code in this branch.  Sorry for the confusion. Usually we do not work so often on the same pages.

Sorry :disappointed:

**Comment by tyranja** [comment]
Can you send a link to your changes?

**Comment by zaziemo** [comment]
I will take over from here. @KanchanPrasad if you'd like to contribute again let's set up a short call to make an introduction.

**Comment by zaziemo** [comment]
@KanchanPrasad you could send me an email at maren@speakerinnen.org
