### ISSUE TITLE
Check and Update Active Storage behaviour with profile images

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#1134]
With the update from Rails 5.2 to 6.0 we observed a different cropping behaviour of the profile images.
Apparently there are a few changes to how Active Storage processes variants of the images: https://bloggie.io/@kinopyo/upgrade-guide-active-storage-in-rails-6

We should adapt this asap.

<img width="1276" alt="104614771-d8eec600-5688-11eb-936a-0e8023b4b6d4" src="https://user-images.githubusercontent.com/2119496/104644096-9c819100-56ad-11eb-9955-be045cbcfb01.png">

**Comment by sabrina-ulbrich** [comment]
There is also a DEPRECATION WARNING: Active Storage's ImageProcessing transformer doesn't support :combine_options, as it always generates a single ImageMagick command. Passing :combine_options will not be supported in Rails 6.1.

**Comment by sabrina-ulbrich** [comment]
combine_options are removed in PR #1222

**Comment by zaziemo** [comment]
@sabrina-ulbrich do we still need this?
