### ISSUE TITLE
Unactivated account error message is "not" visible

### ISSUE THREAD

**Issue by linkclau** [rubymonsters/speakerinnen_liste#1138]
when you try to login into an account which hasn't been activated, the login seems to fail without "any" error message.
After deleting all cookies there is a yellow/orange error pop-up. But it was not visible long enough to read the message.
I don't know if it was there before and I missed it, it was shown for maybe 0.1 to 0.2 seconds (not the 2000ms the code suggests).
I believe it was the "unconfirmed: 'Du musst Deinen Account bestätigen, bevor Du fortfahren kannst.'" message I saw.

It might be an timing issue of the client (timeout expired before the page was properly rendered)
Client was Firefox on Ubuntu 20.04 (can't currently provide more details as it was neither my account nor my computer :-)

Steps to reproduce:
* Register a new account
* Forget to confirm email (for ~6 month ;-)
* Try to login (fails)
* Reset password
* Try to login (fails)

I'm happy to help to debug it further if required

Proposed fix: an error message concerning an error which blocks you from working should stay visible

Workaround was, to klick the confirmation link in the original confirmation email
(could be a security risk that the link was still usable after ~6 month)

**Comment by zaziemo** [comment]
@linkclau thanks for your bug report. We fixed the problem by keeping the alert message longer so that people can read it comfortably!
