### ISSUE TITLE
Add an inactive button to the account edit page

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#1142]
Some Speakerinnen want to deactivate their account for a certain time.
In order to do that we need a button on the account edit page to make the profile "invisible"

**Comment by alicetragedy** [comment]
I really like this idea! There are definitely a lot of cases where someone might want to not receive requests for a certain time and in that case it’s so helpful for both speaker and conference organiser to have something like that so that no one wastes their time...
you could also make the account still visible (e.g. in search) but add the “inactive” label to it and put it at the bottom of search results for example, if you think it’s still worth having it be seen somehow.

**Comment by tyranja** [comment]
- add an attribute for the speaker called "inactive" 
- remove the contact button and just make some not usable button called "inactive" "nicht aktiv" if inactive
- make sure userin can set profile to inactive in edit profile

**Comment by tyranja** [comment]
I have added the inactive column to the profile which is per default "false". The Speakerin and the admin can change the attribute 
and then the profile is still visible but the contact button is inactive and the text changed. I did not want to take away the button because then the user of the website would start to find looking for it.

Now need some feedback:, regarding wording and design:

**The edit page of a speakerin:**

![Screenshot from 2021-07-07 12-01-19](https://user-images.githubusercontent.com/1218914/124741151-b349c780-df1b-11eb-8e6a-7b1f38d60079.png)
![Screenshot from 2021-07-07 12-01-05](https://user-images.githubusercontent.com/1218914/124741154-b3e25e00-df1b-11eb-8b42-855a34d19024.png)

**The show page for the speakerin when she is logged in:**

![Screenshot from 2021-07-07 12-00-44](https://user-images.githubusercontent.com/1218914/124741285-d1afc300-df1b-11eb-934f-95336b9c6572.png)

The show page for the user of the website:
![Screenshot from 2021-07-07 12-01-36](https://user-images.githubusercontent.com/1218914/124741334-df654880-df1b-11eb-9458-24b8646d28c0.png)


I would need the text in english and german

**Comment by salitkrac** [comment]
Hi Anja, please find my suggestion here:
https://www.figma.com/file/aPmSe86hz49J8n1daelWUBDp/Speakerinnen?node-id=1458%3A3010

* it will be great if someone else can look at it and give feedback before you implement it :-)

**Comment by tyranja** [comment]
After nearly a year, this feature is finally done :100:
