### ISSUE TITLE
FIx special tag filter request

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#1160]
We got some error messages  for the request of this URL:  https://speakerinnen.org/profiles?tag_filter=&locale=de&commit=Speakerinnen+mit+diesen+Themen

```
A NoMethodError occurred in profiles#index:

 undefined method `id' for nil:NilClass
 app/controllers/profiles_controller.rb:43:in `index'
```

The referrer Link was: https://speakerinnen.org/de/topics?topic=change+management

So I suppose someone was on this page and clicked on the Button "Speakerinnen mit diesen Themen".

# TODO
1) Please try to reproduce the error.
2) Fix the problem.

I'm not sure what the expected behavior would be and open to suggestions. If you are unsure, let's discuss.

**Comment by tyranja** [comment]
Gleiche wie: https://github.com/rubymonsters/speakerinnen_liste/issues/1153

**Comment by sabrina-ulbrich** [comment]
fixed :)
