### ISSUE TITLE
Upgrade Speakerinnen to a supported Postgres version (10 or higher)

### ISSUE THREAD

**Issue by langjoh** [rubymonsters/speakerinnen_liste#1188]
Our current Postgres version is 9.5 and its support ended in early 2021. 
The supported Postgres versions start at 10, see the version list here: https://www.postgresql.org/support/versioning/

By upgrading, we would also solve [Postgres Docker image not supporting Apple M1 chip](https://github.com/rubymonsters/speakerinnen_liste/issues/1179).

Steps:

- [ ] Update to 9.6
- [ ] Upgrade to 10

https://devcenter.heroku.com/articles/upgrading-heroku-postgres-databases

**Comment by langjoh** [comment]
Hi @tyranja,

frohes neues Jahr erstmal :)
ich hab mal in Heroku staging geschaut und dort steht 'version: 13.5'. Weißt du, ob sich das auf die Postgres Version  bezieht (oder das Heroku Addon)?

**Comment by netagonen** [comment]
How would we connect to stg/live DBs?

**Comment by langjoh** [comment]
@tyranja @zaziemo when you have time, could you please verify that we are using Postgres 13.5 in Prod and Staging? @netagonen and I checked it and to us it looks like the Heroku Postgres plugin has automatic updates and that might be the reason for the high version. If we are correct, Docker needs to be updated as well.
