### ISSUE TITLE
Wrong notification after changing email address

### ISSUE THREAD

**Issue by sabrina-ulbrich** [rubymonsters/speakerinnen_liste#1191]
After confirming the change of my email address (in the email I get) I get the notification "Your account was successfully confirmed. Please sign in." But I am already signed in. I should get the same notification when I change my password.

**Comment by tyranja** [comment]
After you have changed your eail adress -> 

![Screenshot from 2021-12-19 16-06-01](https://user-images.githubusercontent.com/1218914/146680450-860a496d-9678-4a49-8047-47a1fc1b460b.png)

After you clicked in the link in the confirmation email. 
![Screenshot from 2021-12-19 16-20-03](https://user-images.githubusercontent.com/1218914/146680452-858c7f95-fa4d-4f46-a96b-96e5c54d599a.png)

**Comment by tyranja** [comment]
We use the confirmation controller for the changing of the email address. We could change that behavior and use another controller or another method in controller for that.
