### ISSUE TITLE
Use CI from Github actions

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#1193]
https://docs.github.com/en/actions/migrating-to-github-actions/migrating-from-travis-ci-to-github-actions
https://docs.github.com/en/actions/automating-builds-and-tests/about-continuous-integration

**Comment by tyranja** [comment]
hups, I just started :( https://github.com/rubymonsters/speakerinnen_liste/actions will leave it like it is?

**Comment by langjoh** [comment]
@tyranja We can also pair on this :) I was working on a branch, but didn't get much further than you
