### ISSUE TITLE
docker needs manifest

### ISSUE THREAD

**Issue by sabrina-ulbrich** [rubymonsters/speakerinnen_liste#1206]
@langjoh I removed all docker volumes as you described, when I start `make setup` I get the following error message: `no matching manifest for linux/arm64/v8 in the manifest list entries`

**Comment by langjoh** [comment]
Hi @sabrina-ulbrich , thanks for trying it out. Is it possible for you to find out if the error comes from Postgres DB or ElasticSearch? 
Either way, the error sounds like it is still not running on M1 and the easiest way forward is probably to keep upgrading versions until it works. The current versions are still quite old and the Docker images as well.

**Comment by sabrina-ulbrich** [comment]
Hi @langjoh , as far as I understand it comes from elastic:
<img width="825" alt="Screenshot 2022-01-07 at 14 49 51" src="https://user-images.githubusercontent.com/372649/148643803-befe35df-c3ba-4371-8ff8-fdb0a4949d99.png">
Yes, I am fine working without docker. ;)

**Comment by langjoh** [comment]
Updating Docker alone doesn't work, because this is a breaking change and other files will have to be refactored

**Comment by zaziemo** [comment]
@langjoh do we still need this since we do not use elasticsearch anymore?

**Comment by langjoh** [comment]
No, you are right, we luckily don't need this anymore.
