### ISSUE TITLE
elasticsearch error message

### ISSUE THREAD

**Issue by sabrina-ulbrich** [rubymonsters/speakerinnen_liste#1210]
Error message while reindexing (it works after restart):
`Elasticsearch::Transport::Transport::ServerError: [429] {"error_id":"8b49c2ed-2799-40ca-82f9-1662b2481941","errors":[{"code":99701,"message":"You have reached your maximum storage size, upgrade your plan for more storage"}]}`

**Comment by zaziemo** [comment]
Conversation with searchly concerning free upgrade for not-for-profit.

**Comment by zaziemo** [comment]
Searchly upgraded our plan and now the process works flawlessly again.
Which means: if anyone updates a profile or if a new profile is published the search index is updated!
