### ISSUE TITLE
Fix email problems

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#1214]
Currently there are two problems with emails. I donn't know if they belong together:
1) I can't change the email address (via the console). As I tried to change it, I got this error message:
```
Traceback (most recent call last):
        3: from (irb):3
        2: from app/mailers/confirmation_mailer.rb:17:in `confirmation_instructions'
        1: from app/views/devise/mailer/reconfirmation_instructions.en.html.erb:6
ActionView::Template::Error (Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true)
```

2) one speaker got an email with a missing link to reset their password:
```
Hallo xxx!

Du hast dein Passwort vergessen? Kein Problem. Du kannst ein neues Passwort über diesen Link erzeugen: [Passwort ändern]()

Wenn du diese Anfrage nicht selbst gestellt hast, ignoriere diese E-Mail.

Dein Passwort wird nicht verändert, bis du den Link oben anklickst und ein neues erstellst.

Melde dich gerne bei uns, wenn du Fragen hast! Und natürlich freuen wir uns jederzeit über dein Feedback zu [Www.speakerinnen.org](http://www.speakerinnen.org/).

Danke,
Anja, Christiane, Mandy und Maren
(Das Speakerinnen-Team)
```

Please investigate and fix problem(s).

**Comment by sabrina-ulbrich** [comment]
@zaziemo Sorry, forget my first line of my last answer. It's correct that you can't change the email per console. I'll make a fix for that. (Reason is, that the request host is set in the application controller and the console doesn't know that.)

But the email for password reset works.

**Comment by zaziemo** [comment]
@sabrina-ulbrich thanks for the PR, will merge that tomorrow.
Concerning the E-Mail: I asked her back. I have the impression their e-mail programm may have manipulated the html email.
