### ISSUE TITLE
Exchange elasticsearch --> pg_search

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#1229]
1. Research which solution to chose 
a. a gem
b. plain SQL

possible gem:
https://github.com/Casecommons/pg_search

See implementation example: https://github.com/sabrina-ulbrich/mwg

1. which functionalities we need
a. scopes (--> aggregations/filter)
b. search over multiple fields
c. weighting of fields (optional)
d. typeahead --> suggester (with scopes)
e. treat special characters correctly, e.g. ä/ae, é/e

**Comment by sabrina-ulbrich** [comment]
@zaziemo I think it's easier to start with the gem, because it provides all the patterns we want and actually I used this gem in the mwg project, see the model of profiles there.

**Comment by zaziemo** [comment]
- [ ] delete everything elastic search related form docker compose
- [ ] remove elastic search gems
- [ ] remove elastic search module
- [ ] remove elastic search related code in specs
- [ ] add pg_search gem
- [ ] add search functionalities with pg_search until specs are green again

**Comment by zaziemo** [comment]
I will close this issue now. I opened new, small ones to add some features and decide upon some things. All those issues are labelled with `search`.
