### ISSUE TITLE
Adjust to small screen sizes

### ISSUE THREAD

**Issue by athomschke** [rubymonsters/speakerinnen_liste#1233]
We noticed that some parts of the redesign don't work on phone screens yet - we didn't really look at these during the offsite, purposefully.

**Comment by athomschke** [comment]
![Screenshot 2023-01-02 at 19 05 28](https://user-images.githubusercontent.com/2465405/210266092-a72223d4-45ff-45cd-b5ee-16e696cced99.png)

e.g. categories are off

**Comment by tyranja** [comment]
![Screenshot from 2023-01-02 19-06-27](https://user-images.githubusercontent.com/1218914/210266137-72a58cff-0605-434c-9408-e0953cd7f1c3.png)

**Comment by athomschke** [comment]
![Screenshot 2023-01-02 at 19 06 40](https://user-images.githubusercontent.com/2465405/210266153-04a0b59f-35ca-4eb8-aaac-8966c81bd162.png)

Footer also looks weird

**Comment by athomschke** [comment]
https://www.figma.com/file/aPmSe86hz49J8n1daelWUBDp/Speakerinnen?node-id=3007%3A130213
