### ISSUE TITLE
Tiny link adjustments

### ISSUE THREAD

**Issue by athomschke** [rubymonsters/speakerinnen_liste#1256]
Realized three small issues today during a quick review:

* "back to the profile" is underlined in http://localhost:3000/en/profiles/karen-smith/edit
* http://localhost:3000/en/profiles/karen-smith links in den buttons sind unterstrichen 
* border around error bars, plus it has rounded corners

**Comment by tyranja** [comment]
Done https://github.com/rubymonsters/speakerinnen_liste/pull/1242/commits/dff96ad2490deb03f11da60f7c0d1d391255abd2
