### ISSUE TITLE
Speed up new postgres search: switch from kaminari to pagy

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#1269]
The new postgres search https://github.com/rubymonsters/speakerinnen_liste/tree/try-simple-postgres-search is still a little slow.

One culprit is already identified: pagination with kaminari as it is currently implemented.

Please use Pagy instead: https://github.com/ddnexus/pagy

**Comment by sabrina-ulbrich** [comment]
@zaziemo There is the issue #914 that suggests to use pagy instead of kaminari.

**Comment by zaziemo** [comment]
@sabrina-ulbrich ah good hint!
