### ISSUE TITLE
New Design - Figma Feedback

### ISSUE THREAD

**Issue by athomschke** [rubymonsters/speakerinnen_liste#1276]
Salit left some feedback on the designs in https://www.figma.com/file/aPmSe86hz49J8n1daelWUBDp/Speakerinnen?node-id=2855%3A127879 when testing staging:

Task list
- [x] Drop shadow effect for hero image not needed  ( Anja )
- [x] Move "Get inspired" between hero image and current topic section as more elegant divider
- [x] The space between the header text lines in topic sections can be cut by 30%
- [x] Info icons in speakerinning card list could be 2x bigger ( Astrid )
- [x] Text in get inspired section is not visible, needs to be brighter if the section has a dark background
- [x] The 'we need more women on stages' card: use H1 and H2 for the texts ( Astrid )
- [x] The cards on the bottom (get inspired, speakerinnen blog, fifty percent) need to be 2x longer ( Astrid )
- [x] The cards on the bottom - top right logo size needs to be 80px ( Astrid )
- [x] The cards on the bottom - logo needs to be an outline, not a fill ( Astrid )
- [x] Footer needs to be white, not black ( Anja )
- [x] Header dropdown menu color should be # 343A40 ( Anja )
- [x] Header hover color should be # 52585D ( Anja )
- [x] Header highlight color should be the brand green ( Anja )
- [x] FAQ text should be black, and only green on mouseover ( Astrid )
- [x] new header pic
- [x] new favicon
- [x] In den Namenskacheln erst den Namen und das Thema darunter setzen (> tauschen), Name fett, Thema unfett
- [x] Überall wo Text auf weiß ist, sollte der Hintergrund grau werden beim hovern über einen Link (nice to have) (
- [x] Neuer Link im Header “Als Speakerin registrieren” “Register as a speaker”/ remove dropdown
- [x] Sprachwechsel als Dropdown im Header
- [x] "Be part of it" in smaller screen sizes doesn't fit

Not included:
- Info icons in speakerinnen card list could be an outline-icon -> needs font awesome upgrade, but we have a discussion about a new icon set being needed anyways
- Header re-adjustment (see second section in design -> specifying in group chat discussion) -> to be ignored

**Comment by zaziemo** [comment]
Responsiveness:
- [ ] categories vizualization

**Comment by zaziemo** [comment]
good work!
