### ISSUE TITLE
Change picture in og:image

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#1294]
We are still using the Marie Curie picture as open graph image.
1) Delete this image altogether
2) add random picture path to og:image attribute

**Comment by sabrina-ulbrich** [comment]
Solved in the PR: change image for meta tags #1301

![Screenshot 2023-02-06 at 22 17 03](https://user-images.githubusercontent.com/372649/217091951-f63fa193-0a87-45ee-8675-0d291261df3d.png)

https://ogp.me/#array says, that different versions of the image can be added by copying the same meta tag.

**Comment by zaziemo** [comment]
Leider hab ich es jetzt beim testweisen teilen in FB nicht hinbekommen, ein anderes Bild auszusuchen, aber immerhin haben wir jetzt überhaupt das neue Design. Danke @sabrina-ulbrich :)
