### ISSUE TITLE
Check: current master uses the old version of elasticsearch

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#1300]
How did that happen?
How can we get "back" to the newer version 7.17.0?
--> does searchbox change automatically?
--> do we have to reindex?

**Comment by zaziemo** [comment]
After Deployment 

We have to uninstall the searchbox addon: https://devcenter.heroku.com/articles/searchbox#removing-the-add-on
and create a new one with the correct elasticsearch version: `heroku addons:add searchbox:starter --es_version=7`
We have to reindex after deployment `bundle exec rake elasticsearch:import:all`

Unfotunately the process did not work on staging. I have to figure out, what to do.

**Comment by zaziemo** [comment]
Apparently the problem is based on a new licensing model of elastic https://www.elastic.co/de/pricing/faq/licensing
We have to downgrade the elasticsearch version

**Comment by zaziemo** [comment]
@langjoh let's talk about this tomorrow evening. It's a hassle and I don't know if I want to spend more time on this. Is it somehow possible to use a docker image that works with elastic 6 and apple silicon?

**Comment by langjoh** [comment]
Elasticsearch offers free licenses to Open Source Projects: https://www.elastic.co/de/pricing/faq/licensing#ich-entwickle-eine-anwendung-die-elasticsearch-einbettet-und-weiterverteilt.-bin-ich-in-irgendeiner-weise-von-der-%C3%A4nderung-betroffen

**Comment by langjoh** [comment]
closing this issue, because we decided to abandon elasticsearch.
