### ISSUE TITLE
Upgrade staging to the latest heroku stack

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#1305]
https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack

Blocker: needs ruby 3.1.x

**Comment by langjoh** [comment]
<img width="694" alt="Screenshot 2023-10-28 at 12 06 35" src="https://github.com/rubymonsters/speakerinnen_liste/assets/11478797/3e2e5b1b-14c6-4fc6-b4d6-d225bd3cb69e">
