### ISSUE TITLE
Re-evaluate backup strategy

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#1315]

**Comment by netagonen** [comment]
Hi, I think this is the page that relevant for us: https://devcenter.heroku.com/articles/heroku-postgres-backups. I will read and update :)

**Comment by netagonen** [comment]
"Every Heroku Postgres database on the Standard tier or higher comes with an automatic, behind-the-scenes [Continuous Protection](https://devcenter.heroku.com/articles/heroku-postgres-data-safety-and-continuous-protection) mechanism that captures physical backups for disaster recovery.
For testing, setting up environments, and migrating data, logical backups offer more portability than physical backups. Heroku Postgres has a PGBackups feature that allows you to take manual and scheduled logical backups. These backups are in a [compressed binary format](http://www.postgresql.org/docs/current/static/app-pgdump.html), and are much smaller in size than your database’s actual size on disk.
Use PGBackups only for moderately loaded databases up to 20 GB. The backup process can time out for databases that are heavily loaded, larger than 20 GB, or databases with many schemas or large objects. See [Heroku Postgres Logical Backups](https://devcenter.heroku.com/articles/heroku-postgres-logical-backups) for instructions on taking logical backups for databases not suitable for PGBackups.
For all production Heroku Postgres plans, use [continuous protection](https://devcenter.heroku.com/articles/heroku-postgres-data-safety-and-continuous-protection) for data backup and recovery. Logical backups such as those taken by PGBackups are better suited for use cases requiring data portability."

**Comment by langjoh** [comment]
Heroku automatically takes care of backups.
