### ISSUE TITLE
Fix Profile Edit if picture is too big 

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#1326]
if I upload a picture that is too big, I get this error (on staging)

PG::NotNullViolation: ERROR: null value in column "service_name" of relation "active_storage_blobs" violates not-null constraint DETAIL: Failing row contains (319, x0ey5sey0i1azubi9p71ugl239a8, IMG_4927.jpg, image/jpeg, {"identified":true}, 1492153, JpInYirPINK8qnyoCAUPkg==, 2023-10-16 18:29:38.815557, null).

![Uploading Bildschirm­foto 2023-10-16 um 20.31.43.png…]()

**Comment by tyranja** [comment]
That was due to another error we already fixed. Upload on staging did not work at all but does now
