### ISSUE TITLE
Check timeout issues

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#1367]
after some investigation in papertrail the before_action `set_profile` in the `ProfilesController´-> check if we probably have update the friendly_id gem.

**Comment by tyranja** [comment]
The latest is 5.5.1:

![image](https://github.com/rubymonsters/speakerinnen_liste/assets/1218914/0d7a520a-4db2-4ff5-adb9-1f4f95601e37)


We have 5.5.0.

![image](https://github.com/rubymonsters/speakerinnen_liste/assets/1218914/fba5e177-75d8-41a5-88f4-87dbde4858c1)

**Comment by tyranja** [comment]
Dyno Investiagtion:
After reading this article: https://devcenter.heroku.com/articles/addressing-h12-errors-request-timeouts
I came to the conclusion that we do not need to add more dynos because is the dyno usage is always way under 1:
![image](https://github.com/user-attachments/assets/740f511f-eb6c-4d6f-8f83-f9c7451b5aa0)

https://devcenter.heroku.com/articles/metrics#dyno-load

**Comment by tyranja** [comment]
we have long run queries and might need to investigate there.

Also we can [Add a Timeout to the Webserver](https://devcenter.heroku.com/articles/preventing-h12-errors-request-timeouts#add-a-timeout-to-the-webserver)

**Comment by tyranja** [comment]
Jul 11 06:59:49 [speakerinnen-liste](https://my.papertrailapp.com/systems/speakerinnen-liste/events?focus=1747920690504146945&selected=1747920690504146945) [app/web.1](https://my.papertrailapp.com/groups/39146294/events?q=program%3Aapp%2Fweb.1&focus=1747920690504146945&selected=1747920690504146945) F, [2024-07-11T04:59:49.578846 #45] FATAL -- : [[8c7910a0-106f-48a3-b8fb-3dde22f6699f](https://my.papertrailapp.com/groups/39146294/events?q=%228c7910a0-106f-48a3-b8fb-3dde22f6699f%22&focus=1747920690504146945&selected=1747920690504146945)]   
Jul 11 06:59:49 [speakerinnen-liste](https://my.papertrailapp.com/systems/speakerinnen-liste/events?focus=1747920690504146946&selected=1747920690504146946) [app/web.1](https://my.papertrailapp.com/groups/39146294/events?q=program%3Aapp%2Fweb.1&focus=1747920690504146946&selected=1747920690504146946) [[8c7910a0-106f-48a3-b8fb-3dde22f6699f](https://my.papertrailapp.com/groups/39146294/events?q=%228c7910a0-106f-48a3-b8fb-3dde22f6699f%22&focus=1747920690504146946&selected=1747920690504146946)] ActionController::RoutingError (No route matches [GET] "/de/topics"):

**Comment by tyranja** [comment]
Jul 11 07:42:30 [speakerinnen-liste](https://my.papertrailapp.com/systems/speakerinnen-liste/events?focus=1747931430476869640&selected=1747931430476869640) [heroku/router](https://my.papertrailapp.com/groups/39146294/events?q=program%3Aheroku%2Frouter&focus=1747931430476869640&selected=1747931430476869640) at=info method=GET path="/en/profiles?filter_language=ru&filter_state=berlin&search=Marketing" host=speakerinnen.org request_id=[dc486f8a-39b1-4983-b734-88c39bbb682d](https://my.papertrailapp.com/groups/39146294/events?q=%22dc486f8a-39b1-4983-b734-88c39bbb682d%22&focus=1747931430476869640&selected=1747931430476869640) fwd="[66.249.64.130](https://my.papertrailapp.com/groups/39146294/events?q=%2266.249.64.130%22&focus=1747931430476869640&selected=1747931430476869640)" dyno=web.1 connect=0ms service=15084ms status=200 bytes=11246 protocol=https
Jul 11 07:42:30 [speakerinnen-liste](https://my.papertrailapp.com/systems/speakerinnen-liste/events?focus=1747931431051460613&selected=1747931431051460613) [app/web.1](https://my.papertrailapp.com/groups/39146294/events?q=program%3Aapp%2Fweb.1&focus=1747931431051460613&selected=1747931431051460613) E, [2024-07-11T05:42:30.319998 #45] ERROR -- : source=rack-timeout id=[dc486f8a-39b1-4983-b734-88c39bbb682d](https://my.papertrailapp.com/groups/39146294/events?q=%22dc486f8a-39b1-4983-b734-88c39bbb682d%22&focus=1747931431051460613&selected=1747931431051460613) wait=3ms timeout=15000ms service=15000ms state=timed_out
Jul 11 07:42:30 [speakerinnen-liste](https://my.papertrailapp.com/systems/speakerinnen-liste/events?focus=1747931431051460614&selected=1747931431051460614) [app/web.1](https://my.papertrailapp.com/groups/39146294/events?q=program%3Aapp%2Fweb.1&focus=1747931431051460614&selected=1747931431051460614) F, [2024-07-11T05:42:30.397325 #45] FATAL -- : [[dc486f8a-39b1-4983-b734-88c39bbb682d](https://my.papertrailapp.com/groups/39146294/events?q=%22dc486f8a-39b1-4983-b734-88c39bbb682d%22&focus=1747931431051460614&selected=1747931431051460614)]   
Jul 11 07:42:30 [speakerinnen-liste](https://my.papertrailapp.com/systems/speakerinnen-liste/events?focus=1747931431051460615&selected=1747931431051460615) [app/web.1](https://my.papertrailapp.com/groups/39146294/events?q=program%3Aapp%2Fweb.1&focus=1747931431051460615&selected=1747931431051460615) [[dc486f8a-39b1-4983-b734-88c39bbb682d](https://my.papertrailapp.com/groups/39146294/events?q=%22dc486f8a-39b1-4983-b734-88c39bbb682d%22&focus=1747931431051460615&selected=1747931431051460615)] Rack::Timeout::RequestTimeoutException (Request waited 3ms, then ran for longer than 15000ms ):
Jul 11 07:42:30 [speakerinnen-liste](https://my.papertrailapp.com/systems/speakerinnen-liste/events?focus=1747931431051460616&selected=1747931431051460616) [app/web.1](https://my.papertrailapp.com/groups/39146294/events?q=program%3Aapp%2Fweb.1&focus=1747931431051460616&selected=1747931431051460616) [[dc486f8a-39b1-4983-b734-88c39bbb682d](https://my.papertrailapp.com/groups/39146294/events?q=%22dc486f8a-39b1-4983-b734-88c39bbb682d%22&focus=1747931431051460616&selected=1747931431051460616)]   
Jul 11 07:42:30 [speakerinnen-liste](https://my.papertrailapp.com/systems/speakerinnen-liste/events?focus=1747931431051460617&selected=1747931431051460617) [app/web.1](https://my.papertrailapp.com/groups/39146294/events?q=program%3Aapp%2Fweb.1&focus=1747931431051460617&selected=1747931431051460617) [[dc486f8a-39b1-4983-b734-88c39bbb682d](https://my.papertrailapp.com/groups/39146294/events?q=%22dc486f8a-39b1-4983-b734-88c39bbb682d%22&focus=1747931431051460617&selected=1747931431051460617)] app/controllers/profiles_controller.rb:133:in `map'
Jul 11 07:42:30 [speakerinnen-liste](https://my.papertrailapp.com/systems/speakerinnen-liste/events?focus=1747931431051460618&selected=1747931431051460618) [app/web.1](https://my.papertrailapp.com/groups/39146294/events?q=program%3Aapp%2Fweb.1&focus=1747931431051460618&selected=1747931431051460618) [[dc486f8a-39b1-4983-b734-88c39bbb682d](https://my.papertrailapp.com/groups/39146294/events?q=%22dc486f8a-39b1-4983-b734-88c39bbb682d%22&focus=1747931431051460618&selected=1747931431051460618)] app/controllers/profiles_controller.rb:133:in `search_with_search_params'
Jul 11 07:42:30 [speakerinnen-liste](https://my.papertrailapp.com/systems/speakerinnen-liste/events?focus=1747931431051460619&selected=1747931431051460619) [app/web.1](https://my.papertrailapp.com/groups/39146294/events?q=program%3Aapp%2Fweb.1&focus=1747931431051460619&selected=1747931431051460619) [[dc486f8a-39b1-4983-b734-88c39bbb682d](https://my.papertrailapp.com/groups/39146294/events?q=%22dc486f8a-39b1-4983-b734-88c39bbb682d%22&focus=1747931431051460619&selected=1747931431051460619)] app/controllers/profiles_controller.rb:17:in `index'
Jul 11 07:42:30 [speakerinnen-liste](https://my.papertrailapp.com/systems/speakerinnen-liste/events?focus=1747931432112508931&selected=1747931432112508931) [heroku/router](https://my.papertrailapp.com/groups/39146294/events?q=program%3Aheroku%2Frouter&focus=1747931432112508931&selected=1747931432112508931) at=info method=GET path="/en/profiles/sabine-moebs" host=speakerinnen-liste.herokuapp.com request_id=[ac944ec7-590d-40fe-9bfc-469460469b54](https://my.papertrailapp.com/groups/39146294/events?q=%22ac944ec7-590d-40fe-9bfc-469460469b54%22&focus=1747931432112508931&selected=1747931432112508931) fwd="[173.252.107.114](https://my.papertrailapp.com/groups/39146294/events?q=%22173.252.107.114%22&focus=1747931432112508931&selected=1747931432112508931)" dyno=web.1 connect=0ms service=5698ms status=200 bytes=16275 protocol=https

**Comment by zaziemo** [comment]
Hier ist noch eine Übersicht über unterschiedliche Fehler: https://devcenter.heroku.com/articles/error-codes#r14-memory-quota-exceeded

**Comment by tyranja** [comment]
Block certain url's for all crawlers (example tag_filter url)

**Comment by tyranja** [comment]
Check slow queries in logs archive and lock for index

**Comment by zaziemo** [comment]
problem is solved
