### ISSUE TITLE
new error, page not reachable

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#1401]
Jul 29 16:48:38 [speakerinnen-liste](https://my.papertrailapp.com/systems/speakerinnen-liste/events?focus=1754591848834146304&selected=1754591848834146304) [app/web.1](https://my.papertrailapp.com/groups/39146294/events?q=program%3Aapp%2Fweb.1&focus=1754591848834146304&selected=1754591848834146304) F, [2024-07-29T14:48:37.669042 #44] FATAL -- : [[d407d3fb-aa3e-4b52-b7e8-74cbf6dad8d7](https://my.papertrailapp.com/groups/39146294/events?q=%22d407d3fb-aa3e-4b52-b7e8-74cbf6dad8d7%22&focus=1754591848834146304&selected=1754591848834146304)]   
Jul 29 16:48:38 [speakerinnen-liste](https://my.papertrailapp.com/systems/speakerinnen-liste/events?focus=1754591848834146305&selected=1754591848834146305) [app/web.1](https://my.papertrailapp.com/groups/39146294/events?q=program%3Aapp%2Fweb.1&focus=1754591848834146305&selected=1754591848834146305) [[d407d3fb-aa3e-4b52-b7e8-74cbf6dad8d7](https://my.papertrailapp.com/groups/39146294/events?q=%22d407d3fb-aa3e-4b52-b7e8-74cbf6dad8d7%22&focus=1754591848834146305&selected=1754591848834146305)] ActiveRecord::ConnectionTimeoutError (could not obtain a connection from the pool within 5.000 seconds (waited 5.004 seconds); all pooled connections were in use):
Jul 29 16:48:38 [speakerinnen-liste](https://my.papertrailapp.com/systems/speakerinnen-liste/events?focus=1754591848834146306&selected=1754591848834146306) [app/web.1](https://my.papertrailapp.com/groups/39146294/events?q=program%3Aapp%2Fweb.1&focus=1754591848834146306&selected=1754591848834146306) [[d407d3fb-aa3e-4b52-b7e8-74cbf6dad8d7](https://my.papertrailapp.com/groups/39146294/events?q=%22d407d3fb-aa3e-4b52-b7e8-74cbf6dad8d7%22&focus=1754591848834146306&selected=1754591848834146306)]   
Jul 29 16:48:38 [speakerinnen-liste](https://my.papertrailapp.com/systems/speakerinnen-liste/events?focus=1754591848834146307&selected=1754591848834146307) [app/web.1](https://my.papertrailapp.com/groups/39146294/events?q=program%3Aapp%2Fweb.1&focus=1754591848834146307&selected=1754591848834146307) [[d407d3fb-aa3e-4b52-b7e8-74cbf6dad8d7](https://my.papertrailapp.com/groups/39146294/events?q=%22d407d3fb-aa3e-4b52-b7e8-74cbf6dad8d7%22&focus=1754591848834146307&selected=1754591848834146307)] app/interactor/search_profiles_by_params.rb:10:in `call'
Jul 29 16:48:38 [speakerinnen-liste](https://my.papertrailapp.com/systems/speakerinnen-liste/events?focus=1754591848834146308&selected=1754591848834146308) [app/web.1](https://my.papertrailapp.com/groups/39146294/events?q=program%3Aapp%2Fweb.1&focus=1754591848834146308&selected=1754591848834146308) [[d407d3fb-aa3e-4b52-b7e8-74cbf6dad8d7](https://my.papertrailapp.com/groups/39146294/events?q=%22d407d3fb-aa3e-4b52-b7e8-74cbf6dad8d7%22&focus=1754591848834146308&selected=1754591848834146308)] app/controllers/profiles_controller.rb:89:in `search_with_search_params'
Jul 29 16:48:38 [speakerinnen-liste](https://my.papertrailapp.com/systems/speakerinnen-liste/events?focus=1754591848834146309&selected=1754591848834146309) [app/web.1](https://my.papertrailapp.com/groups/39146294/events?q=program%3Aapp%2Fweb.1&focus=1754591848834146309&selected=1754591848834146309) [[d407d3fb-aa3e-4b52-b7e8-74cbf6dad8d7](https://my.papertrailapp.com/groups/39146294/events?q=%22d407d3fb-aa3e-4b52-b7e8-74cbf6dad8d7%22&focus=1754591848834146309&selected=1754591848834146309)] app/controllers/profiles_controller.rb:16:in `index'

**Comment by zaziemo** [comment]
done
