### ISSUE TITLE
randomly shown pictures instead of pictures of speaking women

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#208]
there should be more pictures of diverse people that are randomly shown

**Comment by aparnagireesan** [comment]
Hi, i would like to work on this bug. Could you please help me get started with this?

**Comment by zaziemo** [comment]
Also a great resource for more diverse women*: https://www.flickr.com/photos/wocintechchat/

**Comment by geisasantos** [comment]
There's a lot in Wikipedia Commons, totally free for use. Me and a team of diversity in Wikimedia are trying to tag and create better descriptions, so it'll be more easy to find images of women in Wikimedia. There's a quite resource here: https://commons.wikimedia.org/wiki/Woman

**Comment by 1000miles** [comment]
Bootstrap v4.x offers a nice component called `Image Carousel`: https://getbootstrap.com/docs/4.0/components/carousel/

This ticket depends on ticket #674 . We need to refactor the front-end framework first. 

cc @tyranja

**Comment by zaziemo** [comment]
what about these ones?
https://www.flickr.com/photos/wocintechchat/25900705292/
https://www.flickr.com/photos/re-publica/41885135041/in/album-72157668583960298/
https://www.flickr.com/photos/re-publica/28016206628/in/album-72157668583960298/
https://www.flickr.com/photos/re-publica/41169371504/in/album-72157668583960298/
https://www.flickr.com/photos/re-publica/40973647375/in/album-72157696390863795/
https://www.flickr.com/photos/re-publica/41131676534/in/album-72157694604564251/
https://www.flickr.com/photos/re-publica/41131676534/in/album-72157694604564251/
https://www.flickr.com/photos/re-publica/41852838661/in/album-72157694604564251/
https://www.flickr.com/photos/re-publica/42639593951/
https://www.flickr.com/photos/re-publica/27770951697/
https://www.flickr.com/photos/re-publica/28766634128/
