### ISSUE TITLE
optimizing performance

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#210]
currently processes get slower and slower the more profiles and topics are created
there should be a cache for the topics that help to make performance better

---

issue must probably broken down into more issues

**Comment by zaziemo** [comment]
see new relic for details

**Comment by dmarcoux** [comment]
So how does one access to New Relic? I guess that only certain people have access to the New Relic account. It would be nice to have an idea of the major chokepoints.

**Comment by 1000miles** [comment]
hello, as bespoken with @tyranja here we go with the screenshot to recap one of the examples for the performance prob. :)

![bildschirmfoto 2015-09-26 um 18 16 24](https://cloud.githubusercontent.com/assets/4077916/10118540/c7b83af2-647a-11e5-8217-1c7922000b5e.png)

**Comment by tyranja** [comment]
Will close this for now. I have changed the way the picture is shown, when it is not loaded yet and we are working on getting  the AWS access to change the s3 server zone to Europe.
