### ISSUE TITLE
Redirect from heroku domain to speakerinnen.org

### ISSUE THREAD

**Issue by svenfuchs** [rubymonsters/speakerinnen_liste#213]
Google currently lists and links to speakerinnen-liste.herokuapp.com.

We should set up redirect to speakerinnen.org

Rails 3 might be able to do that in a route: http://stackoverflow.com/questions/4046960/how-to-redirect-without-www-using-rails-3-rack

If that doesn't work I guess Rack might help: https://github.com/jtrupiano/rack-rewrite

**Comment by zaziemo** [comment]
or here: https://stackoverflow.com/questions/7170664/how-to-configure-heroku-application-dns-to-godaddy-domain

**Comment by zaziemo** [comment]
@tyranja could you please have a look on that, probably with @ur5 :) ?
