### ISSUE TITLE
styling (css):  profiles/edit topic selection

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#223]
currently the topics are shown in a relatively big grey box and in a relatively big and serif font
it should be the same font and the same font as in the other fields and the grey box should be adapted to that smaller size

![bildschirmfoto 2014-03-13 um 10 46 53](https://f.cloud.github.com/assets/2119496/2407989/7b4aed40-aa95-11e3-952e-b692870524b0.png)

**Comment by aparnagireesan** [comment]
Hi, I would like to work on this issue. Could you please provide me with the links to the necessary code so that I can work on it?

**Comment by tyranja** [comment]
Done
