### ISSUE TITLE
email contact: set up and  install new email address 

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#231]
currently we use a gmail adress for contacting people (confirmation mail, password reset, individual contact of speakerinnen)
is it possible to have an info@speakerinnen.org address?
if not, Anne will create speakerinnen@grrlz.net and we have to implement it.

**Comment by zaziemo** [comment]
@tyranja haven't we talked about that recently?

**Comment by tyranja** [comment]
Ja, we did not decide the name of the mails. I keep forgetting that. I wrote a mail.

**Comment by zaziemo** [comment]
So that is done now. The only thing that we have to do is to redirect every conversation to team@ instead of speakerinnen@gmail.com, right!? @tyranja (when you are back)

**Comment by zaziemo** [comment]
done!
