### ISSUE TITLE
add multiple links for own websites 

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#238]
currently a user can only provide one link to her website
it should be possible to have the possibility to add more links than one

**Comment by tyranja** [comment]
see https://speakerinnen.org/en/profiles/adrienne-fichter

**Comment by tyranja** [comment]
https://github.com/globalize/globalize#adding-additional-fields-to-the-translation-table

https://github.com/rubymonsters/speakerinnen_liste/issues/644

**Comment by tyranja** [comment]
That is deployed and should be working, Thanks a lot for the work @sabrina-ulbrich :bouquet: :tada:
