### ISSUE TITLE
add unit test: tags forced lowercase for already existing tags 

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#245]
adding unit test tag_test.rb > what happens with already existing tags

**Comment by zaziemo** [comment]
@tyranja did you include these tests with your last commit? Then we could close it.

**Comment by tyranja** [comment]
No, didn't test the database. I just checked, if there is any upper case tag in the DB. I don't think we have to add a test here, because its an ActsAsTaggble function to save all the new added tags in lower case and we don't need to test that...

**Comment by zaziemo** [comment]
@tyranja so great! I will close that :)
