### ISSUE TITLE
implementation of advanced search

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#264]
Currently we only installed the basic search function. The content of all fields is searchable with AND and OR operator.
In the future it should be possible for the user
- to decide which fields to search specifically, e.g. search Berlin only in field "city" not in references
- use wildcards, like *
- to filter search results in different steps

Please consider a user friendly view to the different possibilities of search, e.g. basic search by default, button for advanced search (> redirection to a new search view)

**Comment by zaziemo** [comment]
still to do:
- migration of languages
- change language input field in edit profiles (drop down)
- test "language search"

**Comment by tyranja** [comment]
https://github.com/rubymonsters/speakerinnen_liste/tree/ty_replace_search

**Comment by tyranja** [comment]
Done
