### ISSUE TITLE
sign_in and sign_up UI improvements

### ISSUE THREAD

**Issue by saheba** [rubymonsters/speakerinnen_liste#281]
this should include:
- change UI to have consistent problem presentation style (notice/error/alert messages OR ajax overlays, highlight problematic fields in same style on both pages)
- change sign_up UI to prevent ugly overflow effects
- reorder elements (might include/force refactoring of views):
  - username
  - password
  - password confirmation (only on sign-up)
  - submit-form-button
  - plain word: or
  - via twitter button
  - link to recover password (only on sign-in)
  - link to resend account confirmation email 

![screenshot from 2014-07-21 11 25 13](https://cloud.githubusercontent.com/assets/1809538/3641844/7a885e9e-10b9-11e4-8781-b54cdc67e7c1.png)
![screenshot from 2014-07-21 11 25 27](https://cloud.githubusercontent.com/assets/1809538/3641846/7da1683c-10b9-11e4-8c06-6cf3fbb74a82.png)

**Comment by zaziemo** [comment]
done!
