### ISSUE TITLE
navigation display

### ISSUE THREAD

**Issue by saheba** [rubymonsters/speakerinnen_liste#282]
The navigation gets lost if you reduce your browser's width to a certain extend. It also breaks the list of links into two lines. Both UI problems should be fixed.

![screenshot from 2014-07-21 11 45 19](https://cloud.githubusercontent.com/assets/1809538/3642015/2e0405ac-10bc-11e4-8039-2e34afebc4a8.png)
![screenshot from 2014-07-21 11 47 49](https://cloud.githubusercontent.com/assets/1809538/3642016/2fc63dc4-10bc-11e4-9ba6-a25a2c563ba8.png)

**Comment by zaziemo** [comment]
done. <3 @tyranja @ur5!
