### ISSUE TITLE
category -  unexpected visual effects

### ISSUE THREAD

**Issue by chatulli** [rubymonsters/speakerinnen_liste#291]
- using chrome I got unexpected visual effects such as underline and split on two rows.
see screen shots

![screen shot 2014-08-13 at 11 41 06](https://cloud.githubusercontent.com/assets/5828998/3903703/4a9a1218-22cf-11e4-8541-39d506055306.png)
![screen shot 2014-08-13 at 11 46 11](https://cloud.githubusercontent.com/assets/5828998/3903704/4bf12ea8-22cf-11e4-975d-c615c4c269a3.png)

**Comment by zaziemo** [comment]
done
