### ISSUE TITLE
category's order: miscellaneous at the end

### ISSUE THREAD

**Issue by chatulli** [rubymonsters/speakerinnen_liste#292]
- sonstiges/miscellaneous should be at the end of the list, not in the middle. What is the order of the categories? Why? Why not alphabetical?
![screen shot 2014-08-13 at 11 41 06](https://cloud.githubusercontent.com/assets/5828998/3903705/505d1e52-22cf-11e4-8d34-4ae49677b68c.png)

**Comment by tyranja** [comment]
Done. The german 'Sonstiges' (en: Miscellaneous) is at the end and the other categories are orders by their german name.
