### ISSUE TITLE
name based vanity URL

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#306]
change profile URL from 
http://speakerinnen.org/de/profiles/27
to
http://speakerinnen.org/de/profiles/name

think about: how to handle name duplicates?

**Comment by zaziemo** [comment]
we use the gem friendlyID
TODO: use heroku console to generate first slugs via Profile.find_each(&:save)

TO decide: should we use URL histories? Concern: needs too much performance

**Comment by zaziemo** [comment]
test cases:
creation of slugs
-for new profiles
-for existing profiles with changend firstname or lastname
-for profiles with duplicate names
-with user generated slugname

**Comment by zaziemo** [comment]
started doing that in this branch: https://github.com/rubymonsters/speakerinnen_liste/tree/mh-su-name-based-routing

**Comment by marcinwyszynski** [comment]
I can take that.

**Comment by tyranja** [comment]
heroku run rake db:migrate --remote production
Profile.find_each(&:save)

**Comment by tyranja** [comment]
:tada:
