### ISSUE TITLE
extract all inline javascript to js-files

### ISSUE THREAD

**Issue by sray** [rubymonsters/speakerinnen_liste#313]
the title says it all

**Comment by zaziemo** [comment]
probably like this? https://medium.com/swlh/how-should-you-organize-javascript-in-rails-app-3d6cccdd3e28

**Comment by annesbln** [comment]
This was discussed today. This issue is not relevant at the moment. It seems better to think about this again after upgrading to rails 6 as JavaScript will be handled by Webpacker.

**Comment by sray** [comment]
just saw that pop up in my feed ... @annesbln @zaziemo to let webpacker handle ALL the javascript, you actually need extract the inline javascript inside .rb template files (or sth similar) into separate .js files (and refer/import the js file(s) with `javascript_pack_tag '<pack_name>'` then into your templates for webpacker to package it properly). That is what is meant with this issue. See https://blog.capsens.eu/how-to-write-javascript-in-rails-6-webpacker-yarn-and-sprockets-cdf990387463#Webpacker for details of js handling with webpacker (and intro to alternatives).
