### ISSUE TITLE
responsiveness: integrate badge of Marie Curie in the picture

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#320]
We decided to have the badge of Marie Curie pasted in the picture via photoshop. We want to use the interactive part with the moving badge only for 13'' screens / the corresponding browser sizes. @bioshrimp could you help us with the picture please?

**Comment by zaziemo** [comment]
@bioshrimp could you please have a look on that issue and help us with a picture of Marie Curie with the badge already integrated in the picture?

**Comment by bioshrimp** [comment]
done and sent to you :)

**Comment by zaziemo** [comment]
done, thx @bioshrimp!
