### ISSUE TITLE
Thumbnails Redesign

### ISSUE THREAD

**Issue by srse** [rubymonsters/speakerinnen_liste#328]
Instead of having the a big thumbnail with a big picture and the text at the bottom of it, it would be better to have a smaller picture and the text (name, profession, @twitter) to the right. Instead of having three or four columns with results or latest speakers it would be usually two columns of speakers thumbnails as results then. This concept also fits better to a mobile environment and reduces the problem of displaying too long names (e.g. Anna-Katharina Reitmeier-Nussbaum) or profession titles, which at the moment would break the layout. It does not solve the problem of long texts completely, but it offers more space for the text, so even if we do cut text sometimes with "..." at the end, it is more probably to already have enough characters shown, that also the automatically cut version makes sense to the reader.

as is:
------
Picture
------
Firstname Lastname
Profession/Main Topic
@twitter
------

to be:
             | Firstname Lastname
Picture | Profession/Main Topic
             | @twitter

**Comment by zaziemo** [comment]
done
