### ISSUE TITLE
add tests for devise methods

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#332]

**Comment by nerdinand** [comment]
What do you mean by this?

**Comment by tyranja** [comment]
Well, I guess we wanted to check if both ways ( twitter and email) to sign in are working properly.

**Comment by geisasantos** [comment]
Hey, menthors :)
Me and Emma were running some tests about it. I guess we can add this issue to our project planning.

@tyranja is just that check you mentioned or you want to add some rspec testing too?
