### ISSUE TITLE
time out error when uploading a bigger profile picture

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#343]
When user want to upload a profile picture which is bigger ( my example had the size of 2,5 MB), Heroku sends a H13 Error 
`2015-01-20T19:54:11.217055+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=POST path="/de/admin/profiles/79" host=staging-speakerinnen-liste.herokuapp.com request_id=a1e31c2c-a4f3-4c27-b2d6-ab902bd764ca fwd="92.226.35.86" dyno=web.1 connect=2ms service=15665ms status=503 bytes=0
`

and the App shows an Application Error:
![screenshot from 2015-01-20 21 00 16](https://cloud.githubusercontent.com/assets/1218914/5824866/6142fcf0-a0e7-11e4-9f9e-a1b4f8fead7d.png)

Here is the Error described on Heroku:

https://devcenter.heroku.com/articles/error-codes#h13-connection-closed-without-response

**Comment by tyranja** [comment]
@svenfuchs should I change the unicorn timeout config to 30s? At the moment its 15.

https://devcenter.heroku.com/articles/error-codes#h13-connection-closed-without-response

**Comment by svenfuchs** [comment]
Yeah, sounds like you wanna give that a try.

**Comment by zaziemo** [comment]
@tyranja can we now close this issue or do we need another solution?

**Comment by tyranja** [comment]
@zaziemo we can close it, I hope. I limited the size of the profile picture to upload and changed the ruby version and increased the unicorn timeout.

**Comment by zaziemo** [comment]
yay, thank you :)
