### ISSUE TITLE
Admin tag Database Error

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#344]
When you are in Admin/Tags and select:
- Show all tags without category
- Show all categories
- And search for a tag

you get an PG::Error
`PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "categories"
LINE 1: ...ROM "tags"  WHERE (tags.name ILIKE '%test%') AND (categories...
                                                             ^
: SELECT COUNT(*) FROM "tags"  WHERE (tags.name ILIKE '%test%') AND (categories.id IS NULL)`

**Comment by tyranja** [comment]
At the moment when "Show all tags without categories" is selected, the box "Show all categories" should be deselected!

**Comment by acid** [comment]
I think, this should be two bugs. The first is the database error and the second the deselection.

**Comment by acid** [comment]
The database error can't be reproduced anymore.

**Comment by tyranja** [comment]
Then I will close this! Thanks for checking! :smile_cat:
