### ISSUE TITLE
tests for admin section

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#345]
until now there are no tests available for the admin sections and functions. Since admins can control almost everything it would be great to have tests for those actions.

**Comment by zaziemo** [comment]
e.g. profile
* are all profiles shown?
* delete profile works
* edit profile works
* publish profile works

**Comment by zaziemo** [comment]
@Ressy77 and @essymo are working on that.

**Comment by zaziemo** [comment]
@Ressy77 @essymo I'm not sure what you are planning to add as tests but it would also be great to test if only the admin is able to assign categories to tags.

**Comment by essymo** [comment]
Yeah will do that too

On Friday, 11 September 2015, Maren Heltsche <notifications@github.com>
wrote:

> @Ressy77 <https://github.com/Ressy77> @essymo <https://github.com/essymo>
> I'm not sure what you are planning to add as tests but it would also be
> great to test if only the admin is able to assign categories to tags.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rubymonsters/speakerinnen_liste/issues/345#issuecomment-139537306>
> .
>


-- 
Esther Monchari
Business Information Technology
Skype Esther.Monchari
