### ISSUE TITLE
bug: tag merging and deleting

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#353]
currently it seems there are two problems when tags are merged, e.g. #communication into communication
1) admin interface counting doesn't sum up
2) if one user deletes the tag afterwards it is deleted on the other profile as well

**Comment by zaziemo** [comment]
#test tag deletion
  #case 1: there are two users, user 1 creates tag 'sommer', user 2 uses the same tag 'sommer', 
  #user 1 deletes tag 'sommer', user 2 should still have 'sommer' as a tag
  #case2: there are two users, user 1 creates tag 'sommer', user 2 uses the same tag 'sommer', 
  #user 2 deletes tag 'sommer', user 1 should still have 'sommer' as a tag
  
  #test tag merging (config/initializers/acts_as_taggable_on.rb)
  #case 3: there are two users, user 1 creates tag 'sommer', user 2 creates tag '#sommer', 
  #admin merges '#sommer' into 'sommer', user 2 should have tag 'sommer'
  #case 4: there are two users, user 1 creates tag 'sommer', user 2 creates tag '#sommer', 
  #admin merges '#sommer' into 'sommer', admin interface should count 'sommer' 2 times
  #case 5: there are two users, user 1 creates tag 'sommer', user 2 creates tag '#sommer', 
  #admin merges '#sommer' into 'sommer', #user 1 deletes tag 'sommer', user 2 should still have 'sommer' as a tag

**Comment by tyranja** [comment]
Thats done?

**Comment by tyranja** [comment]
Done
