### ISSUE TITLE
unifiying test environments

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#356]
Currently we have tests in 3 different test environments:
-test unit
-cucumber
-rspec.

But tests should be written mainly in rspec and basic tests can stay in test unit.

Todo: 
- translate cucumber tests into rspec

**Comment by nerdinand** [comment]
I'm working on this.

**Comment by nerdinand** [comment]
Consider this done: #405

**Comment by tyranja** [comment]
Thanks!!!!!!!!! :bouquet:
