### ISSUE TITLE
50% database: transfer history data into database

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#361]
All the history data should be transferred into the new database.

**Comment by madny** [comment]
There is an entry on "La barbe" on page 5 of the historic data. Should it stay in the database (or rather go into the blog?) thanks for a short briefing what to do with it @tyranja

**Comment by tyranja** [comment]
Hey @madny can you give me the event number? I can't find it :( 

Just in case you write sth in the blog, the english translation doesn't work yet ...

**Comment by madny** [comment]
P.S. Waht to do with double entries? (view TEDxBerlin Cities 2.0) @tyranja

**Comment by tyranja** [comment]
I would delete one of them.

**Comment by madny** [comment]
ok for 2. question. where do i find the event number? (sorry, had just a short intro)

**Comment by tyranja** [comment]
in the url:

eg "https://50prozent.speakerinnen.org/admin/events/97"

**Comment by madny** [comment]
No. 175, but just saw that further on there are other "wrong" entries (that probably should be in the blog, not in the database > no. 103, 102, 100, 91, 87, 86

**Comment by tyranja** [comment]
Then put them in the blog, there probably was not a thing like the blog at that time .... thanks for the work!!

**Comment by madny** [comment]
Euuhm, not quite shure how to handle the Blog. @zaziemo just showed me the database... Could either you take over or @zaziemo explain that to me later...

**Comment by madny** [comment]
Hui, everything in red! And the percentages of women! Nice! I'm going on transferring data (page 7/9)...

**Comment by tyranja** [comment]
I redesigned a bit :) I will tell Anne that we are nearly done transfering and if she has any objections against publishing the website \o/. Thanks for all this copy and pasting without a mouse!!!!

**Comment by madny** [comment]
DONE! All ancient data are transferred (but not the blog posts, could one of you please do it?!)
Best, Mandy

**Comment by zaziemo** [comment]
YAY!!! <3 <3 <3

**Comment by tyranja** [comment]
@madny  THANKS!!! COOL. I will check for the blogposts!

**Comment by zaziemo** [comment]
thank you @madny :)
