### ISSUE TITLE
inuit/css questions

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#364]
- when scrolling down the images of the profiles stay over the header 
- I have added font-size: 24px to the form and now the button and the formfield are correctly aligned
- changed the color of the button for a try
- added font-awesome for icons http://fortawesome.github.io/Font-Awesome/ https://github.com/bokmann/font-awesome-rails
- fixed all the tests (one test is failing now and then, just reload on the Travis webpage and its all green again) \o/
- for the contact form in the profile show view we need to add the correct javascript, I delete now all the bootstrap javascript as well and used jquery for tooltip
- check responsiveness

**Comment by tyranja** [comment]
Let us make sure, that all the test are green in the inuit branch from now on

**Comment by zaziemo** [comment]
since @tyranja removed bootstrap - conacting a speaker isn't possible anymore
>> rebuild with jquery? or other possibilty

**Comment by zaziemo** [comment]
it's possible to use bootstrap in admin interface and inuit in the other parts

**Comment by tyranja** [comment]
I think, that makes no sense, then we would have to load all the bootstrap things again. But I am nearly done!

**Comment by tyranja** [comment]
I think I finished refactoring all the views with inuit. Just the issues with the profiles and the contact form on the profile show view are still there. I kept them for you ;) 

I added a better limitation for the length of the maintopics and I added the functionality to edit the position of the medialinks for the admins.

**Comment by zaziemo** [comment]
@sabrina-ulbrich @bioshrimp here are the CSS-Todos @tyranja left us.
I add the following things: 
*buttons > please adjust them to the current design in production (speakerinnen.org), means shadow and round corners
*grid of selected profiles on homepage (has to be adjusted properly)
*some elements (eg. profile pictures on the homepage and tag boxes in profile/edit) don't disappear when scrolling over the header

**Comment by sabrina-ulbrich** [comment]
@zaziemo regarding grid of selected profiles: not the full solution but maybe one step: define in the class 'photo--grey': width: 100% (but the left picture is wider than the others)

**Comment by zaziemo** [comment]
@sabrina-ulbrich cool :) Will you try to fix it?

**Comment by tyranja** [comment]
@zaziemo I did the thing with the contact form. I hope its ok with you, I just wanted to do sth productive ;)

**Comment by zaziemo** [comment]
@tyranja yeah :+1:  everything is fine with me. I think there are some more issues left to be solved by me !

**Comment by zaziemo** [comment]
current bugs on staging CSS:
*search box in english locale is cut because of shorter links

**Comment by zaziemo** [comment]
Now all the CSS problems should be solved. Yay :) I pushed the current status of branch inuit-css-refactoring-rails4 to staging. It would be great if all of us @sabrina-ulbrich @bioshrimp and @tyranja (if possible) test it and add comments if something is strange. Next week, Regine will be at Rubymonstas and could help solving remaining problems.

**Comment by zaziemo** [comment]
*profiles edit: input fields could be longer, there is enough space  - right now urls and longer names are cutted

**Comment by tyranja** [comment]
cool. I could do that with the profile edit fields

Is it already responsive?

**Comment by zaziemo** [comment]
@tyranja great :+1: We didn't yet test for responsiveness but we kept that in mind all the time. But you are right we have to keep an eye on reponsiveness while testing.

**Comment by tyranja** [comment]
on the index page the boxes of the speakers are a bit moved to the right, compared to the border line in top of them ...

**Comment by zaziemo** [comment]
@tyranja that's right. We didn't manage to build the grid perfectly. That is one thing we hope to solve with Regines help. If it doesn't work we will leave it like this. Pragmatism rules ;)

**Comment by tyranja** [comment]
I have another thing ;) 
In march this year a lot of the inuit code on github changed. If you compare our trumps.width.scss (https://github.com/rubymonsters/speakerinnen_liste/blob/inuit-css-refactoring-rails4/app/assets/stylesheets/inuit/_trumps.widths.scss)  with the current file on github: https://github.com/inuitcss/trumps.widths/blob/master/_trumps.widths.scss you can see it.

When we want to use the responsive width file, its not working (you get an error message) because of the changes in the whole inuit project. I guess we have to update all our inuit files. :(  Maybe you could ask Regine.

**Comment by zaziemo** [comment]
@tyranja Regine says we could use the resposive file of the same version we are using right now and update everything another time.

**Comment by tyranja** [comment]
![startpage_palm-01](https://cloud.githubusercontent.com/assets/1218914/8405586/ea3bc258-1e55-11e5-9557-0a173e11a5b5.jpg)
For the smartphone version?

**Comment by zaziemo** [comment]
@tyranja you mean if we like the header design?
Me: yes.

**Comment by tyranja** [comment]
Well, that was a suggestion, how we could do it. It's just a jpeg right now and not implemented ...

**Comment by zaziemo** [comment]
Didn't we plan to remove the jpeg on smaller screens and to show only Home instead?

**Comment by tyranja** [comment]
yes, but I kind of like to have the logo still on top.

**Comment by tyranja** [comment]
Or, we remove the logo and have in the menü also home as a link?

**Comment by zaziemo** [comment]
jep, great. Do you have time to implement it? Or a hint how we can implement it this evening with @sabrina-ulbrich and @bioshrimp?

**Comment by tyranja** [comment]
I would like to start. But I willl send you the link anyway and tell you later how far I got.

**Comment by zaziemo** [comment]
@tyranja cool!

**Comment by zaziemo** [comment]
done with the help of all @bioshrimp @sabrina-ulbrich but mostly by @tyranja! You rock :)
