### ISSUE TITLE
Upgrade to cedar-14

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#365]
when deploying to heroku, we get that message:

Cedar-10 will reach end-of-life on November 4th, 2015.
remote:  !   Upgrade to Cedar-14 at your earliest convenience.
remote:  !   For more information, check out the following Dev Center article:
https://devcenter.heroku.com/articles/cedar-14-migration

**Comment by tyranja** [comment]
@svenfuchs I have upgraded the staging version of speakerinnen and everything seems to work. You think, I can do the same with the production version? Just counter-checking ;)

**Comment by svenfuchs** [comment]
@tyranja I haven't done this upgrade on any of my/our apps so far, so you probably have a more educated opinion at this point thatn I do :D 

But yeah, if it worked on staging, that should be good. I'd possibly capture and download a db backup just to be sure, even thought that's probably not necessary at all.

**Comment by tyranja** [comment]
Thanks @svenfuchs 

Its done!
