### ISSUE TITLE
responsivness: design for mobile

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#374]
@bioshrimp suggests:
- having pictures seperately under text and crop it to a smaller size
- then the texts don't need to have the white frame
- texts and profile pictures should be centered
- somehow the app doesn't yet adapt to the current screen size

**Comment by zaziemo** [comment]
* check out: smaller spacing of text, smaller pictures (text should fit into picture)

**Comment by bioshrimp** [comment]
examples: 
* http://hem.com/de/
* https://www.airbnb.de/
* http://www.fitbit.com/de/home

**Comment by tyranja** [comment]
The navbar isn't scrollable in the mobile version.

**Comment by tyranja** [comment]
@bioshrimp can we work with you on that? Maybe just with the Marie Curie picture and delete the other?

**Comment by bioshrimp** [comment]
@tyranja sorry, didn't see this til now. sure!
I am not sure I understand correctly what you are asking though, are you at the monstas tomorrow? :)

**Comment by zaziemo** [comment]
@bioshrimp I think we wanted to have a more sophisticated solution for the pictures and the overlaying headlines in the mobile version. You added the examples above as models. Right now in the mobile version only a cutting of the picture is shown. I think you mentioned (somwhere in the past) to have a smaller picture and display the headline below the picture.

**Comment by tyranja** [comment]
Looks like this is done with getting back to bootstrap
