### ISSUE TITLE
ActsAsTaggableTags in the database should all be lowercase

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#378]
When you save a tag now, it's gets saved lower case in the database, but we only added that configuration later after some tags where already saved. So we have to change all the upper case tags in the database to lower case. 

I think that's one of the problems I had with merging tags lately.

**Comment by tyranja** [comment]
Solved. With a huge help of @ur5, thanks!

I (or rather @ur5) wrote two rake task. The first finds all the tags that are upper case as well as lower case and merge them. The second rake task converts all tags in lower case. 

We had 14 double tags and 1755 were upper case.

**Comment by zaziemo** [comment]
Yay! Thank you @tyranja & @ur5!!! <3
