### ISSUE TITLE
restore heroku database auto backups 

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#379]
We have now two heroku databases for speakerinnen-liste. Would be good to delete one.

And we don't have automatic backups any more :(

**Comment by zaziemo** [comment]
argh, why is that?

**Comment by tyranja** [comment]
I don't know. After may 19 we have no more backup data.

**Comment by zaziemo** [comment]
hum, I see now that I/we got an email concerning backup migrations on the 27th of may. I will forward the email to you. Probably it is just stored at another place.

**Comment by tyranja** [comment]
Thanks for the email. Done thanks to @svenfuchs!!! Mörci!!
