### ISSUE TITLE
get directed to the profile page after signing in?

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#383]
Does it make sense to land on your profile page instead of the main page after signin in?

**Comment by zaziemo** [comment]
Not a bad idea, given that people want to edit their profile after signing in.
Can we see somewhere (in piwik?) where people are going after signing in?

**Comment by zaziemo** [comment]
@tyranja I'm going through the open issues right now. Just do this redirection. Makes sense :)

**Comment by zaziemo** [comment]
@tyranja I'm currently trying that out. One thing is a bit strange:
- after sign in and redirection I get the confirmation message: "Du bist bereits angemeldet." - should probably be "Du bist jetzt angemeldet."

**Comment by tyranja** [comment]
Yeh, thats right. I found that irritating too.

**Comment by zaziemo** [comment]
should we only change the text or is that a special message that should stay if people are trying to sign in when they already signed in?

**Comment by tyranja** [comment]
I check

**Comment by tyranja** [comment]
I will push the branch to staging and try there.

**Comment by tyranja** [comment]
Now it seems to work correctly

**Comment by tyranja** [comment]
Done!

 https://github.com/rubymonsters/speakerinnen_liste/tree/ty_new-redirection-for-devise
