### ISSUE TITLE
No fallback, when no profile in index.html

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#384]
We got lately a lot of error reports (like this:
```undefined local variable or method `profile' for #<#<Class:0x007f146dd0fd58>:0x007f146d0613b8>```

 from rollbar, now I got the reason:
when the profiles controller finds no profiles in index.html, the app throws an error.

**Comment by tyranja** [comment]
I hope I fixed that bug with the last commit. 

@maren do you get emails from rollbar at all?

**Comment by zaziemo** [comment]
@tyranja yeah, I get them but I don't look at them until now. I should, hum !?

**Comment by tyranja** [comment]
I guess :D

I didn't take them serious as well ...
