### ISSUE TITLE
moderate and activate entries on 50% database

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#386]
@madny would like to do that. We have to set up an account for her and explain the workflow for activating the entries.

**Comment by madny** [comment]
yeah! let me know when you put me on admin (or sth. similar) and I'll be happy to do this...

**Comment by zaziemo** [comment]
@madny you arrrrre already an admin :) just try out!

**Comment by zaziemo** [comment]
@tyranja I think that's something you should do when you are back from holidays :) I have no idea how to do that.

**Comment by tyranja** [comment]
Done! I have send you an email @madny  and thanks for the offer :sparkles:
