### ISSUE TITLE
application_controller_spec

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#387]
... must be added.

**Comment by zaziemo** [comment]
Apparently you don't test the application controller itself but have to create a kind of anonymous controller as explained here: https://www.relishapp.com/rspec/rspec-rails/docs/controller-specs/anonymous-controller

**Comment by n3k00n3** [comment]
Where `after_sign_in_path_for` is used? if is it used?
What the `resource` parameter means?

**Comment by zaziemo** [comment]
Hey @n3k00n3, this method redirects the user to her own profile if she signed in. Do you already know the "blame" view here on github? https://github.com/rubymonsters/speakerinnen_liste/blame/master/app/controllers/application_controller.rb
It helps you to find out who changed the particular code snippets and in the context of which commit. In this case @tyranja wrote really cool explanatory commit messages that explain the background of this method - what we didn't always do in the past - I must admit :)  
If you have further questions don't hesitate to ask!
