### ISSUE TITLE
profile edit: contact

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#388]
currently when user is in profile/edit and clicks the contact button it is missleading where the email is sent to:
![bildschirmfoto 2015-08-20 um 18 53 29](https://cloud.githubusercontent.com/assets/2119496/9389748/e1d0dd5c-476c-11e5-8ce9-4ca86098db57.png)

actually the email isn't been sent to the Speakerinnen-Team but to the person itself.
I think we should 
* disable that button in the edit view
* add the footer on every site

**Comment by tyranja** [comment]
Done.

https://github.com/rubymonsters/speakerinnen_liste/commit/1dedfd949d0596135baadcfe7480f8a3ab97c9e3
