### ISSUE TITLE
translation of How To Guide german > english

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#394]
We want to provide a how to guide for our speakers who want to register and edit their profile.
Currently we have the text written in german and screenshots to illustrate the individual steps.

We need the texts translated into english (the english language screenshots will be added afterwards. 

The whole document can be found here as PDF: https://drive.google.com/file/d/0B1D1qcLPu9SSeWE4MUxrd250eUU/view?usp=sharing 

The plain text can be found here as plain text: https://gist.github.com/zaziemo/b71011eec2af5c1f279d

**Comment by robinboening** [comment]
Hey @zaziemo as discussed, we pick this issue for the next edition of rubyissues. :dancers: 

How should the contribution workflow look like? I mean: should the translation be provided as text on this issue? (attached pdf for example)

**Comment by zaziemo** [comment]
@robinboening great \o/ It would be perfect to have it as a plain text format. Either in our gist or in an own one.

**Comment by SonjaHeinen** [comment]
Hi Maren, I created a fork of this Gist with the English translation. You can find it here: https://gist.github.com/SonjaHeinen/d7923436ad250525ddc9 
Let me know your thoughts.

**Comment by zaziemo** [comment]
@SonjaHeinen awesome :) Thx a lot!

**Comment by tyranja** [comment]
@SonjaHeinen Cool :smile: Thanks for the work!!!

**Comment by zaziemo** [comment]
@tyranja do you have time to build that How-to-subsite or integrate it in the FAQ section?

**Comment by tyranja** [comment]
Yes, maybe not today but this week. I would integrate it in the FAQ section.

**Comment by zaziemo** [comment]
@tyranja cool :) wasn't meant to be right now!

**Comment by tyranja** [comment]
Done! Thanks to @SonjaHeinen :confetti_ball: 

https://speakerinnen.org/en/faq#howto_anker
