### ISSUE TITLE
add country field in profiles table

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#396]
so speakers can add their country to their current location. This makes it easier for event organizers to search and browse for speakers based in their countries of interest. 

It would be great to have a drop down menu where the speakers can choose from. Is there probably a gem that helps doing it and already provides lists of countries in different languages? @tyranja uses something similar for the languages (https://rubygems.org/gems/language_list/versions/1.1.0) so they are searchable (see #264). 

- add a migration to add the new column
- make fields visible in profile edit / show
- write tests

- add in the detailed search the country field ( https://github.com/rubymonsters/speakerinnen_liste/blob/master/app/models/profiles_search.rb and here https://github.com/rubymonsters/speakerinnen_liste/blob/master/app/views/shared/_profile_search.html.erb)

**Comment by aparnagireesan** [comment]
Hi, I would like to work on this bug. Could you please help me get started with this?

**Comment by zaziemo** [comment]
@n3k00n3 @geisasantos it would be cool if you could solve that issue before we launch the portuguese locale. If you have other plans, let us know and we have to work on this :)

**Comment by n3k00n3** [comment]
@zaziemo oh yeah! I can do it.

**Comment by tyranja** [comment]
Thanks @n3k00n3 and @geisasantos for the great work! :tada:
