### ISSUE TITLE
Profile edit: button translation

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#397]
apparently the button for uploading the picture has the text "Datei auswählen" even in english ;) We have to change that.

**Comment by tyranja** [comment]
I just see the button "browse" in german and english :hushed:

**Comment by zaziemo** [comment]
hehe ;) have a look at the screenshot - probably these ones are controled by the browser settings

**Comment by nerdinand** [comment]
I'm pretty sure this is about the browser language... I think this can be closed.
