### ISSUE TITLE
Database Seeds

### ISSUE THREAD

**Issue by dmarcoux** [rubymonsters/speakerinnen_liste#400]
While reading the CONTRIBUTING.md file, I saw that you are manually seeding the database by using the rails console. It does work, however it is much longer than seeding the database automatically with a rake task.

TODO:
1. Rake task
2. Update documentation

**Comment by dmarcoux** [comment]
I am working on this...

**Comment by dmarcoux** [comment]
Basic seeds are now in the project following #402. However, they can be improved a lot since only Profiles are added.

**Comment by zaziemo** [comment]
thank you @dmarcoux!
