### ISSUE TITLE
feature: use autocompletion for better search results

### ISSUE THREAD

**Issue by 1000miles** [rubymonsters/speakerinnen_liste#401]
Hey, we'd love to open a new ticket to suggest autocompletion upon some observations we made. :)
To solve this problem of not knowing how different people think differently when using tags/categories (for search and definition), maybe autocompletion would help to list all existent tags/categories?

What do you think? :)

Best,
Thuy

cc @acid
## Cases to recap:
- when typing "Anti-Rassismus" in search input field, then no results are found
- when typing "Antirassimus" in search input field, then 10 results are found
- when typing "Rassismus" in search input field, then the 11 profiles shown here are not the same and not included in the search for "Anti-Rassimus" or "Antirassismus" even though these 2 words contain "Rassimus"

**Comment by tyranja** [comment]
Belongs to #439
