### ISSUE TITLE
recommendation feature on website

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#408]
We should provide the possibility to recommend our site to potential speakers.
Via email and via twitter (first ideas).
We should provide a text that can be changed.

**Comment by tyranja** [comment]
something like that? https://about.twitter.com/de/resources/buttons#tweet

**Comment by geisasantos** [comment]
Hey, @zaziemo @tyranja !
That's a great idea. How this recommendations will work?
Will it be sent from users, from Speakerinnen's team?

Maybe we can provide an area in the site for this. A simple form like "Do you have something interesting to say?" area. It may be: "Do you know someone who might be here? Invite her!".

What do you think?
That way we can customize better for e-mail, Twitter, Linkedin and others. (without using Twitter API)

**Comment by zaziemo** [comment]
Hey @geisasantos,

yeah, it should be something like "Do you know someone who might be here? Invite her!".
It would be cool if the person who recommends is the sender of the message or shares it via his or her own account/email address (so I think it is more personal and credible).
Better than a simple form would be something like recommendation icons as they are often used by media or blogs e.g.: https://www.theguardian.com/us-news/2016/jul/15/republicans-quash-last-ditch-attempt-to-stop-donald-trump-becoming-nominee (below the date - unfortunately I can't upload a screenshot because I'm in the train with a bad internet connection) 

If you have to use twitter authentication, we can provide you with the key we also use for the sign up process.
