### ISSUE TITLE
Piwik broken?

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#411]
![bildschirmfoto 2015-10-20 um 18 05 35](https://cloud.githubusercontent.com/assets/2119496/10613450/7cbbd53e-7755-11e5-904c-155cf6178758.png)

**Comment by zaziemo** [comment]
I talked to Edna about that. Apparently the account on uberspace ended and we need to reinstall and host it somewhere else. Checking out the possibilities on heroku.

**Comment by tyranja** [comment]
I am at uberspace as well. Maybe I can do that?

**Comment by zaziemo** [comment]
@tyranja Edna said that it's probably too late to move it to another account. I will take care of it since you already have so many things to do.

**Comment by tyranja** [comment]
OK. But it seems to be really easy.https://robtranquillo.wordpress.com/2015/06/29/piwik-installieren-auf-uberspace/

**Comment by zaziemo** [comment]
:) so do it if you want!

**Comment by tyranja** [comment]
No, I just pasted it there, in case I want to find it again. Its your thing! I don't even know what to do with it.

Its raining in BCN :(

**Comment by zaziemo** [comment]
@tyranja humpf, we need a mysql database to store the piwik information. which means we can't use heroku for that. So what about you installing Piwik on your uberspace and I will implement everything afterwards?

**Comment by tyranja** [comment]
OK

**Comment by zaziemo** [comment]
done. ouufff!
