### ISSUE TITLE
Aufteilung 50 Prozent Kontakt zum Veranstalter-Feld

### ISSUE THREAD

**Issue by anneroth** [rubymonsters/speakerinnen_liste#419]
Im Formular für neue Events bei '50 Prozent' gibt es jetzt ein Feld "Wie kann die Veranstaltung kontaktiert werden?". Aus dem einen Feld sollten mehrere entstehen
1. "Twitter-Account"
2. "E-Mail-Adresse"
3. Kontaktseite (URL)

Ideal wäre, wenn jeweils auch mehrere untereinander eingegeben werden könnten, weil manchmal mehrere Organisationen / Unis / Unternehmen eine Veranstaltung organisieren und entsprechend mehrer Angaben gleichberechtigt aufgeführt werden.

**Comment by tyranja** [comment]
So @anneroth jetzt schau mal nach, ob es so ok ist. Ich habe jetzt zwei neue Felder hinzugefügt. 

Das Problem bei noch mehr Feldern wäre, wieviel müssen da noch als Option vorhanden sein und all die Kontaktfelder könnten im Frontend auch seltsam aussehen und evt verwirren.

**Comment by anneroth** [comment]
Danke! Dass mehr mehr Konfusion schafft, stimmt. Ist halt manchmal schwierig, wenn mehrere ein Event organisieren, weil, wen nimmst du dann? Aber vielleicht müssen wir da im Frontent irgendwann nochmal über Alternativen nachdenken. 

Ansonsten könnte meiner Ansicht nach ganz unten bei den Kontaktangaben der Eingebenden was weg: E-Mail und Kontakt-URL. Mail wird kaum wer angeben wollen, und wer hat schon eine Kontakt-Seite?
