### ISSUE TITLE
Datenschutz-Erklärung/data privacy statement

### ISSUE THREAD

**Issue by anneroth** [rubymonsters/speakerinnen_liste#422]
Um die zu erstellen, muss zuerst aufgeschrieben werden, was alles gespeichert wird. Damit kann dann hoffentlich einigermaßen einfach eine Datenschutzerklärung erstellt werden, zB mithilfe dieser Seiten: 
Tips für Impressum und Datenschutz:
http://rechtsanwalt-schwenke.de/smmr-buch/datenschutz-muster-generator-fuer-webseiten-blogs-und-social-media/
http://www.e-recht24.de/muster-datenschutzerklaerung.html
http://www.it-recht-kanzlei.de/datenschutzerkl%C3%A4rung-muster.html
Und ein paar Hinweise dazu
http://www.socialmediarecht.de/2011/04/04/rechtliche-hinweise-zum-bloggen-i-impressum-und-datenschutz/
Ein Generator fürs Impressum
http://www.juraforum.de/impressum-generator/

**Comment by zaziemo** [comment]
Hey @anneroth, jetzt haben wir eine Datenschutzerklärung: https://www.speakerinnen.org/de/impressum Schau doch bitte mal drauf.

**Comment by zaziemo** [comment]
Text noch gendern

**Comment by anneroth** [comment]
Mache ich heute abend!

BG
Anne

Maren Heltsche:

**Comment by zaziemo** [comment]
@anneroth machst du hier noch etwas oder kann ich das Issue schließen?

**Comment by tyranja** [comment]
@anneroth hast Du das noch auf dem Schirm?
