### ISSUE TITLE
Blog-Kategorien

### ISSUE THREAD

**Issue by anneroth** [rubymonsters/speakerinnen_liste#423]
Es gab den Vorschlag, die drei Kategorien in vier zu erweitern: 

- Expertinnen (Listen / Datenbanken ähnlich wie Speakerinnen-Liste) /experts
- Statistiken (Zählprojekte/-artikel) /counting
- Methoden (Gute Beispiele, wie es besser wird) /techniques 
- Aktionen (Protestformen) /actions

Wenn es die gibt, müssen die alten Blogposts neu einsortiert werden.

**Comment by tyranja** [comment]
Die Kategorien gibt es jetzt.

**Comment by zaziemo** [comment]
@anneroth du kannst jetzt sortieren ;)
