### ISSUE TITLE
contact via email: does not work properly if not all formfields are filled out

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#424]
If I want to contact a speaker via the contact button and by mistake don't fill out every field I get an error message and I'm redirected to another site which tells me to fill out every field.
I write something in the empty field and click on "send" and I get an empty white site with "ok".

There are three problems with that:
- the email is not sent unless the status site said "ok"
- why are we redirected to the other site and don't stay on the "normal" email conversation site?
- the status site after filling out the missing form fields should not be a seperate site but a flash message

**Comment by tyranja** [comment]
In https://github.com/rubymonsters/speakerinnen_liste/blob/master/app/controllers/contact_controller.rb is a method: reject_spam_bots, that checks if there is an email address in the address input field. And if then it renders for the bots the text "ok". 

How come we get to it?

**Comment by zaziemo** [comment]
when does the error happen?
when you enter at least the email address and the submit, you get the error message that you have to fill out all form fields.
You fill them in > submit > ok site

**Comment by tyranja** [comment]
I think I have solved it \o/ Lets look at it monday. I stil need to write a test for it. 
https://github.com/rubymonsters/speakerinnen_liste/tree/ty_test_profile_contact

**Comment by zaziemo** [comment]
thx, @tyranja!
