### ISSUE TITLE
Notes to the new search

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#426]
- [x] Ich frage mich worin der Unterschied besteht, zwischen den Themen (topics), die man in der Detailsuche angeben kann und denen, die unten unter der gleichnamigen Überschrift aufgelistet sind. Das ist vielleicht verwirrend, also vielleicht anders benennen oder einen Satz zur Erklärung.

- [x] Gibt es einen Grund, weshalb die Topics nicht mehr auf der Homepage angezeigt werden? Im Link steht noch Categories and Topics >> aber wenn man da drauf klickt, dann werden nur die Categories angezeigt.

- [x] zum Style: Die Liste der topics auf der Suchseite ist als einziges Element eingerückt, wäre besser links gleichmäßig abzuschließen.

- [x] Wenn man auf einen Link in den Topics klickt, dann fehlt auf der Folgeseite, die die entsprechenden Speakerinnen anzeigt, der Footer. Sollte der nicht auf allen Seiten sein? (Sieht ein bisschen „abgeschnitten" da unten aus.)

- [x] Werden eigentlich Links aus der Topic-Liste gelöscht, wenn Speakerinnen diesen Topic bei sich löschen? In staging gibt es zu „pretty“ gar keine speaker.

- [x] Wollte gerade einen neuen Account anlegen, da sehe ich auf der Seite "Update your profile“ über dem Feld für Language folgenden Text: "Languages<br><small>Please add programming languages in 'Topics', not here</small>"

- [x] So auf die schnelle fällt mir auf das auf der Startseite "unsere Kategorien" steht, aber wenn man auf was raufklickt, "Bildung" z.b., und man zu Ergebnisliste kommt, dort dann aber groß "Themen" steht wo man wieder was suchen kann.  Also kann man in "Kategorien" nach "Themen" suchen? Find ich verwirrend, weil es sich wie das gleiche anhört. 

- [x] Die Ergebnisse (speakerinnen) zur Kategorie "Bildung" stehen sehr weit unten. Hab ich erstmal glatt übersehen. Kann man die vielleicht höher rücken?

- [x] Themen "quick search", wenn ich "Ruby" eingebe finde ich nichts wenn ich aber unter "speakerinnen" nach Ruby suche werden mir Profile angezeigt. Find ich auch etwas verwirrend. :)

**Comment by tyranja** [comment]
6. is done.

**Comment by tyranja** [comment]
6. is done
5. wir haben nur ~4 speaker auf staging

**Comment by tyranja** [comment]
Added a placeholder in quick search: "name or twitter handle"/"Name oder Twitterhandle" for a better understanding of the quick search field. @zaziemo Is the description clear?

**Comment by tyranja** [comment]
@zaziemo  Should we change "themen" zu "topics"?

**Comment by tyranja** [comment]
zu 8. Das stimmt voll. Evt zuerst die Speakerinnen zeigen und dann die dazugehörigen topics?

**Comment by tyranja** [comment]
zu 4. Thanks for pointing that out @sabrina-ulbrich there  was a bug indeed. Is fixed now :smile_cat:

**Comment by zaziemo** [comment]
"*zu 9. Added a placeholder in quick search: "name or twitter handle"/"Name oder Twitterhandle" for a better understanding of the quick search field. @zaziemo Is the description clear?*"

yes it is clear. But it's not what it really searches. You can also look for topics in quick search, can't you?

**Comment by zaziemo** [comment]
*"Should we change "themen" zu "topics"?"*

but it is the same, isn't it?

**Comment by tyranja** [comment]
I have changed the view of topics, search and category and pushed to staging.

**Comment by tyranja** [comment]
@sabrina-ulbrich @bioshrimp We pushed the search now to production \o/ 

But we definitely have to think about the naming of the tags! Are you at the monstas monday?

**Comment by zaziemo** [comment]
ad 1) change title of "topics" into "all topics"

**Comment by sabrina-ulbrich** [comment]
done :)
