### ISSUE TITLE
Speeding up with indexes

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#427]
Should we use that to display and add missing indexes? The app still seems to be still slow.

https://github.com/plentz/lol_dba

http://rakeroutes.com/blog/increase-rails-performance-with-database-indexes/

http://weblog.rubyonrails.org/2011/12/6/what-s-new-in-edge-rails-explain/

**Comment by zaziemo** [comment]
I think it is already pretty fast :) But let's discuss that in the evening at the Monstas meeting.

**Comment by tyranja** [comment]
done!
