### ISSUE TITLE
Logo-Link im Blog

### ISSUE THREAD

**Issue by anneroth** [rubymonsters/speakerinnen_liste#431]
Auf blog.speakerinnen.org führt das Logo oben links nicht zur Speakerinnen-Liste, sondern zur Blog-Hauptseite. Das ist verwirrend, weil das Logo ja zur -Liste gehört. Können wir ein neues Logo für's Blog? Sonst besser Text ("Speakerinnen-Blog"), und das Logo rechts für den Link zur -Liste.

**Comment by tyranja** [comment]
Ich habe jetzt den link zur speakerinnen liste ans logo gehängt.

**Comment by zaziemo** [comment]
danke @tyranja
