### ISSUE TITLE
Sprachen in der Suche

### ISSUE THREAD

**Issue by anneroth** [rubymonsters/speakerinnen_liste#432]
Aktuell können in der Suche ganz viele Sprachen ausgewählt werden. Die meisten davon haben wir wahrscheinlich gar nicht? Lässt sich das auf die in den Profilen erwähnten reduzieren?

**Comment by zaziemo** [comment]
@anneroth das wäre ziemlich kompliziert. Ist das sehr störend?

**Comment by sabrina-ulbrich** [comment]
Tatsächlich sind nur 9 der 33 Sprachen nicht vertreten (was ich ziemlich bemerkenswert finde, yay) - hab ich gerade ausprobiert. Allerdings erscheint mir die Reihenfolge etwas durcheinander, wäre es nicht besser für die Suche, wenn man das alphabetisch sortieren würde? @tyranja 
Was passiert eigentlich, wenn jemand eine Sprache eingibt, die noch nicht in der Liste ist? Wird die dann hinzugefügt?

**Comment by tyranja** [comment]
Nein, die Sprachen werden händisch eingegeben für die Suche. Wir habens zum Schluss einfach gehalten.
Das mit den nicht alphabetisch sortieren habe ich gar nicht bemerkt. Good point!

**Comment by anneroth** [comment]
@zaziemo Nein, davon geht die Welt nicht unter. Ich hatte auch wirklich nicht damit gerechnet, dass soviele in den Profilen stehen - mea culpa. Falls es geht, würde ich zum Sortieren vielleicht vorschlagen, dass Deutsch und Englisch ganz oben stehen, und dann der Rest alphabetisch?

**Comment by tyranja** [comment]
ok, wird gemacht.

**Comment by tyranja** [comment]
Done and on production
