### ISSUE TITLE
Quick search fails when input contains of more than on word

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#435]
... Christiane ist gerade aufgefallen, dass AND-Verknüpfungen in der Quick-Search nicht (mehr?) gehen.
Also Maren Heltsche, "Maren Heltsche" oder Maren AND Heltsche funktioniert nicht.

    it 'displays all profiles that contain search input' do
      visit root_path
      fill_in 'search_quick', with: 'Ada Curie'
      click_button I18n.t(:search, scope: 'pages.home.search')
      expect(page).to have_content('Ada')
      expect(page).to have_content('Curie')
    end

**Comment by tyranja** [comment]
stackoverflow.com/questions/22461042/sending-array-of-values-to-a-sql-query-in-ruby

**Comment by anneroth** [comment]
Bei mir kam gerade Feedback, das ist wahrscheinlich dasselbe? Wenn nach mir mit Vor- und Nachnamen gesucht wird, werde ich nicht gefunden.

**Comment by zaziemo** [comment]
works now but search needs refactoring see #439
