### ISSUE TITLE
Refactor search: implement elastic search

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#439]
search has to use "common" search logic and operators - ideally as it is used by Google search
- AND, OR, NOT operators
- concatination of two words means AND by default ("Ada Lovelace" means Ada AND Lovelace)
- if possible allows the use of wildcards \* or ?
- to be discussed: should parts of the word already match or does it have to be the exact word that is matching? e.g. right now looking for Ada matches firstname Ada but also the twitter handle mADAmecurie

**Comment by zaziemo** [comment]
http://joelabrahamsson.com/elasticsearch-101/
german: http://www.schwarzer.de/blog/elasticsearch-tutorial-das-konzept-verstehen/
Video: https://www.youtube.com/watch?v=P6VqWiXsGIo
Book: https://www.elastic.co/guide/en/elasticsearch/guide/master/index.html

**Comment by zaziemo** [comment]
I think we want to use this gem: https://github.com/elastic/elasticsearch-rails

Here is a tutorial video: 
https://www.youtube.com/watch?v=Pse-2ZkVaTs

**Comment by zaziemo** [comment]
Testing elastic search with RSpec: http://www.binarywebpark.com/testing-elasticsearch-in-your-rails-4-application/

**Comment by zaziemo** [comment]
Heroku Add-on for Elasticsearch: https://devcenter.heroku.com/articles/bonsai

**Comment by svenfuchs** [comment]
@zaziemo @tyranja We know great people at Elastic. I could try ping some folks who might be able to help with an initial implementation, or at least some good advice, if you want.

**Comment by zaziemo** [comment]
@svenfuchs yes, that would be cool. Good advice always helps :)

**Comment by zaziemo** [comment]
have a look on that migration for indexes: db/migrate/20151216091821_add_missing_indexes.rb
do we have to revert it or can we reuse this index?

**Comment by zaziemo** [comment]
- [ ] add Pagination: https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/README.md
- [ ] solve problems with splitting city and languages

**Comment by zaziemo** [comment]
Thanks for your great work @BriocheBerlin. All tests are passing :)

But I realize some crazy behaviour: 

- if the search box is empty and you click on search button 488 search results are shown - but these are not all the profiles. What are they based on?
- if I look for my full name, I get 387 results - I am the first one (yay!) but how can we reduce the other results? Put more weight on fullname? reduce the fuzzyness?
