### ISSUE TITLE
refactor specs for search

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#442]
currently there are two documents for search specs that repeat test cases:
/spec/features/searching_for_profiles_spec
/spec/models/profiles_search_spec

connected to #439

**Comment by zaziemo** [comment]
some more relevant search specs:
/spec/models/admin_profile_search_spec.rb
/spec/views/search_spec.rb

**Comment by tyranja** [comment]
Done :green_heart:
