### ISSUE TITLE
embed testimonial quotes in homepage 

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#443]
create new section on homepage to show quotes of testimonials on our homepage
with a direct anker to the whole quote (so it can be referenced via twitter) 

idea: rotation of quotes

**Comment by geisasantos** [comment]
@zaziemo some questions:
1. Testimonials: 
- From users about Speakerinnen or sent from people who know some speakers?
- We're thinking about random testimonials embed from Speakers' page, like Linkedin's recommendations. 
- Can users send testimonials? If yes, how you want it to be? Through a form or like a comment (and in that comment, there can be a social plugin for sharing)?

2. About Twitter: Can you explain more about it?

**Comment by zaziemo** [comment]
oh sorry, I only see this now.
ad 1) We already have some quotes of people we asked for it recently. I will attach a table with the quotes and the source to your trello card. Right now, we only have german quotes. But we could collect some more (also in english and portuguese).

ad 2) What I mean here is, that the section with the quotes must be sharable and therefore needs an anchor so we can create a link that can be used in a tweet or in a blog post (https://www.w3.org/TR/html4/struct/links.html) --> we also use this in the FAQ section: https://speakerinnen.org/de/faq/#how_to-anker

**Comment by zaziemo** [comment]
- [ ] get quotes (selected from comms team)
- [ ] find place and layout on website
