### ISSUE TITLE
50 Prozent: Jahresangabe Events

### ISSUE THREAD

**Issue by anneroth** [rubymonsters/speakerinnen_liste#445]
Könnten im Formular die Jahre vor 2016 entfernt werden? Oder alternativ 2016 als default eingestellt sein?

**Comment by tyranja** [comment]
Ich habe jetzt 2016 als default, guck doch mal, ob das so okay ist. Ich habe etwas Angst, dass die Leute jetzt evt vergessen, das korrekte Datum anzugeben ... Was meinst Du?
