### ISSUE TITLE
50 Prozent: Ausgabe aktuelles Event

### ISSUE THREAD

**Issue by anneroth** [rubymonsters/speakerinnen_liste#446]
Schick wäre, wenn es die Möglichkeit gäbe, auf der Website die Events auch nach Datum sortiert auszugeben, also alle, die ab jetzt als nächstes noch kommen.

**Comment by tyranja** [comment]
More than a year later: 

![sort_event](https://user-images.githubusercontent.com/1218914/46764267-540fe780-ccdc-11e8-8b04-7bdf8ac48c08.png)

**Comment by tyranja** [comment]
Done!
