### ISSUE TITLE
50 Prozent: Benachrichtigungen

### ISSUE THREAD

**Issue by anneroth** [rubymonsters/speakerinnen_liste#448]
Wir haben nicht so viel Aktivität bei 50 Prozent, deswegen gucke ich da nicht ständig nach neuen Events. Für die User_innen ist das blöd, weil ihre frisch eingetragenen Events manchmal ganz schön lange bis zur Freischaltung brauchen: eine Benachrichtigungs-Mail wäre super.

**Comment by tyranja** [comment]
Gemacht :tada:
