### ISSUE TITLE
switch email client

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#451]
Mandrill will close its free service and we have to find another solution

**Comment by yepher** [comment]
Just incase it can help here is the Mandrill migration to SparkPost [guide](https://www.sparkpost.com/mandrill-migration-guide) and this [Slack channel](http://slack.sparkpost.com) is available if you need help with the migration.

They are giving 100,000 free emails per month.

**Comment by tyranja** [comment]
Thanks @yepher, we will check that out.

**Comment by tyranja** [comment]
https://devcenter.heroku.com/articles/postmark
http://support.postmarkapp.com/article/1003-migrating-your-mandrill-heroku-add-on-to-postmark
 heroku addons:destroy mandrill

**Comment by tyranja** [comment]
touch .env
heroku config:get POSTMARK_API_TOKEN -s  --app staging-speakerinnen-liste >> .env
heroku config:get POSTMARK_SMTP_SERVER -s --app staging-speakerinnen-liste >> .env
heroku config:get POSTMARK_INBOUND_ADDRESS -s --app staging-speakerinnen-liste >> .env
