### ISSUE TITLE
empty profile in the list

### ISSUE THREAD

**Issue by sabrina-ulbrich** [rubymonsters/speakerinnen_liste#454]
seen on the page http://speakerinnen.org/en/profiles

![screen shot 2016-03-03 at 15 38 51](https://cloud.githubusercontent.com/assets/372649/13497596/84f947b6-e156-11e5-8aad-52a0f6ade11a.png)

Is there a test for necessary content for listed profiles?

**Comment by zaziemo** [comment]
@sabrina-ulbrich thx for sharing. Muhaha! We only have tested that only published profiles are displayed. Empty profiles shouldn't be published. I'm not sure how this special case could happen but we don't have a solution that warns us (or hides) profiles that are once published and then emptied. Do you want to write a test for this case or was it "just" a reporting?

**Comment by sabrina-ulbrich** [comment]
@zaziemo I just wanted to report this issue :)

**Comment by zaziemo** [comment]
@sabrina-ulbrich :) as fabulous @tyranja found out while I was responding to the issue: this was only a test profile that we forgot to delete 😁

**Comment by sabrina-ulbrich** [comment]
ok, hahaha, then I close this issue
