### ISSUE TITLE
profile show: improvement of medialinks view

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#456]
currently an empty link is shown as http:// 

if no link is provided this line should be empty or deleted
![bildschirmfoto 2016-03-17 um 10 00 09](https://cloud.githubusercontent.com/assets/2119496/13841137/4bbc2190-ec27-11e5-8862-7505747c5750.png)

**Comment by SanjanaSharma** [comment]
Hello. :) We (Team HolyheadHarpies) would like to work on this issue. We are currently applying for RGSOC 2016 and would like to contribute to this project. Please guide us how to get started. Thank you!

**Comment by zaziemo** [comment]
Hey @SanjanaSharma, cool, thanks for your message! We have some general information on how to get started here: https://github.com/rubymonsters/speakerinnen_liste/blob/master/README.md and here https://github.com/rubymonsters/speakerinnen_liste/blob/master/CONTRIBUTING.md.
Once you are accepted to RGSoC @tyranja and I will be your mentor and show you more details. Right now this issue should be part of your project plan :) Cheers, Maren.

**Comment by n3k00n3** [comment]
@zaziemo 

I think that pr solve this issue.
https://github.com/rubymonsters/speakerinnen_liste/pull/466

**Comment by zaziemo** [comment]
thx a lot @n3k00n3!
