### ISSUE TITLE
Show the profiles always random

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#461]
When clicking on a category or tag we see the profiles sorted by the created_at date. 

That means that the profiles that were created first are always on the last page. 

We should display the profiles random like on the first page: https://github.com/rubymonsters/speakerinnen_liste/blob/master/app/controllers/pages_controller.rb

**Comment by colleenmcguckin** [comment]
I'll tackle this issue!

**Comment by cesc1989** [comment]
I'm going to working on this. Be back in a few days.

**Comment by tyranja** [comment]
Thanks! :heart:
