### ISSUE TITLE
Translate speakerinnen.org into Brazilian Portuguese

### ISSUE THREAD

**Issue by n3k00n3** [rubymonsters/speakerinnen_liste#462]
We want to spread the Speakerinnen's project in our country and motivate brazilian women\* and empower them. So we decided to translate the pages to pt_BR.

**Comment by zaziemo** [comment]
that's a great idea! we also have a translation into french (but it hasn't been implemented yet).
The thing is: with more languages we need more conceptual thinking concerning the usability e.g. profile edit for different languages. It would be cool if you think it through what more languages mean not only for editing but also for searching and browsing the speakers. Then we can discuss it in our call.

**Comment by zaziemo** [comment]
Hey @n3k00n3, 
I merged you pull request and pushed it to staging. It looks great. Thanks for your amazing work!! 
You can access it here and do some more click testing: https://staging-speakerinnen-liste.herokuapp.com

There is one point where the translation is still missing:
the categories 
![bildschirmfoto 2016-07-21 um 11 01 12](https://cloud.githubusercontent.com/assets/2119496/17017383/77f8328e-4f33-11e6-810f-c05572905d98.png)

Besides the layout of the contact form needs a little bit of adjustment
![bildschirmfoto 2016-07-21 um 11 03 11](https://cloud.githubusercontent.com/assets/2119496/17017516/e929c3dc-4f33-11e6-8828-8ead2819efeb.png)

**Comment by zaziemo** [comment]
One more thing I realized while testing: the notification email has also be translated into portugeese - right now there is an error displayed when I try to contact a speaker in the pt-locale. 
You can find the corresponding english mailer-text under app/views/notifications_mailer. There you have to create a new file new_message.pt.text.erb, translate everything that is not embedded ruby.

**Comment by zaziemo** [comment]
there is an own branch for that: https://github.com/rubymonsters/speakerinnen_liste/tree/portuguese_translation

must be updated before launching

**Comment by zaziemo** [comment]
Currently closed until there is a team that wants to take care of it in Brazil.
