### ISSUE TITLE
WYSIWYG editor for blogposts in fifty percent

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#468]
A better editor for the blogposts.

**Comment by tyranja** [comment]
Tested Trix : https://github.com/maclover7/trix  ( does not work with the pics, and does not provide the feature for surrounding text )
Tested cke editor: https://github.com/galetahub/ckeditor ( )


Ideas:
- make a draft mode
- when writing a blog have a markdown translator

**Comment by zaziemo** [comment]
done! thx <<3
