### ISSUE TITLE
Update to Rails 5

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#470]
Right now the App runs on Rails 4 sooner or later we will have to update it.

**Comment by tyranja** [comment]
http://guides.rubyonrails.org/upgrading_ruby_on_rails.html

**Comment by sadiksha** [comment]
Hi, 
Can I start working on this issue?

Best,
Sadiksha

**Comment by tyranja** [comment]
Hey @sadiksha, yeah, sure, thanks! \o/ 

Just out of curiosity, where did you learn about that project?

**Comment by sadiksha** [comment]
Hi @tyranja, I was a rails girls summer of code for this summer, and there was an announcement on the slack channel about #hacktoberfest. :D I looked at some projects and your project description looked cool. :)

**Comment by tyranja** [comment]
https://hashrocket.com/blog/posts/how-to-upgrade-to-rails-5

**Comment by sadiksha** [comment]
Hi @tyranja ,
I am running the tests first before i start making any changes. I had one test failing though. 

ProfilesController search action should store aggregations in aggs variable

Can you please let me know if this error exists or is it only in my system? Thank you.

**Comment by tyranja** [comment]
Hey @sadiksha, 
hm, locally the test are green on my machine and on travis-ci https://travis-ci.org/rubymonsters/speakerinnen_liste/builds/254570518.

I also started with updating the rails versionas you can see above in the link "update all gems", but you are welcome to work on that since I am busy with other tickets :)

**Comment by zaziemo** [comment]
@sadiksha probably this has something to do with elasticsearch? You have to run elasticsearch during the test runs.

**Comment by zaziemo** [comment]
Fetching: did_you_mean-1.2.0.gem (100%)
ERROR:  Error installing did_you_mean:
	There are no versions of did_you_mean (= 1.2.0) compatible with your Ruby & RubyGems
	did_you_mean requires Ruby version >= 2.5.0dev. The current ruby version is 2.3.0.

**Comment by zaziemo** [comment]
if all gems are updated try 

```rake acts_as_taggable_on_engine:install:migrations````
```rake db:migrate```

**Comment by zaziemo** [comment]
- [ ] https://github.com/thoughtbot/factory_bot_rails

**Comment by zaziemo** [comment]
https://medium.com/@vonchristian/upgrading-a-rails-4-2-6-app-to-rails-5-0-0-deef42f8d741

**Comment by tyranja** [comment]
assigns and assert_template, have been deprecated:

https://everydayrails.com/2016/08/29/replace-rspec-controller-tests.html

**Comment by tyranja** [comment]
deployed to staging and tested:

- [x] search works
- [x] login works
- [x] edit profile and medialinks in both en and de works
- [] create account via twitter
- [] create a new account

**Comment by sabrina-ulbrich** [comment]
create account via twitter gives the foolwing answer:
![screen shot 2018-04-30 at 20 56 22](https://user-images.githubusercontent.com/372649/39444851-5b744b18-4cb9-11e8-9da2-4901f47f4a0a.png)

**Comment by sabrina-ulbrich** [comment]
@zaziemo I guess I fixed it, but I don' t want to push some code (not sure if I break something). It's just one line: in models/profile.rb line 57: instead of
`new(session['devise.user_attributes'],` without_protection: true) do |profile|`
write
`new(session['devise.user_attributes']) do |profile|`
After that I get the message "A message with a confirmation link has been sent to your email address. Please open the link to activate your account."
The 'without_protection' option is no longer implemented (not even in Rails 4). Seen here:
[https://stackoverflow.com/questions/17105112/argumenterror-in-deviseregistrationscontrollernew-wrong-number-of-arguments](url)

**Comment by zaziemo** [comment]
@sabrina-ulbrich you should push that code :) We have tests to check whether anything breaks! Are you coming tonight?

**Comment by sabrina-ulbrich** [comment]
@zaziemo I'll come and we can look at it together. I tried to push with 'git push origin zaziemo-upgrade-to-rails-5' but I got the answer 'Everything up-to-date' and nothing changed.

**Comment by zaziemo** [comment]
\o/
