### ISSUE TITLE
tags for different languages

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#471]
At the moment all the different tags ( german and english ) are in one table without the possibility to filter them by language.

When you go to the page and see the tag_cloud you have german tags as well as english tags which is pretty confusing and gets worse when we add other languages.

![tag_cloud](https://cloud.githubusercontent.com/assets/1218914/17708175/20677136-63e4-11e6-9a69-1d459e9a512d.png)

The aim is that the user adds tags in the languages they speak to their profile. In the tag_cloud you can see only the tag with the correct language.

**Comment by tyranja** [comment]
One Idea is not to translate the tags because strictly speaking that is not what we want. But to add another table called tag_language and make connections there with the tag_id and language.

eg:
tag_language:

**tag_id     |     language_locale**
23           |     en
23           |     de
66        |     en
12       |     en

**Comment by geisasantos** [comment]
@tyranja when we can schedule a call to talk about this issue and others and about our next contribuitions for Speakerinnen?

**Comment by zaziemo** [comment]
next steps: gather possible concepts to implement that, discuss and evaluate --> then decide

**Comment by zaziemo** [comment]
our solution should meet the following requirements:
* tag cloud should be filtered according to current locale
* search results should show topics according to current locale
* during profile edit speaker should get suggestions for tags in their languages (not only dependent from locale but language the profile is edited)
* all existing tags (5,500) must be adapted to the new system
* admin process should stay efficient --> adding tags to categories

**Comment by zaziemo** [comment]
we identified 2 options - tbd
https://gist.github.com/zaziemo/72d8042d7f1a2144a3c4029433245240

**Comment by zaziemo** [comment]
add user stories to make clearer what we want
