### ISSUE TITLE
Add a button in the profile view to get to the next profile view

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#472]
It would be nice to have a arrow to move to the next profile under the 'all profiles views' link

![show_view](https://cloud.githubusercontent.com/assets/1218914/17863421/dd5698da-6899-11e6-9699-44a390ee3dc7.png)

**Comment by colleenmcguckin** [comment]
I'll give this a try!

**Comment by geisasantos** [comment]
Great! Thanks, @tyranja !

**Comment by k1r8r0wn** [comment]
Hello, added in #479

**Comment by tyranja** [comment]
Thanks @k1r8r0wn! We will have a look at it as soon as we find some time! :+1: :tada:

**Comment by k1r8r0wn** [comment]
Glad to help!

**Comment by tyranja** [comment]
I will close that for now. Its to difficult to achieve that because there are different scopes and the implementation now does not takes the search scopes into consideration.

Thanks a lot for the work in that!! I am sorry that we cannot deploy that right now.

**Comment by k1r8r0wn** [comment]
No prob. 👍
