### ISSUE TITLE
Check gems

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#476]
Right now, we have a lot of gems. 
We should look through the list and check if we need all of them.

Gems to be removed?
`guard`

**Comment by geisasantos** [comment]
I want to help with this. Me and @n3k00n3 already checked some gems during the RGSoC.

**Comment by tyranja** [comment]
Cool, so maybe you can add some removing suggestions :)

**Comment by zaziemo** [comment]
also related to #210
