### ISSUE TITLE
changes of account information: some things are wrong

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#484]
1) extra confirmation email should be created - right now resource.unconfirmed_email is used (which is the regular email for first time confirmation

2) if you only want to change the email address, you shouldn't be forced to enter password

**Comment by tyranja** [comment]
Started working in this and it seems to work. I just need to add tests.

https://github.com/rubymonsters/speakerinnen_liste/tree/ty_add_a_reconfirmation_email

Following that blogpost: https://cbabhusal.wordpress.com/2015/09/26/rails-devise-send-different-emails-for-confirmation-and-reconfirmation/

**Comment by tyranja** [comment]
https://github.com/rubymonsters/speakerinnen_liste/pull/487

**Comment by tyranja** [comment]
Done
