### ISSUE TITLE
Heroku application error, site down

### ISSUE THREAD

**Issue by jancborchardt** [rubymonsters/speakerinnen_liste#489]
First I wanted to report the speaker pictures not being visible with an apparent connection timeout from Amazon AWS:
```
https://speakerinnen.s3.amazonaws.com/uploads/profile/picture/2146/profile_…Signature=4b9c932ca3c326c8b6aabee9a1b60c606b690bab6fb54512a88b7e04ee8e9802
Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
```

But now the whole app is down with a Heroku application error. :\

**Comment by zaziemo** [comment]
thx for letting us know.

**Comment by zaziemo** [comment]
apparently everything is working again now :)

**Comment by jancborchardt** [comment]
Yep, cool! :)
