### ISSUE TITLE
translation of postcard text german --> english

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#499]
Could anyone translate this short german text into english?
https://gist.github.com/zaziemo/1d5bb7b99473d85a220a3d23f6077f4f

Some of the expressions are already translated on our website. <3

**Comment by cmn819** [comment]
_German is my second language but this may help at least! :)_

More women on the stage! 
There is no excuse to have any panels without women. 

This list of speakers wants to increase the visibility of women at conferences, talkshows, panels and anywhere else where there is public speaking. Lecturers and speakers from many varied disciplines are registered here.

On speakerinnen.org you can:
Create a meaningful profile as an Expert with your topics and references.
Event organizers can find the right speaker for their next event.

Create a profile now!
speakerinnen.org/sign-up

Find your next speaker!
speakerinnen.org

Follow us on Twitter!
@speakerinnen

Follow us on Facebook!
facebook.com/speakerinnen/
