### ISSUE TITLE
How to get conference organizers to use our app

### ISSUE THREAD

**Issue by thatbettina** [rubymonsters/speakerinnen_liste#50]
So here's a summary of what Jan, the organizer of JSConf, told me:
1. He asked me if this was a real product, where we'd charge organizers say 30 euros per conference to use. 

I know that this is not our goal, but I found it really encouraging that he thought SpeakerInnen_Liste could be a viable product. 
1. He said that it's a LOT more work to do outreach to get more diverse speakers. 

His workflow for recruiting speakers is
1. make a spreadsheet of everyone he knows personally who might be good. For JSConf, he'd estimate that it was about 35 speakers from his social networks, which are Twitter and Github (not LinkedIn or Xing or Facebook).
2. email to ask them to speak, trying to get them sold on the event itself as the perk or else that the reach / community aspect of being a speaker is worthwhile
3. half of them did not answer, the other half emails back with one of three questions:
   - "I don't know what to talk about"
   - "I've never given a talk"
   - lack of mechanics--don't know how to use slides, etc. 
4. email personally every single one of them, pointing them to template slide decks, local user groups where they can practice speaking, and working with them on finding topics. 

This takes a lot of time. It's like being a speaker coach to 15 people. 

They tried to make this simpler by having the website weareallaweso.me

Despite keeping all the resources on that website, he still has to track 
- to whom he's spoken/emailed 
- what he needs to email them or if he's waiting to hear back from them 
- the entire funnel, taking them through the process to get them to submit a proposal

I asked him if he thought that pairing people up would help but the speakers really need to be paired with someone with experience. One of his ideas was to contact the speakers 'alumni' to ask them to help coach new speakers. 

Lastly, Jan mentioned Lanyrd as a model to consider, as its a community resource where people can help, review slides, etc. I didn't really see the community aspect of it, but it seems like what Lanyrd does is create a profile for every speaker at all the conferences they cover: http://lanyrd.com/profile/opheliabenson/
They aggregate media of past talks as well as list when/where speakers are talking next. I secretly love this, because they've already created your profile for you! But it's also a bit scary how stalker-ready this is.

Jan's specific requests for us were
1. work on the design
- It would be easy to tap a box next to a speaker to email them about the event, where the speaker could respond by with yes, no, maybe, follow up with some questions.
1. filter function--other databases are hard to explore because they just list people alphabetically, which has NO real impact on whether you'll email them or not. He wants a "Yelp experience"--where you press one button to find crowdsourced results for, as an example, a Ruby conference in Israel and they are all available for your events' time. 

He does not want to fill out a database form, because organizers have no time and please don't make them think.
- For budget-conscious organizers they need to find speakers around them, so we should add location information.
- He mentioned that it would be great if we can see what time they're available, but I think this is more complicated and a little too much information (like surveillance/stalker style).
1. to curate the speakers, so it's not just anyone who can sign up but at the same time to not discourage anyone with a test they have to pass. 
- my personal thought was to sort the speakers according to how close they are to the organizers' twitter network.
- for the strangers, recordings of previous talks or slidedecks are important, esp. so that organizers can hear for themselves how well speakers can speak in their non-native languages. 
- Jan mentioned that he would like to share with other organizers how easy speakers were to work with, but I didn't think this information belonged on a public website. Attendees review speakers on Joind.In : http://joind.in/talk
  But when I went to the website, talks and events were rated. I didn't see where you could search for speakers. 
1. Identify which languages are our speakers' natural native languages, since organizers want to make sure that they are good enough to be understood in their second / third languages.
2. make it easy for organizers!

There is a need for this. 30-40 events have stolen their cfp from github: https://github.com/jsconf/2012.jsconf.eu
But most conference organizers don't get the idea yet of working on diversity.

He personally saw the benefits of getting 15-20% women speakers at his event being:
- it's not odd anymore to be a woman there
- no more 'frat boy'-feel to the conference -- it's more grownup
- better talks

And he's totally open to skyping with us about this.

**Comment by zaziemo** [comment]
--> move to wiki
