### ISSUE TITLE
Remove the postmark addon and make own rails mailer

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#504]
for confirmation and contact mails: https://t.co/P7CNfzntDg

**Comment by tyranja** [comment]
The cases where we use postmark

- [ ] account confirmation to speakerin ( confirmation_mailer.rb )
- [ ] mail to admin that a new profile was created ( admin_mailer.rb )
- [ ] publish notification from admin to speakerin ( admin_mailer.rb )
- [ ] contact from a org to a speakerin ( notification_mailer.rb )
- [ ] contact to us ( notification_mailer.rb )

**Comment by tyranja** [comment]
We need to add a new field for the profile to get their locale and to send to correct email translations to them: https://niallburkley.com/blog/localize-rails-emails/

```
class AddLocaleToProfiles < ActiveRecord::Migration
  def change
    add_column :profiles, :locale, :string, null: false, default: :en
  end
end
```

**Comment by tyranja** [comment]
```
before_action :set_locale
 
def set_locale
  locale = I18n.locale
end
 ```

**Comment by tyranja** [comment]
- keep the multilanugaes email
- adjust is, so the english is first (https://github.com/rubymonsters/speakerinnen_liste/blob/master/app/views/admin_mailer/profile_published.html.erb)

**Comment by zaziemo** [comment]
works!
