### ISSUE TITLE
decide which fields should be translated

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#513]
what about country/city that often have different names and/or spellings in different languages

**Comment by alicetragedy** [comment]
+1 on this — I often get asked about lists for speakers in Vienna, and searching for “Wien” with the extended search or for “Vienna” you get different results ... It would be great to aggregate this so that you find the same speakers no matter which language the city you input is in.

**Comment by tyranja** [comment]
Not translated:

**Comment by tyranja** [comment]
Add [globalize](https://github.com/globalize/globalize) for the following fields twitter, city, website and references
For example here: https://github.com/rubymonsters/speakerinnen_liste/blob/master/app/views/shared/_profile_formfields.html.erb#L69

**Comment by zaziemo** [comment]
-> short question? what do you mean by media_url, @tyranja. Isn't that the field for the picture URL? Do you mean the medialinks?

**Comment by tyranja** [comment]
yes, medialink :roll_eyes: all the names!!
