### ISSUE TITLE
re-build search view for faceted search 

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#515]
see these mockups: https://github.com/rubymonsters/speakerinnen_liste/issues/494#issuecomment-293511439

~and this PR: https://github.com/rubymonsters/speakerinnen_liste/pull/512~

**Comment by zaziemo** [comment]
I will work on the part to make the aggregations (facets) accessible in the view so you can work on the layout @tyranja.

**Comment by tyranja** [comment]
https://github.com/rubymonsters/speakerinnen_liste/pull/516
