### ISSUE TITLE
Bug: not all profiles have default-routes with slug

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#518]
Currently there are certain profiles that have a default permalink with their ID (original Rails Routing), e.g. https://speakerinnen.org/de/profiles/25. This is the route used in the search result.

The permalinks with slugs https://speakerinnen.org/de/profiles/firstname-lastname should be referenced by default and the routing with ID should be possible as well.

Check why this happens and fix.

**Comment by tyranja** [comment]
Might have sth to do with this: https://github.com/rubymonsters/speakerinnen_liste/issues/531

**Comment by zaziemo** [comment]
is working now - one profile that has no slug has empty name fields
