### ISSUE TITLE
Upload smaller pics for the following accounts:

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#531]
```
invalid = Profile.all.reject(&:valid?).map(&:id)
=> 
[364, 62, 258, 513, 929, 334, 609, 204, 210, 103, 101, 107, 617, 389, 160, 185, 127, 123, 92, 180, 173, 205, 250, 573, 232, 238, 289, 293, 172, 638, 519, 320, 275, 517, 323, 417, 367, 461, 405, 381, 384, 465, 430, 443, 454, 456, 471, 489, 546, 531, 655, 395, 699, 427, 692, 25, 728, 789, 798, 803, 842, 841, 821, 976, 892, 290, 923, 455, 304, 228, 356, 769]
Profile.where(id: invalid).each(&:valid?).map{|p| p.errors.full_messages}.uniq
=> [["Ein Foto von mir: ( wenn möglich in Farbe, wir zeigen es in Graustufen.)  ist zu groß. Bitte nicht größer als 1 MB"]]

```

**Comment by zaziemo** [comment]
1) log in as an admin
2) select the profile by changing the last part of the URL into the corresponding ID (see list of IDs above): https://speakerinnen.org/de/admin/profiles/364
3) download the picture and store it locally
4) go to "edit profile"
5) click "delete my photo" and click "update your profile"
6) upload the locally stored picture
7) if the field: "The country, I live in:" is empty, select the country of the person (based on the information given in the in the "city" field
8) click "update your profile"
\0/

**Comment by zaziemo** [comment]
if pictures can't be removed via the admin interface we can remove them via heroku console:
`profile =  Profile.find(<ID>)
profile.remove_picture!
profile.save`
