### ISSUE TITLE
Facetted search should show cities in correct / original spelling

### ISSUE THREAD

**Issue by BriocheBerlin** [rubymonsters/speakerinnen_liste#543]
Currently the facetted search doesn't show the original city name but the analysed form, which is not nice:
![screen shot 2017-05-17 at 15 54 06](https://cloud.githubusercontent.com/assets/6567555/26157281/18df7276-3b19-11e7-9d96-fd052b91a801.png)
We want `Köln` to show as such.

**Comment by zaziemo** [comment]
done, thanks @BriocheBerlin!
