### ISSUE TITLE
Create Elasticsearch alias

### ISSUE THREAD

**Issue by BriocheBerlin** [rubymonsters/speakerinnen_liste#544]
For easy maintenance, create ES alias to later on allow reindexing on production without downtime.
See https://www.elastic.co/guide/en/elasticsearch/guide/current/index-aliases.html

**Comment by BriocheBerlin** [comment]
Since aliases are independent form indices they can be created any time.
For a how to see: https://www.elastic.co/guide/en/elasticsearch/reference/2.4/indices-aliases.html

**Comment by zaziemo** [comment]
tried to do this but didn't work
![bildschirmfoto 2017-05-22 um 18 29 25](https://cloud.githubusercontent.com/assets/2119496/26318808/b31da6ee-3f1c-11e7-8a34-94dd6bb3cc4b.png)
