### ISSUE TITLE
edit medialinks: unwanted symbols 

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#549]
currently there are ...** shown in front of the form titles. 

Pleas check: why is that?
<img width="485" alt="bildschirmfoto 2017-05-19 um 11 50 05" src="https://cloud.githubusercontent.com/assets/2119496/26242662/828a47e8-3c89-11e7-8a69-d205b473e9ef.png">

**Comment by tyranja** [comment]
https://github.com/rubymonsters/speakerinnen_liste/pull/562
