### ISSUE TITLE
check: warning in heroku - memory quota exceeded :(

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#566]
https://devcenter.heroku.com/articles/ruby-memory-use

**Comment by zaziemo** [comment]
check this out: https://github.com/MiniProfiler/rack-mini-profiler

also this: https://github.com/schneems/derailed_benchmarks#dynamic-app-benchmarking

**Comment by zaziemo** [comment]
- [ ] remove non-used gems
- [ ] check gems that use much memory, e.g. carrierwave
- [ ] check which processes need much memory via https://github.com/MiniProfiler/rack-mini-profiler and refactor code
- [ ] optimize memory usage on server: https://devcenter.heroku.com/articles/optimizing-dyno-usage#basic-methodology-for-optimizing-memory

**Comment by zaziemo** [comment]
after the first days the error never occured again - probably we don't have to investigate further.

**Comment by zaziemo** [comment]
also check: https://www.sitepoint.com/silver-bullet-n1-problem/

**Comment by tyranja** [comment]
https://honeybadger.leadpages.co/exceptions/
https://schneems.com/2017/05/17/ruby-backend-performance-getting-started-guide/
https://evilmartians.com/chronicles/fighting-the-hydra-of-n-plus-one-queries

**Comment by zaziemo** [comment]
seems to need refactoring: main_topic_or_first_topic --> make it possible to eager load translations for main_topic

**Comment by zaziemo** [comment]
🌪☄️ cool!

**Comment by tyranja** [comment]
Seems to work. Close this for now.
