### ISSUE TITLE
internationalize tags: check possibilities of acts-as-taggable 

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#570]
is it possible to customize acts-as-taggable and use further columns, e.g. tag_language?
related to #471

**Comment by zaziemo** [comment]
1. we could use acts-as-taggable in combination with globalize: http://danielpuglisi.com/articles/2013/09/setup-acts_as_taggable_on-with-globalize3
2. we could also check out tag_types to assign languages to tags

**Comment by tyranja** [comment]
to the second solution: https://hamzakc.wordpress.com/2006/06/28/acts_as_taggable-with-different-language-tags/

**Comment by zaziemo** [comment]
Visualisation of @tyranja's idea
![db_overview_170726_idee 001](https://user-images.githubusercontent.com/2119496/28674006-6ab97e18-72e4-11e7-968e-2018546b3257.jpeg)

**Comment by zaziemo** [comment]
![db_overview_170726_idee 001](https://user-images.githubusercontent.com/2119496/28716941-0ce7b0d6-73a0-11e7-84a3-0a22416797b0.jpeg)
