### ISSUE TITLE
profile index: remove text if there are no results for aggregations

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#575]
if there are no results for aggregations (e.g. if you have only one result and the speaker has not entered city/country or language) 
or only one result

we don't want to have the headlines for the aggregations and the text block "here you can filter the results"

**Comment by agustinariq** [comment]
Hello! Can I work on this issue?

**Comment by zaziemo** [comment]
@agustinariq yes sure! That would be great :)
