### ISSUE TITLE
New or adjusted logo

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#577]
Our logo right now is difficult to recognize when it is smaller. The text does not scale.

![logo_header](https://user-images.githubusercontent.com/1218914/27476281-697af4f6-5808-11e7-8702-03642e3fff82.jpg)

It would be nice to adjust our logo maybe with a pic like that:
![f0e61873c7a7389bbd0f7183ef1c3f18](https://user-images.githubusercontent.com/1218914/27476250-4b2b363c-5808-11e7-9c35-65d5087a03f7.jpg)

Also it would be nice to have sticker!!!

**Comment by bioshrimp** [comment]
or you could keep the old version but change it up a little. for example the speakerinnen logo for mobile could just contain the initials  "SL" so everything could be bigger. or change it all together of course with a illu you posted.
