### ISSUE TITLE
after adding new fields to globalize: how to migrate existing data?

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#586]
as described in #513 we want to translate more fields.

How do we treat the content that is already there?

idea: 
* if person only speaks one language we transfer all content to _en or _de
* if person speaks more languages, we copy it in both contexts and write an email to all the people to revise their profile

**Comment by tyranja** [comment]
I would say it depends what field we are translating:

city -both
twitter - both 
website -both
tags
media URL

**Comment by zaziemo** [comment]
obviously it is not possible to migrate existing field content to both translated field. Migration uses only default locale and then uses fallback.

**Comment by zaziemo** [comment]
we have to write a migration to copy the content of <field>_de into <field>_en
