### ISSUE TITLE
remove translated columns in profiles table

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#610]
- [x] twitter
- [x] website
- [x] city

**Comment by zaziemo** [comment]
also remove tag_languages table

**Comment by tyranja** [comment]
- [ ] remove the model `TagLanguage`

**Comment by tyranja** [comment]
Looking at the database the column `city` and `website` are still populated.

- [ ] create a dump from the production database

- [ ] merge  the PR
- [ ] deploy on staging
- [ ] run the migration on staging
- [ ] check the staging website
do the same with production 
- [ ]

**Comment by tyranja** [comment]
Thank you @zaziemo!
