### ISSUE TITLE
tbd: make it possible to enter more than one country

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#621]
user feedback: "Da ich in zwei Ländern (D/CH) lebe, wollte ich beide auf meinem Profil eintragen"

--> it would be possible to choose multiple countries and would be consistent with the possibility to enter different cities as well. But would the form get to complex with another form field with checkboxes? Probably check multi select drop down

**Comment by tyranja** [comment]
we will close this for now.
