### ISSUE TITLE
Actual database schema

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#644]
![db_overview_170918 001](https://user-images.githubusercontent.com/2119496/30583466-6f72ba42-9d27-11e7-8689-cbbddfd9b3ee.jpeg)

**Comment by tyranja** [comment]
old database scheme: https://github.com/rubymonsters/speakerinnen_liste/issues/613

**Comment by tyranja** [comment]
@zaziemo update database please

**Comment by tyranja** [comment]
We don't have twitter, city, website in the Profiles tables any more.

What about talks or media_url?

**Comment by tyranja** [comment]
And `languages` seems to be `iso_languages` nowadays.

**Comment by zaziemo** [comment]
Yes, that is true. I think we wanted to keep those fields a little while because we did many migrations and were not sure whether everything works out properly. But now 1 year has passed and nobody complained ;) Can be deleted!

**Comment by sabrina-ulbrich** [comment]
city, twitter, website, main_topic, bio and languages are no longer in the profile table, look at pull request #733

**Comment by tyranja** [comment]
Maybe we can use this to create an actual db schema: https://github.com/voormedia/rails-erd

**Comment by tyranja** [comment]
![erd](https://user-images.githubusercontent.com/1218914/43900439-368fa600-9be5-11e8-8f9c-d209784de1ef.jpg)

**Comment by zaziemo** [comment]
@tyranja do we want to stick to that gem? It think some tables are missing there. Or should I update the PPT-Doc?
