### ISSUE TITLE
deleting website in form as admin

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#651]
if I delete the website of that profile as an admin https://speakerinnen.org/de/profiles/janna-aljets it disapears in profile edit but is still visible in profile show.

please check

**Comment by zaziemo** [comment]
has possibly to do with permissions to delete globalize translations: https://github.com/globalize/globalize/issues/635

**Comment by tyranja** [comment]
@zaziemo I tried to reproduce but it seems to be working ...

**Comment by zaziemo** [comment]
@tyranja 👍
