### ISSUE TITLE
admin profiles index: adapt counting

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#660]
/admin/profiles has a counting that says "2173 Speakerinnen. 1960 public." This gives the admins an orientation about still unpublished profiles that has to be done after manually checking which is at the moment 213. You can see those published and unpublished profiles by sorting the table below in the "visibility" column.

The overall sum (2173) includes profiles that are not yet confirmed by the users. Those unconfirmed profiles are however NOT listed in the table below. This is sometimes misleading for the admins who expect that the sum of the published and unpublished profiles in the table correspond to the sum of the overall profiles in the counting.  

--> Therefore: please adapt the overall counting to include only confirmed profiles and adapt the text to "2173 confirmed Speakerinnen. 1960 public" (with the german translation accordingly).

**Comment by Vikingnut** [comment]
Hi @zaziemo , I am a ruby on rails beginner and would like to take a stab at this. Do I have permission to do so?

**Comment by zaziemo** [comment]
Hey @Vikingnut cool :) and yes, you could do so. You can find all the setup information in the README.

**Comment by Vikingnut** [comment]
Thank you! I will get started at some point today

**Comment by tyranja** [comment]
Thank you @Vikingnut for the effort! Will close this now.
