### ISSUE TITLE
Accessibility: reCaptcha

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#663]
Hey @speakerinnen, did you know that it's hard to register on your site for people with seeing disability (#reCAPTCHA is the problem)? How may my friend and potential speakerin get into alternative contact with you? Thanks for your support!

**Comment by zaziemo** [comment]
I talked with the friend: 

- apparently the click event does not work - error message:  "Recaptcha kann nicht erreicht werden, überprüfen sie die Verbindung"
- she uses the screenreader Jaws
- she had problems with recaptcha on several sites recently
- suggestion what works good for her: calculation 

We have to have a look at that again. For troubleshooting I registered her with her email address.

**Comment by zaziemo** [comment]
https://groups.google.com/forum/#!forum/recaptcha

**Comment by tyranja** [comment]
we have remove recaptcha so I am closing this issue.
