### ISSUE TITLE
Using docker for tests?

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#668]
here is a nice blogpost about how to use docker and guard. Since installing elasticsearch is time consuming, may running the tests with docker makes more sense.

@1000miles you already had some thoughts about it ...

 https://www.chrisblunt.com/ruby-on-rails-running-tests-with-guard-and-docker/?utm_source=rubyweekly&utm_medium=email

**Comment by 1000miles** [comment]
Hi @tyranja @zaziemo,

yes, I am totally up for using docker but how about using docker not only for tests? If yes, I was thinking about also providing set up info for docker and vagrant setup in the `README.md`.

What do you think?
