### ISSUE TITLE
add specs for typeahead method

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#670]
In the search field we make suggestions to the user while she types in search phrases.
<img width="909" alt="bildschirmfoto 2018-02-23 um 15 55 59" src="https://user-images.githubusercontent.com/2119496/36600255-153da06c-18b2-11e8-8449-3e5373fd3467.png">

Last week we detected a bug, that the suggestions don't work anymore. I wrote a fast fix for this but didn't do it test-driven. Now it would be great if we had a spec that covers the functionality of the typeahead method in the profiles_contoller 
https://github.com/rubymonsters/speakerinnen_liste/blob/c7dce810e62cd7b2a792ddacb1769442bdd45f63/app/controllers/profiles_controller.rb#L79 

We already cover the necessity of certain classes to actually display the suggestions. But what we don't cover in our specs are the results of this method. In the case of the recent bug the suggestion object changed (because of the update of the acts-as-taggable gem?) and the method didn't deliver any output anymore.

Please add specs for this case and for potential others where the method execution could fail.

**Comment by Arvisix** [comment]
Will be happy to help with this issue

**Comment by zaziemo** [comment]
@Arvisix cool, thank you :) Here are some hints to setup the project: https://github.com/rubymonsters/speakerinnen_liste/blob/master/CONTRIBUTING.md
If you have any questions feel free to ask.

**Comment by netagonen** [comment]
@Arvisix : are you working on this issue at the moment?
