### ISSUE TITLE
[Security] Add a security info page

### ISSUE THREAD

**Issue by 1000miles** [rubymonsters/speakerinnen_liste#677]
# Context

When users create a profile on speakerinnen.org they can provide their full name, email address, additional info and links to their other channels, contact options, etc. to present themselves on the internet. 

While this is a great way to increase your online reputation and reach out to potential requesters it also makes you vulnerable to harassment and abuse. 

Even though we understand that every user on speakerinnen.org is fully responsible for their own content and any communication between them and their requesters we care about this topic and would love to provide a page where we can list some security tips for our users.

# Scope

- provide a link to a separate security page in the footer that contains:
  - security tips
  - incident examples, if any (anonymized)
  - who to contact when affected

**Comment by tyranja** [comment]
I like that a lot!!!

**Comment by n3k00n3** [comment]
- who to contact when affected
Can you explain it more? I think that can vary from country to country.
