### ISSUE TITLE
Setup speakerinnen with docker

### ISSUE THREAD

**Issue by 1000miles** [rubymonsters/speakerinnen_liste#680]
This is a follow up and replacement ticket for https://github.com/rubymonsters/speakerinnen_liste/issues/671.

# Scope

- [x] Initialize docker 
- [x] Install essential and additional packages
  - [x] git curl vim wget
  - [x] python-software-properties build-essential 
  - [x] ruby ruby-dev
  - [x] nodejs & npm
  - [x] Postgres
  - [x] bundler
  - [ ] imagemagick libmagick++-dev libxml2-dev 
  - [ ] openjdk:8-jre (needed for ES 2.4)
  - [ ] Elasticearch 2.4.5
- [ ] Set locale
- [ ] Set docker entry point (/docker-entrypoint-initdb.d)
- [ ] Change database.yml according to postgres configs with docker
- [ ] Document docker setup

**Comment by 1000miles** [comment]
Referencing #668

**Comment by tyranja** [comment]
I just found that talk: RailsConf 2018: Containerizing Rails: Techniques, Pitfalls, & Best Practices by Daniel Azuma: https://www.youtube.com/watch?v=kG2vxYn547E 

Maybe that can be helpful.

**Comment by zaziemo** [comment]
@1000miles --> @Powerglove wants to support the project. She wants to work on that issue.

**Comment by 1000miles** [comment]
@zaziemo @Powerglove 

Hi there, sounds great! Thanks. 

Oh, you are right, I noticed that I never pushed it. Sorry about that. I guess it's kind of outdated and a bit a mess so I will push the branch as it as without fixes. Is it okay?

**Comment by 1000miles** [comment]
I still have some files in that branch that are yet uncommitted. Not sure if I should also commit and push them. Some of them were generated by Docker if I remember correctly? What should we do?

![Screenshot 2019-08-20 at 00 31 17](https://user-images.githubusercontent.com/4077916/63304100-2aebba80-c2e2-11e9-9e4e-892d9946f578.jpg)

**Comment by Powerglove** [comment]
Hi @1000miles , I think it is fine if you push the files (the yml file and the html). Are the two folders empty? then I guess we won't need them. 
Have you documented somewhere where exactly you got stuck with solving this issue?

**Comment by 1000miles** [comment]
@Powerglove No the `speakerinnen_data` and `docker` folders are not empty and I believe at least `speakerinnen_data` was generated that can be omitted, too. 

Thanks, I'll try to look into it over the weekend and push it if it's enough time for you?

**Comment by 1000miles** [comment]
@Powerglove , sorry, I forgot to reply to your question `Have you documented somewhere where exactly you got stuck with solving this issue?`. Unfortunately it's not documented but I remember vaguely that I couldn't fully build all containers. 

I hope you can work with it for now.

**Comment by Powerglove** [comment]
Tackled by #971
