### ISSUE TITLE
no result for a listed tag

### ISSUE THREAD

**Issue by sabrina-ulbrich** [rubymonsters/speakerinnen_liste#682]
Clicking on the tag new work + arbeiten 4.0 gives no results:

![screen shot 2018-05-10 at 18 03 43](https://user-images.githubusercontent.com/372649/39880180-41250308-547d-11e8-9533-3a6479205304.png)

**Comment by zaziemo** [comment]
🤨 that's true. I have the impression that is a problem with the escaping of + and . in the URL parameters. Same with this tweet: https://twitter.com/timpritlove/status/992347926230859776
