### ISSUE TITLE
AWS migration

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#690]
- [x] create own AWS account (hosted in Europe)
- [x] move existing Data to new account

**Comment by tyranja** [comment]
Hey @zaziemo I am afraid we have to do that together. I am not sure what to write into the form :(

**Comment by sabrina-ulbrich** [comment]
If data from carrierwave is involved, we maybe can do the migration of the data together with a change to active storage (because we don't need another rake task to migrate pictures from carrierwave to active storage). @zaziemo @tyranja

**Comment by zaziemo** [comment]
write ruby script to copy and paste from one bucket to another, research "copy bucket aws" perhaps there is a professional tool for it.

**Comment by tyranja** [comment]
https://aws.amazon.com/de/premiumsupport/knowledge-center/copy-s3-objects-account/ 

right now I am trying to list the content of the bucket with our speakerinnen credential but it won't work. :woman_shrugging:

**Comment by zaziemo** [comment]
@tyranja do you need help with that issue or is it already done?

**Comment by sabrina-ulbrich** [comment]
It seems to be a description how to migrate the data from carrierwave to active storage:
https://www.stefanwienert.de/blog/2018/11/05/activestorage-migrating-from-carrierwave-attachment-pointers/
