### ISSUE TITLE
Heroku: Upgrade to the latest stack

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#693]
We got this warning:

Warning: You are running on a deprecated stack.
remote:  !   Please upgrade to the latest stack by following the instructions on:
remote:  !   https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack

**Comment by tyranja** [comment]
Started with staging: https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack#upgrading-an-app

**Comment by tyranja** [comment]
Done and deployed to staging and production.
