### ISSUE TITLE
forced https

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#699]
Message via twitter:

Hallo @speakerinnen! Eure Seite macht noch kein forced https, alles, was mit http verlinkt ist, wird noch mit http aufgerufen. Auch die Registrierung. Pls fix!

@tyranja could you have a look at this?

**Comment by ur5** [comment]
I think `config.force_ssl` in the production environment could do the job for you. See: https://stackoverflow.com/questions/15676596/what-does-force-ssl-do-in-rails

**Comment by zaziemo** [comment]
another hint from Robert via email:
add the following in .htaccess
#redirect all to https
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
</IfModule>

```#hardenings based on https://securityheaders.io - enables HSTS + other goodies
<IfModule mod_headers.c>
Header always set X-Frame-Options "SAMEORIGIN"
Header always set X-Xss-Protection "1; mode=block"
Header always set X-Content-Type-Options "nosniff"
Header always set Strict-Transport-Security "max-age=31536000; includeSubdomains; preload"
Header set Referrer-Policy: no-referrer-when-downgrade
</IfModule>```

**Comment by tyranja** [comment]
Also wanted to link `www.speakerinnen.org` to `speakerinnen.org` .so we have only one valid domain.

**Comment by tyranja** [comment]
Done and deployed. Thanks @ur5 !!!
