### ISSUE TITLE
link www.speakerinnen.org to speakerinnen.org

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#701]
who owns our DNS entry? 

We need to change the settings in DNSimple: https://support.dnsimple.com/articles/redirect/

**Comment by sabrina-ulbrich** [comment]
> On 1. Jun 2018, at 17:46, Tyranja <notifications@github.com> wrote:
> 
> who owns our DNS entry?
> 

I guess Konstantin did this. You can check that in the travis dns simple account.

**Comment by zaziemo** [comment]
I think this is already done? right?
