### ISSUE TITLE
Use rails new feature Active Storage

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#703]
With the update to rails 5.2 we could use the build in feature Active Storage.

https://blog.heroku.com/rails-active-storage
http://edgeguides.rubyonrails.org/active_storage_overview.html

https://evilmartians.com/chronicles/rails-5-2-active-storage-and-beyond

https://www.engineyard.com/blog/active-storage

**Comment by tyranja** [comment]
https://www.randygirard.com/migrating-from-carrierwave-to-activestorage-in-rails/

**Comment by sabrina-ulbrich** [comment]
It's done
