### ISSUE TITLE
Add correct prompt text in password field.

### ISSUE THREAD

**Issue by drashti4** [rubymonsters/speakerinnen_liste#709]
User might get confuse by just "At least 8 character" of what? It can be replace with "********" or "Enter 8 character password"
![spk 1](https://user-images.githubusercontent.com/9081004/41140348-8ee03040-6ab2-11e8-909f-936c7ccddd35.PNG)

**Comment by tyranja** [comment]
That is a good idea! It is really confusing, I like the second suggestion the best.

**Comment by drashti4** [comment]
Great. I'm modifying. Can you please assign this issue to me?

**Comment by tyranja** [comment]
It is online :smile: :tada:  

But now we have to make the text field a bit wider especially in German. German language! :roll_eyes: 

![password](https://user-images.githubusercontent.com/1218914/41163335-b22a78cc-6b38-11e8-8bc6-067af62ec81b.png)

![password_de](https://user-images.githubusercontent.com/1218914/41163699-abb732e0-6b39-11e8-8263-2410d9db6163.png)

**Comment by drashti4** [comment]
Yeah I had fear of that but couln't find any right prompt to fix it. What do you think? Should we change hint or make textfield larger?

**Comment by tyranja** [comment]
Sorry, did not see your answer. We should make the text field larger. :)

**Comment by tyranja** [comment]
I fixed the width of the field so the user can see the whole place holder text:
https://github.com/rubymonsters/speakerinnen_liste/commit/2108647bfcb53e7131b4076a0c5612d45dcd687b


![fixed](https://user-images.githubusercontent.com/1218914/41293424-85b8af28-6e55-11e8-904d-3f7855b2ae47.png)
![fixed_2](https://user-images.githubusercontent.com/1218914/41293427-85f6ec2a-6e55-11e8-8b4b-00f6a9c67d65.png)

**Comment by tyranja** [comment]
Thanks a lot for your work!!

I gonna close the ticket now.
