### ISSUE TITLE
Improve cookie text

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#714]
We need to make clear that without using cookies, the user cannot sign in or sign up.

Right now the text is:
```
 cookie_consent: "We take the protection of your personal data and its confidential treatment very seriously. We use cookies to optimize and to improve the services we offer you. By using this website, you agree to the use of cookies. Find more information about data security in our <a href='%{link}'>privacy policy</a>."
```

```
cookie_consent: "Wir nehmen den Datenschutz sehr ernst. Damit wir unsere Webseite optimal gestalten und verbessern können, verwenden wir Cookies. Durch die weitere Nutzung der Webseite stimmst Du der Verwendung von Cookies zu. Mehr Informationen in unserer <a href='%{link}'>Datenschutzerklärung</a>."
```

**Comment by zaziemo** [comment]
Hey @mandeepsidhu2,
Thanks for your suggestion! 
You can find the text here: https://github.com/rubymonsters/speakerinnen_liste/blob/master/config/locales/en.yml#L77

We'd need some more important information (sorry for not specifying the issue more). Could you probably change the first sentence in: "To provide the full functionality of this site (e.g. login and registration) we have to store information about how you use it."

The crucial fact is, that without agreeing to store cookies, you can't login or register.

**Comment by zaziemo** [comment]
Thanks for you help @mandeepsidhu2 !
