### ISSUE TITLE
Delete usused code

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#725]
We obviously don't user `media_url` and  `talks` any more so we should delete that from the Dtabase table and code.

See: https://github.com/rubymonsters/speakerinnen_liste/issues/644#issuecomment-398392508

**Comment by zaziemo** [comment]
Hum, I would say we don't need it anymore. But there are 29 profiles where :talks is not nil.
```Profile.where.not(talks: nil).count``` 
I can't see right now where this comes from. 
```Profile.where.not(media_url: nil).count``` results in 28.
Probably you could inspect that more before deleting ;)

**Comment by tyranja** [comment]
I think those are old once, because we used it in the beginning. All those profiles have low id's so there were created at the beginning.

**Comment by tyranja** [comment]
Also once we are finished with that, I have found some more columns to delete :grin: 

See https://github.com/rubymonsters/speakerinnen_liste/issues/644#issuecomment-400039144

**Comment by sabrina-ulbrich** [comment]
I'm done with deleting talks and media_url: pull request #733
