### ISSUE TITLE
Improve loading speed of profile images 

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#730]
Currently it takes a long time to load the start page www.speakerinnen.org (7.3 sec).

A big problem is the speed of image loading, especially the profile images: 
<img width="968" alt="bildschirmfoto 2018-07-16 um 19 57 59" src="https://user-images.githubusercontent.com/2119496/42777024-21be0424-8939-11e8-96d9-b900f1b236e5.png">

Please inspect what causes the long loading times. Size of the images, wrong or insufficient use of carrierwave, connection to Amazon AWS...?

**Comment by sabrina-ulbrich** [comment]
I guess this problem is related to a bad usage of active storage in the profile model, method image_variant. There is no need to build every time a new variant object. Not sure if it is better to upgrade rails to 6.0 before.

**Comment by sabrina-ulbrich** [comment]
@zaziemo I guess I solved the problem with the picture load time (at least the part for the active storage images, the others from carrierwave should be migrated within the next days or maybe 2 weeks). Could you take a look at the speed now to compare it with former load time, please?

**Comment by sabrina-ulbrich** [comment]
@zaziemo I guess this can be closed, isn't it?

**Comment by zaziemo** [comment]
Yeah, right @sabrina-ulbrich I will check that again.

**Comment by zaziemo** [comment]
Ok, I checked again with https://www.webpagetest.org/ and it improved \o/ 
![Bildschirmfoto 2019-11-26 um 09 42 35](https://user-images.githubusercontent.com/2119496/69613547-023a3600-1032-11ea-9e6d-737ca46c198b.png)

There seems to be room for more improvement but I think we close this ticket now.
