### ISSUE TITLE
Contact form: Prevent reload of page when cookie consent is given while writing a message

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#731]
Currently every page reloads after giving cookie consent.
We got a complaint that this also happens while writing a message via the contact form. User clicks on cookie consent "OK", page reloads and the whole message is gone.

Make sure either this site does not reload or the content of the message is temporarily captured.

**Comment by tyranja** [comment]
Maybe we could also make sure the contact window is only shown when the cookie consent is already given. And when it is not given we show a message "Please allow cookies" or sth like that.

**Comment by zaziemo** [comment]
shouldn't be the case anymore since it is only possible to open the contact form when cookie consent is given.
