### ISSUE TITLE
Refactor admin/tags_controller

### ISSUE THREAD

**Issue by netagonen** [rubymonsters/speakerinnen_liste#734]
- [x] Simplify the update method
- [ ] move the session filter params from each redirect to the index method if possible
- [x] see issue [631](https://github.com/rubymonsters/speakerinnen_liste/issues/631)
- [x]  use .includes() after .all queries

**Comment by netagonen** [comment]
Second point won"t be fixed: params need  to be already at the redirect

**Comment by tyranja** [comment]
@netagonen can we close this?

**Comment by netagonen** [comment]
Fixed in PR [#732](https://github.com/rubymonsters/speakerinnen_liste/pull/732)
