### ISSUE TITLE
debug Hashie::Mash warning

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#741]
this comes up after searching:

```You are setting a key that conflicts with a built-in method Hashie::Mash#length defined in Hash. This can cause unexpected behavior when accessing the key as a property. You can still access the key via the #[] method.```

**Comment by tyranja** [comment]
This still exist. I did a quick google search and it seams like this id fixed in the newer versions: https://github.com/elastic/elasticsearch-ruby/issues/398  but not in older once: https://github.com/elastic/elasticsearch-rails/commit/5732fa3   :(

**Comment by zaziemo** [comment]
ok, I think we should upgrade to the newer elasticsearch version in the next months. Will open a new issue and close this one.
