### ISSUE TITLE
Add a 'featured' object 

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#743]
It would be nice to show **featured profiles (** interesting or rare profiles ) on the start page.

For that we would need a new object with the properties:

**- title ( text )**
**- description ( text )**
**- profiles ( array of profile id's )**

_For example: There is a gaming conference in berlin and we want to have more women represented there. 
We could add 4 woman to the feature object with the title: "Women in gaming", have a text about it and then add 4 profile.id's {2,356, 76, 28 }of women we have in our database that have gaming as a topic.
And always the latest feature object is shown on our start page._
_we can also tweet about it with a link to the profiles._

As a first iteration we have to add the profile.id in admin/profile/index view, so we have them. and then create the feature in the console. Later we can add it to our admin interface. 

It should like that:

![featured_speaker](https://user-images.githubusercontent.com/1218914/45561508-39b32d00-b848-11e8-8619-bd05d8536a25.png)

**Comment by zaziemo** [comment]
\o/ deployed! Thanks @sabrina-ulbrich for your work!
