### ISSUE TITLE
Add a 'Kurzkritik'/'review' to the speakers profile

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#748]
In order to make speakerinnen more interactive we could add the possibility for signed in speakers to add a ( positive ) review to other speakers.

It should be more than a 'like' button because then it would be easy for people with a big network to get all theirs friends to like them. 

So it should be a bit more sophisticated with fields like: 
- when did I see/read/hear about that person
- where did I see it
- what did I like

----

Speakerin have a list of speaker they have featured.

### Could look like this:

![screenshot from 2018-09-07 12-31-38](https://user-images.githubusercontent.com/1218914/45214173-07c72700-b29a-11e8-9bc7-14cba64fa63e.png)

### on the page:
![kritik](https://user-images.githubusercontent.com/1218914/45215019-54abfd00-b29c-11e8-8ebc-f0b249da0117.png)

---

We would also need something on the speakerin profile who added the review.

### technical:
We could have a new object called `review` with attributes:

- from_speaker ( profile.id, has_many relation to profile ) 
- for_speaker  ( profile.id, has_many relation to profile ) 
- when ( date )
- where ( text )
- why ( text )

**Comment by zaziemo** [comment]
Wow, what a great issue - not only the idea but also the proficiency of the doing @tyranja.  I'm impressed 😍
