### ISSUE TITLE
Admin scope: Creating Category

### ISSUE THREAD

**Issue by sabrina-ulbrich** [rubymonsters/speakerinnen_liste#772]
I have just noticed that when creating a category, this is displayed twice (admin scope, locally).
![screen shot 2018-10-08 at 23 43 47](https://user-images.githubusercontent.com/372649/46635293-2b5ce600-cb54-11e8-843f-c39a8d396003.png)

**Comment by sabrina-ulbrich** [comment]
no, just displayed twice

**Comment by tyranja** [comment]
That is strange. Do you want to correct that?  Admin is "ausbauwürdig" :)

**Comment by sabrina-ulbrich** [comment]
It's shown twice because its sorted german and english, so I remove the sorting - I think it's not necessary as long as there are only 10 or 15, but more confusing shown twice. Done with #882
