### ISSUE TITLE
update elasticsearch version 

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#781]
to get rid of Hashie Mash warning and keep up with new development

**Comment by zaziemo** [comment]
- [ ] update gem elasticsearch_rails #806 
- [ ] https://www.elastic.co/guide/en/elasticsearch/reference/5.0/setup-upgrade.html

**Comment by zaziemo** [comment]
Some links:
https://logz.io/blog/upgrade-elasticsearch-5/

**Comment by zaziemo** [comment]
Maybe this migration helper plugin can help as well: https://github.com/elastic/elasticsearch-migration/blob/master/README.asciidoc

**Comment by zaziemo** [comment]
https://mendab1e.github.io/dev/2019/03/09/how_not_to_integrate_elasticsearch_testing_with_rspec.html

**Comment by zaziemo** [comment]
https://gist.github.com/zaziemo/1c8f6ed25b17b4200f1f53068e79f905

**Comment by zaziemo** [comment]
- [ ] make spec pass: ./spec/system/searching_for_profiles_spec.rb:48
- [ ] make spec pass: ./spec/controllers/admin/category_controller_spec.rb:124
- [ ] make spec pass: rspec ./spec/controllers/profiles_controller_spec.rb:38
- [ ] make autosuggestions work again

**Comment by zaziemo** [comment]
Already did some work on this branch: https://github.com/rubymonsters/speakerinnen_liste/compare/mah-upgrade-elasticsearch

**Comment by netagonen** [comment]
Steps towards upgrade elastic search locally:
1. Have production data on local machine
2. Re-Index elasticsearch with new data
3. Make sure website on localhost still works
4. Upgrade elasticsearch server and API in the docker container - look at @zaziemo 's branch first:
(links which might be useful for this step that @zaziemo  referred to:
- https://www.elastic.co/upgrade_guide 
- https://logz.io/blog/upgrade-elasticsearch-5/
- https://www.linkedin.com/pulse/upgrading-elasticsearch-2x-5x-gian-giovani/
- https://github.com/elastic/elasticsearch-migration/tree/2.x
5. Upgrade elasticsearsch rail gems - look at @zaziemo 's branch first
6. Test search on website (i.e number of results, autosuggestions) ->
7. Look at changes at elasticsearch API and gems API
(links that might be usefull: 
- https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking-changes-5.0.html
- https://www.elastic.co/guide/en/elasticsearch/reference/5.0/search-suggesters-completion.html)
8. Fix search specs (look at @zaziemo list above).
(link that might be useful: https://mendab1e.github.io/dev/2019/03/09/how_not_to_integrate_elasticsearch_testing_with_rspec.html)

**Comment by netagonen** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_suggester.html
https://www.elastic.co/guide/en/elasticsearch/reference/5.0/search-suggesters-completion.html
https://www.elastic.co/blog/strings-are-dead-long-live-strings

**Comment by langjoh** [comment]
@netagonen Hi Neta, about step 4 (Upgrade elasticsearch server and API in the docker container): I think all you have to do is to specify a later version of the elasticsearch image in the docker-compose.yml. At the moment it is ``` image: elasticsearch:2.4.5 ``` .
Here you can find all available image versions: https://hub.docker.com/_/elasticsearch and then search under 'tags' for your preferred version.

**Comment by netagonen** [comment]
@langjoh thanks fir the reply and sorry for the late response- you are totally right! we did spend some time until we realize it. I still have a question regarding the `volumes:` Could you maybe help?    
 in the docker-compose.yml we commented out `volumes: - elastic_data:/usr/share/elasticsearch/data2`
so version 6 could work, otherwise there is an error. we need to find out how to make it work. Maybe some helpfull links:
https://discuss.elastic.co/t/elastic-elasticsearch-docker-not-assigning-permissions-to-data-directory-on-run/65812/4
https://github.com/elastic/elasticsearch-docker/issues/21

**Comment by netagonen** [comment]
hi @zaziemo ,
There is some progress :) all documented here: https://cloud.speakerinnen.space/f/22379
Can also move it here to the issue if it's better. see also PR #1091 .
There is still more work to do...

**Comment by zaziemo** [comment]
@netagonen @alonpeer concerning *min_score*

I think we need one - or probably some more tweaking with the tie_breaker or field weighs.
Can you explain how the profiles in the search results are ordered? Is it after the scores? 

I made tests with the following search terms:
1) for „Social Business“, being in :en

Localhost: 1.108 speakers
examples for non matching profiles (for my understanding): 
http://localhost:3000/en/profiles/nina-mohimi 
http://localhost:3000/en/profiles/arlene-buehler
http://localhost:3000/en/profiles/alexandra-grassler

Production: 388 speakers (but there are also some profiles I would not consider matching to the search terms)

2) „programmieren frauen“, being in :en

localhost: 541
examples for non matching profiles (for my understanding)::
http://localhost:3000/en/profiles/anja-blodow
http://localhost:3000/en/profiles/regula-simon
http://localhost:3000/en/profiles/annika-peters

not really matching but cool to list it: http://localhost:3000/en/profiles/janina-tiedemann 
--> which is an argument for being not so strict with the matching terms 

production: 159

**Comment by zaziemo** [comment]
@netagonen @alonpeer 
Concerning autosuggestions:
Here I don't get the same autosuggestions as on production which is good, because currently the suggester seems to be buggy if not broken :(

I would say it works as expected.

The suggested terms seem to be sorted by a score. Do you know what this score is about?

**Comment by zaziemo** [comment]
Solution for 0 Matches --> I opened a new issue. I think this is out of the scope for this one here.

**Comment by zaziemo** [comment]
@netagonen concerning cities: I think it is good to have the cities not analyzed. I remember faintly that we had problems with people having a city name as their real name. Besides as the cities serve as filters they are already covered.

**Comment by zaziemo** [comment]
@netagonen concerning the HashWrapper. Do I get it right that we have to add it somehow? If we have to, we should do it. This was one of the reasons we wanted to update elasticsearch in the first place (we were annoyed by these warnings.)

**Comment by alonpeer** [comment]
Hi @zaziemo. I just checked, and the `Hashie::Mash#key` warnings appear on my localhost when I'm on the master branch, but no longer appear on the `neta/upgrade-elastic-6.7` branch. 🎉

**Comment by zaziemo** [comment]
The country filtering does not work anymore.

To reproduce: 
1) search for anything
2) click on one country in the most left column
You get this view
<img width="1066" alt="Bildschirmfoto 2020-11-23 um 19 31 38" src="https://user-images.githubusercontent.com/2119496/100000914-97e1e000-2dc2-11eb-9c59-f88ac56a9492.png">
