### ISSUE TITLE
UX: Split-Screen

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#793]
based on Salit's suggestions: new startpage, separated for event organizers and speakers

Desisions -->
Q1: Should we adapt this idea?
Q2: If yes, what would be the nexts steps? What do we need?
<img width="874" alt="bildschirmfoto 2018-11-13 um 20 41 22" src="https://user-images.githubusercontent.com/2119496/48438556-85b91a00-e784-11e8-9779-c8f092c13fa0.png">

**Comment by jancborchardt** [comment]
@alicetragedy and I had a small design chat about this today and this seems to be a good way to go from our view. :slightly_smiling_face: 

Some further thoughts:
- The randomized showing of some profiles directly on the front page is pretty cool, it should be directly below the split. It shows you "Be part of this cool group of people" for people with no profile yet and also "This wide array of speakers is already here" for organizers
- If you are logged in, the left part of the main page could directly show your profile as it appears to others (or a quick version, with some hints what to add, like media links)
- For organizers, the next step other than a search could be a sentence-like interface somehow similar to this:
    - I’m looking for `speakers / workshop leaders / moderators / …`
    - in the field of `programming / ecology / …`
    - who speak `English / German / Spanish / …`
    - OPTIONAL: living in `Anywhere / Berlin / Madrid / etc …`

What do you think?

**Comment by zaziemo** [comment]
@jancborchardt thanks for your ideas and suggestions! I will forward it to the UX person who is currently working on the details :)
