### ISSUE TITLE
Got warning about Ruby version

### ISSUE THREAD

**Issue by jancborchardt** [rubymonsters/speakerinnen_liste#819]
When installing Ruby for the project via `rvm install "ruby-2.3.1"` I got this warning:
```
Install of ruby-2.3.1 - #complete 
Please be aware that you just installed a ruby that requires 2 patches just to be compiled on an up to date linux system.
This may have known and unaccounted for security vulnerabilities.
Please consider upgrading to ruby-2.5.1 which will have all of the latest security patches.
```

Fiftypercent for example uses Ruby 2.4.2, so it might be good to upgrade and use the same? :slightly_smiling_face: 

(cc @alicetragedy as we are working on setting up both projects locally.)

**Comment by tyranja** [comment]
Sounds like a good idea. Thank you for reminding us! :two_hearts:

**Comment by tyranja** [comment]
It is done: https://github.com/rubymonsters/speakerinnen_liste/blob/master/Gemfile#L4 

Thanks again @jancborchardt and @alicetragedy! :bouquet:
