### ISSUE TITLE
Personal profile details: Links are localizable?

### ISSUE THREAD

**Issue by jancborchardt** [rubymonsters/speakerinnen_liste#838]
In the lower part of the profile, the links are inside the translatable container. This is useful for people who have separate profiles, but seems to be an edge-case?

And now when your website or Twitter profile changes, you have to change it in both languges. Maybe it’s better to do it like in the "Media links", where you can define the language a link or talk is in? That way when you are German or Portuguese but can still read English, the links still show.

cc @alicetragedy as we saw this while reviewing the site. :)

**Comment by zaziemo** [comment]
@jancborchardt & @alicetragedy thanks for your input. I have one question to better understand what you want to achieve: Do you want that people that change their website or twitter account only have to change it in one place or is it confusing that the provided links only show up in one language environment (english links in english locale, german in german)?

**Comment by jancborchardt** [comment]
> Do you want that people that change their website or twitter account only have to change it in one place

This for sure, yes.

> or is it confusing that the provided links only show up in one language environment (english links in english locale, german in german)?

This is also slightly confusing. Do you in practice actually have a lot of people who have _separate_ links for their Twitter profiles?

As mentioned, the solution in the personal profile where you list "media links" is a bit more obvious since you can just add stuff in a list and add in which language that is (default being English).

This is much better than the tabs, also because the tabs are "exclusive" and hide things which don’t need to be hidden. I might browse Speakerinnen in german, but for people who have their german Twitter profile listed, I’d still like to see their english one too.
