### ISSUE TITLE
Redesign FAQ page

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#873]
We need to redesign our FAQ page to make it more clearly and easy to read: https://speakerinnen.org/de/faq

For example like that: 
https://podcasterinnen.org/faq

**Comment by zaziemo** [comment]
Hinweis: @Programmiererinnen: bitte Die Fragen bzw. Schritte und Tipps unten als Dropdown-Zieharmonika anlegen, sodass man alle Fragen auf einem Blick sieht und die Antworten dann entsprechend aufklappen kann.
Hinweis 2: bitte gff. Ankerlink auf „Schritte zum Anlegen eines aussagekräftigen Profils“ in der Bestätigungsmail an neue Speakerinnen ändern.
--

FAQ 
Hier beantworten wir Eure wichtigsten Fragen zur Plattform Speakerinnen.org und dazu, wie Ihr ein möglichst aussagekräftiges Profil anlegen könnt.
Allgemeine Fragen zur Plattform Speakerinnen.org:
Wer kann sich auf Speakerinnen.org eintragen?
Hier noch unsere Entscheidung abwarten oder:
Speakerinnen.org hat das Ziel, mehr Frauen auf Bühnen und Podien, zu Konferenzen, Workshops, Meetings und in die Medien zu bringen. Es können sich daher alle registrieren, die sich selbst als Frau verstehen.
Nach der Registrierung prüft das Speakerinnen-Team jeden Eintrag vor der Freischaltung auf Vollständigkeit.

Welche Themen kann ich wählen?
Du kannst selbst Deine Themen vergeben. Bei der Eingabe eines Themas werden Dir ähnlich lautende Vorschläge gemacht – Du kannst diese Direkt anwählen oder ein anderes, neues Thema anlegen. Themen kannst Du in allen Sprachen eingeben.
Die Themen werden von uns in Kategorien gebündelt und auf der Speakerinnen-Seite präsentiert.

In welcher Sprache kann ich ein Profil anlegen?
Du kannst Dein Profil ausschließlich auf Deutsch, ausschließlich auf Englisch oder in beiden Sprachen anlegen. Legst Du ein Profil nur in einer Sprache an, wird es nur auf der jeweiligen deutschen bzw. englischen Sprachversion gefunden. Legst Du es auf Deutsch und Englisch an, wirst Du auf beiden Sprachversionen gefunden.

Warum ist mein Profil noch nicht freigeschaltet?
Wir arbeiten ehrenamtlich im Speakerinnen-Team und sind daher nicht ständig online: Wenn Du also Dein Profil gerade erst eingetragen hast, kann es einen Moment dauern, bis wir es per Hand freischalten. 
Falls Du sehr wenige Informationen in Deinem Profil hinterlegt hast, dachten wir möglicherweise, dass es noch nicht fertig ist. Wenn Du möchtest, dass es trotzdem freigeschaltet wird, dann schreib uns eine Mail an team@speakerinnen.org. 

Ich habe bereits einen Account – wie kann ich Mailadresse und/oder Passwort ändern?
Melde Dich unter „Einloggen“ mit Deiner Mailadresse und Passwort an. Nach der Anmeldung klicke in Deinem Profil oben rechts auf „Benutzerkonto bearbeiten“. Hier kannst Du Dein Mailadresse und/oder Dein Passwort ändern. Ein Klick auf „Aktualisiere Account“ – fertig.

Wie kann ich Euch Geld spenden?
Yay, das ist eine super Idee! Leider können wir gerade (noch) keine Spenden annehmen, hoffen aber, dass das bald möglich sein wird.


Schritte zum Anlegen eines aussagekräftigen Profils:
Schritt 1: Als Speakerin registrieren
Rechts oben auf der Seite findest Du den Button „Als Speakerin registrieren“ – draufklicken und schon geht es los!
Zuerst musst Du Deine E-Mail-Adresse eingeben, dann ein Passwort Deiner Wahl. Dieses bitte wiederholen. Dann auf „Registrieren“ klicken.

Du erhältst nun eine E-Mail an die angegebene Adresse. Hier findest Du den Link „Bestätige meinen Account“ – draufklicken!
Du kommst nun wieder auf die Speakerinnen-Seite, wo Du Dich mit E-Mail-Adresse und Passwort anmelden kannst.

Übrigens: Eine Registrierung funktioniert auch über Twitter. Dafür einfach auf „Über Twitter registrieren“ klicken, dann wirst Du zu Twitter weitergeleitet.
Hier wirst Du gefragt: „Speakerinnenliste berechtigen, Deinen Account zu nutzen?“. Wenn Du auf Anmelden klickst, geht es zurück auf die Speakerinnen-Seite. Hier musst Du nur noch eine E-Mail-Adresse eingeben.
Anschließend erhältst Du eine E-Mail, in der Du den Satz „Bestätige meinen Account“ findest. Draufklicken, dann wirst Du auf die Speakerinnen-Seite zurückgeleitet, wo Du Dich mit E-Mail-Adresse und Passwort anmelden kannst.

Schritt 2: Profil ausfüllen
Sobald Du eingeloggt bist, kommst Du auf Deine Profilseite. Hier steht nun: „Hier gib es noch nix zu sehen ¯\_(ツ)_/¯.“ 
Um Dein Profil zu vervollständigen, klicke rechts auf den Button "Profil bearbeiten". 
Auf der Seite, die sich nun öffnet – „Aktualisiere Dein Profil“ – kannst und solltest Du verschiedene Profilinformationen hinterlegen: Vorname und Nachname, das Land in dem Du wohnst und tätig bist und die Sprachen, die Du sprichst.
Bitte keine Programmiersprachen eingeben – sie gehören zu Deinen Themen.

Rechts findest Du unter „Bild“ den Button „Datei auswählen“. Hierüber kannst Du ein Profilfoto hochladen. Bitte nutze ein jpg, jpeg oder png und achte darauf, dass Du die Rechte an diesem Foto besitzt! Die Größe des Fotos sollte kleiner als 1 MB sein.
Dir ist vielleicht aufgefallen, dass die Profilfotos auf unserer Seite in schwarz-weiß angezeigt werden. Wenn man mit der Maus darüber fährt, erscheint das Original. Deshalb wäre es schön, wenn Du ein farbiges Bild verwendest, damit dieser Effekt entstehen kann.

Jetzt kannst Du Tags eingeben, also die Themen, mit denen Du Dich beschäftigst. Das kann Journalismus sein, Biotechnologie oder Netzfeminismus. Bitte prüfe zuerst, ob es bereits Tags gibt, die Du nutzen kannst.
Du findest sie, indem Du einfach die ersten Buchstaben Deines Wunsch-Tags eingibst – dann werden Dir Begriffe vorgeschlagen. Oder Du schaust Dir auf der Speakerinnen-Seite an, welche Themen bereits eingegeben wurden.

Im nächsten Schritt findest Du zwei Reiter: Deutsch und Englisch. Hier kannst Du weitere Profilinformationen jeweils in beiden Sprachen hinterlegen. Du kannst aber auch nur den deutschen bzw. nur den englischen Reiter ausfüllen. Hier gibst Du an: die Stadt, in der Du wohnst und soweit vorhanden einen Twitter-Account sowie eine oder mehrere Webseiten. 
Als nächsten hinterlegst Du hier einen Themenschwerpunkt. Das sollte Dein Hauptthema sein – nur eins, bitte eindeutig und gut verständlich. Beispiele hierfür sind „Social Media“, „Nachhaltige Landwirtschaft“ oder auch „Human Resources“.
Das Hauptthema erscheint als Bildunterschrift unter Deinem Profilfoto. Wichtig: in der Übersicht der Profile wird das Hauptthema auf 31 Zeichen begrenzt.

Nun auf jeden Fall das Feld „Biografie“ ausfüllen!
Ohne Angaben in diesem Feld können wir das Profil nicht freischalten. Du kannst das alles auf Wunsch auch auf Englisch eingeben, das ist aber keine Pflicht. Diese Angaben werden nur angezeigt, wenn man auf die englische Version der Seite (siehe oben rechts) klickt.

Abschließend einfach ganz unten auf „Aktualisiere Dein Profil“ klicken und schon siehst Du Dein Profil, wie andere es nach der Freischaltung sehen werden.
Bei Bedarf kannst Du Dein Profil jederzeit nachträglich bearbeiten.

Schritt 3: Referenzen angeben
Um Referenzen einzutragen, klicke bitte rechts auf den Button „Referenzen bearbeiten“. Es öffnet sich die Überblicksseite Deiner Referenzen.
Klicke dann auf den Link „Referenz hinzufügen“ und gib nun eine URL, wo die Referenz zu finden ist, eine Überschrift sowie eine kurze Beschreibung an. Dann gib bitte per Dropdown kurz die Sprache an, in der Dein Vortrag, Dein Diskussionsbeitrag etc. verfügbar ist. Dann auf „Referenz hinzufügen“ klicken und schon befindet sich die Referenz unter „Meine Vorträge / Referenzen“ in Deinem Profil.
Du kannst die Reihenfolge der Referenzen jederzeit problemlos verändern, indem Du sie einfach nach oben oder unten verschiebst.
Willst Du Dir Dein fertiges Profil anschauen, gehe einfach auf den Link „Eigenes Profil anzeigen“ und schon siehst Du, wie Dein fertiges Profil nach der Freischaltung aussehen wird.

Schritt 4: Freischaltung
Das Speakerinnen-Team erhält eine Benachrichtigung bei jeder neuen AnmelDung. Wir werden Dein Profil – wenn es vollständig ist – so schnell wie möglich freischalten.
Solltest Du Rückfragen haben oder Dich wundern, warum Dein Profil noch nicht sichtbar ist, wende Dich jederzeit an Christiane vom Speakerinnen-Team unter christiane[at]speakerinnen.org!
Sobald Dein Profil für alle sichtbar ist, erhältst Du eine automatische E-Mail, die Dir sagt: Dein Profil wurde jetzt freigeschaltet!

Tipps: Wie erstelle ich ein möglichst aussagekräftiges Speakerinnen-Profil?
Füge ein gutes Foto von Dir ein! Dieses kannst Du auf Wunsch jederzeit wieder austauschen.
Lass die Kategorie „Meine Biografie“ nicht leer! Wird sie nicht ausgefüllt, können wir das Profil in der Regel nicht freischalten.
Füge in der Kategorie „Meine Biografie“ keinen allzu langen Fließtext ein – übersichtlich, schnell erfassbar und aussagekräftig soll es sein!
Fülle möglichst auch die Kategorie „Meine Vorträge“ aus. Falls Du bisher keine Vorträge gehalten hast, beschreibe in der Biografie Deine Erfahrungen, die das wieder ausgleichen! Vielleicht gibt es ja auch eine Website, die Deine Erfahrungen veranschaulicht. Auch diese kannst Du unter „Meine Vorträge“ eintragen.
Die Tags dienen dazu, schnell und eindeutig zu verdeutlichen, wo Deine Kompetenzen liegen, damit die Veranstalter möglichst schnell eine passende Speakerin finden. Orientiere Dich daher an den bestehenden Tags! Wenn Du neue Tags eingibst, nutze möglichst nicht mehr als 1-2 Wörter und beschreibe Dein Kompetenzfeld eindeutig und selbsterklärend!

**Comment by zaziemo** [comment]
- [ ] copy english translations from here https://speakerinnen.org/en/faq for the first 4 questions
- [ ] get translation done for new How-to-texts
- [ ] add anchor named "howto_anker" that opens directly the "How to"-question
