### ISSUE TITLE
check if certain sites can be scraped again by google

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#876]
context: if people change their name, the slug /firstname-name changes as well.

The link with the previous name does not work anymore and the user gets an error page. 
Please check: Is it possible to tell google to crawl a certain site again (eg. if name changes)?

**Comment by sabrina-ulbrich** [comment]
Idea: Women can enter a name for the url themselves. If the name changes (for example, on marriage), they can change the field themselves, or we suggest that two urls refer to the same profile.

**Comment by netagonen** [comment]
Are users aware of this problem? 
Can we warn them not to change their names?
OR
Is it a feature that is not yet implemented? 
How would we want to implement it? 
Would it be a mandatory field? 
What happens with all the users who changed their names so far?

**Comment by zaziemo** [comment]
@netagonen this is something that is already implemented. We use the gem `friendly-id` to make routing by name instead of id possible (default Rails Route `.../profiles/1` vs. .../profiles/maren-heltsche`). This comes with the downside that if the name changes the slug (last part of the route) also changes. 

I think we shouldn't prevent our users to change their names. Nobody would do that unless it is really necessary. 
I also would prefer not to let people themselves decide how their slug might be named as @sabrina-ulbrich suggested. 

As I described above it would be great if we could "tell" google somehow to crawl the site again (because to my knowledge this is the only context the problem really is a problem) or
alternatively we could see if we have a redirection from the old URL to the new one as @sabrina-ulbrich also suggested.
