### ISSUE TITLE
change z-index of flash messages

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#880]
Currently the profile cards are overlaying the flash message if you are redirected after signing in

<img width="1241" alt="bildschirmfoto 2019-02-18 um 19 15 39" src="https://user-images.githubusercontent.com/2119496/52969810-0013be80-33b2-11e9-8c44-bf5611fa4604.png">

**Comment by sabrina-ulbrich** [comment]
Fixed in #882
