### ISSUE TITLE
Change categories partial in main page

### ISSUE THREAD

**Issue by netagonen** [rubymonsters/speakerinnen_liste#898]
branch name: ```replace_categories_partial```
Add a new categories partial
Mention the number of profile next to each category
implement according to Salit's design
![categoris_partial](https://user-images.githubusercontent.com/22200510/54537142-4b5dc480-4992-11e9-8bdb-61c2528a1f61.png)

**Comment by netagonen** [comment]
Just to make sure, what happens when we click on a category? a page with related profiles is opened?

**Comment by netagonen** [comment]
Current progress:
![image](https://user-images.githubusercontent.com/22200510/55009394-c18da700-4fe2-11e9-8bfc-e5c623c5452e.png)

remained issues:
1. the colors are not stretching on the whole width of the page. The margins are giving me troubles. Couldn't figure it out yet.
2. the fading of the color: how do we want to calculate it? what does the number represent? the actual number of profiles? some kind of percentage? 
3. the title: should be also changed?

**Comment by zaziemo** [comment]
@netagonen great progress so far :)

ad 1) we set a `max-width`of 1200px for the container and a padding. We have to adapt this for the whole page as far as I interpret Salit's drafts. I'd suggest you keep on implementing the functionality and we solve that problem later.
ad 2) colors --> I'll ask Salit, numbers: I think we said it's the number of profiles that are connected to this category. 
ad 3) do you mean "Browse by category" if you have a better idea, let's discuss :)

**Comment by zaziemo** [comment]
@netagonen I tried some things out and opened this new branch: https://github.com/rubymonsters/speakerinnen_liste/tree/mah_suggestion_categories_partial

Feels a little hacky and some things aren't resolved yet (see commit message)
<img width="1245" alt="Bildschirmfoto 2019-03-27 um 22 28 27" src="https://user-images.githubusercontent.com/2119496/55113521-c5532380-50df-11e9-81b7-ac306375975f.png">

**Comment by netagonen** [comment]
Thanks @zaziemo :)
I inserted the no-gutters class. Couldn't now have a padding at all on the right side :).  
We should decide on a calculation first maybe? Salit's calculation seems like a percentage, we want to put the number of profile. If we put the percentage of profiles from the total number of profiles it doesn't look as good as in Salit's demo cause most of it is less then 50%.  
Also- the width of the screen is wider then what seems in Salit's demo.
So I have a suggestion: Maybe we won't make the colors fade at all? it then could look like this: 
![image](https://user-images.githubusercontent.com/22200510/55265260-ddf64180-5277-11e9-9b76-2d04edc21768.png). 
About the title I meant: how should we design it? the fonts of the title and the categories are different and I think they should be the same. Also in Salit's suggestions the title is centered but I think maybe it should be aligned with the rest of the text on the start page (and also the categories text??).

**Comment by netagonen** [comment]
This is current state: 
![image](https://user-images.githubusercontent.com/22200510/55714146-5edcd800-59f2-11e9-9fc8-61a6bc5e8c1d.png)

I am not sure this is best solution... I am pretty sure we can do something better. @zaziemo, let's discuss it when we meet

**Comment by netagonen** [comment]
Progress! 
the design is there! @zaziemo, thanks for the helpful link.
to do's:
[ ] optimize DB queries in categories_helper.rb
[ ] test new helper methods 

![image](https://user-images.githubusercontent.com/22200510/55873320-9fbe2380-5b8f-11e9-8a2f-6992e0b1b542.png)

**Comment by zaziemo** [comment]
🎊🎉🌈❤️😍👩🏽‍💻
