### ISSUE TITLE
refactor profile feature to remove n+1 query

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#903]
search for the place in the code which asks for the translation of the profile and refactor it

**Comment by sabrina-ulbrich** [comment]
![feature_profile](https://user-images.githubusercontent.com/372649/54560624-0aca6f00-49c3-11e9-92c3-0b7e2604df42.jpg)

**Comment by tyranja** [comment]
@sabrina-ulbrich Was starting to read that blogpost: **https://www.speedshop.co/2019/01/10/three-activerecord-mistakes.html**

And we should also replace the `if @features.any?` with `if @features.load.any?`

**Comment by tyranja** [comment]
I guess we can close this for now.
