### ISSUE TITLE
link to nowhere?

### ISSUE THREAD

**Issue by sabrina-ulbrich** [rubymonsters/speakerinnen_liste#907]
Link "Suche anpassen >>" seems to be obsolete
![Screen Shot 2019-03-26 at 21 11 07](https://user-images.githubusercontent.com/372649/55030206-26a9c280-500c-11e9-968a-12c6480b44dd.png)
I get a random speaker but expected kind of advanced search.

**Comment by zaziemo** [comment]
I would have expected a link to the "normal" search where I can start over again.

**Comment by sabrina-ulbrich** [comment]
"Normal" search is also ok, but what I found irritating is, that I get the headline "Wir haben eine Speakerin gefunden!" although I didn't type anything into the searchfield ... and with always the same profile of Hannah Förster

**Comment by zaziemo** [comment]
@sabrina-ulbrich this is weird indeed 🤓

**Comment by sabrina-ulbrich** [comment]
Something else: I search for a name that doesn't exist, so I get similar suggestions (which is cool), but I don't get the search field again, what I want if the suggestions doesn't match:
![Screen Shot 2019-03-28 at 19 41 18](https://user-images.githubusercontent.com/372649/55184263-fee46700-5191-11e9-94c2-69ad11bd916f.png)

**Comment by tyranja** [comment]
So, Hannah Förster had in the twitter field `###` which was not a twitter handle and I guess that is what the search found. So I deleted it and no we have the correct behavior when searching with an empty search field.
