### ISSUE TITLE
unify gender star

### ISSUE THREAD

**Issue by sabrina-ulbrich** [rubymonsters/speakerinnen_liste#909]
I found Speakerinnen, Organisator*innen, Speakerinnen*, Speaker\*innen. We should chose one form. I prefer Organisator*innen.

**Comment by sabrina-ulbrich** [comment]
damned autoformatting, I mean the star is sometimes in the middle, sometimes in the end, sometimes without star and also a slash before the star

**Comment by tyranja** [comment]
We can ask that next Monday in the meeting.

**Comment by zaziemo** [comment]
done!
