### ISSUE TITLE
add scroll-padding to elements that overlap anchors

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#913]
<img width="1172" alt="Bildschirmfoto 2019-04-04 um 10 27 47" src="https://user-images.githubusercontent.com/2119496/55540978-561f9580-56c4-11e9-9fb0-09e1d606cdee.png">

https://css-tricks.com/fixed-headers-on-page-links-and-overlapping-content-oh-my/

**Comment by tyranja** [comment]
A good idea but in the blog is mentioned that right now this only works on Chromium :(
