### ISSUE TITLE
Use pagy istead of kaminari 

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#914]
Now we are using kaminari. It would be great to switch to pagy because it is faster.

https://github.com/ddnexus/pagy

**Comment by rebecarancan** [comment]
Hello, can I work on this issue?

**Comment by sabrina-ulbrich** [comment]
Sorry, for the late response, but sure, you can work on this. We are happy about it! Feel free to ask, if there are questions.

**Comment by sabrina-ulbrich** [comment]
@rebecarancan Do you still want to work on the pagy issue?

**Comment by rebecarancan** [comment]
I'm working on it!

**Comment by sabrina-ulbrich** [comment]
@rebecarancan Cool :) so I assigned you to this issue.

**Comment by rebecarancan** [comment]
Hello @sabrina-ulbrich, I'm almost done with this issue, but I'm having trouble to paginate the profiles index with the params[:search]. I'm trying to use the Pagy Extra for ElasticSearch, but it's not working. Could you help me?

**Comment by sabrina-ulbrich** [comment]
Hi @rebecarancan, yes, I can try :) What's the problem? Maybe you can make a pull request (with "Work in progress" in the title to mark it as not ready) if this is better to show the context.

**Comment by rebecarancan** [comment]
@sabrina-ulbrich, I'll make a pull request to show you the problem then.
