### ISSUE TITLE
Duplicate profiles with tag-search

### ISSUE THREAD

**Issue by sabrina-ulbrich** [rubymonsters/speakerinnen_liste#915]
I wanted to see all profiles for the tag "musik", get 28 profiles on 2 pages. On the second page, however, profiles were displayed that already existed on the first page. These are not always the same (like the last or the first ones), but in a new attempt there are different profiles shown twice.

**Comment by tyranja** [comment]
Maybe, its because every time you go to the first page back, it is loaded again randomly. We can try that on sunday

**Comment by sabrina-ulbrich** [comment]
If so, it is a bit uncomfortable for people looking for a specific keyword. Anyway, I would like to see each profile only once, otherwise it's confusing. What do you mean @tyranja ?

**Comment by sabrina-ulbrich** [comment]
resolved with pr #1195
