### ISSUE TITLE
Improve search

### ISSUE THREAD

**Issue by sabrina-ulbrich** [rubymonsters/speakerinnen_liste#918]
Some notes about searching and tags. There is something we have to think about:
If someone search for i.e. "twitter" she gets all profiles with single "twitter" tag but not these with i.e. "twitter for journalists". 
Another case: Someone has the tags "influencer marketing", "video marketing", "online marketing", "content marketing" and "social media marketing" but is not shown when I list all tags with "marketing".
So I think it doesn't make sense to create such complex tags (even only two words) because nobody search for it or only in special cases. Maybe it's better to make a difference between searchable tags (which are short (one word?) or maybe given) and kind of key terms on the other hand that are more like a selfmade description from the women.

**Comment by sabrina-ulbrich** [comment]
I renamed this issue because it can be solved with improvement of the search algorithm. There are also some cases in #1011 that can be solved by such improvement, so that "workshop" and "workshops" serve the same results.

**Comment by zaziemo** [comment]
cited from #1011:
Also: Unusual/individual spelling with only one profile (e.g. "mutter*schaft" but not found in "mutterschaft")

And: Topics/tags are only displayed if that correspond to the selected language. Most people will probably not be aware of this. Is that described somewhere?
