### ISSUE TITLE
Handling invalid picture format

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#928]
Someone uploaded a picture in .webp format (https://developers.google.com/speed/webp/) which is currently not valid.

Either we have to catch the error or to make the use of this format possible.

**Comment by zaziemo** [comment]
https://stackoverflow.com/questions/52176142/error-with-webp-images-when-using-active-storage-on-heroku

**Comment by Powerglove** [comment]
@netagonen and I tried to reproduce this error but uploading a webp file worked without any problems. 
But we found out that we could validate image type with this code:
`   validate :image_type `

``` 
def image_type
    if !image.content_type.in?(%('image/jpeg image/png'))
        errors.add(:image, "needs to be a jpeg or png!")
    end
end 
```

**Comment by sabrina-ulbrich** [comment]
For now I excluded use of other formats than jpg, png or gif in this PR #1085. I would recommed to close this issue to get an better overview what is really needed. What do you mean @zaziemo ?
