### ISSUE TITLE
Contact Mail mark rquired fields and if possible redirect when error to the same page 

### ISSUE THREAD

**Issue by sabrina-ulbrich** [rubymonsters/speakerinnen_liste#930]
There are stars at the first two fields, so it can be interpreted as optional fields, but that's not the case. Actually all fields need to be filled out. When I fill out the form without a name I get an error message and get redirected to another form (same fields but not the popup field). It works, but it's confusing.

- [x] Mark all fields as required. ( easy )
if possible:
- [ ] to redirect to the same page with an open contact module. ( difficult )

**Comment by kolja-lucht** [comment]
Hey @tyranja and @sabrina-ulbrich,
it's been almost a year since I picked up this issue... 🙈  Does it still need to be fixed? I'm willing to give the redirect another try. What do you say? 😊

**Comment by sabrina-ulbrich** [comment]
Hi @kolja-lucht,
yes, this issue with the redirection is still open. If you want to fix that, we would be happy! 😄

**Comment by kolja-lucht** [comment]
Sounds good. Will give it a shot then 🙂

**Comment by kolja-lucht** [comment]
How attached are you to this flash alert message when not all fields are filled out?

![Screenshot 2020-10-10 at 18 43 55](https://user-images.githubusercontent.com/6205839/95763668-a0b5a100-0caf-11eb-9d1b-6e8e16dec003.png)

It seems to be quite tricky to get that to work inside the modal. Of course I would make sure the error messages for each empty field ("can't be blank") will still appear inside the modal to show the user what went wrong.

**Comment by zaziemo** [comment]
@sabrina-ulbrich @tyranja do you think we should take the effort to get this done or close the issue?
