### ISSUE TITLE
profession not saved on production

### ISSUE THREAD

**Issue by sabrina-ulbrich** [rubymonsters/speakerinnen_liste#956]
The profession is saved locally and on staging but not on production. I can fill in the field, but is not shown in the views (both english and german)

**Comment by sabrina-ulbrich** [comment]
now it works :) does anybody change something?

**Comment by tyranja** [comment]
haha, no maybe some caching in your browser?

**Comment by sabrina-ulbrich** [comment]
ja, maybe ... however, it's weird ... do we have any control about that from the script side? I wonder how this works for other profiles. @zaziemo could you please add a profession to your profile on production and check if it works, please? If yes, then we can close this issue.

**Comment by sabrina-ulbrich** [comment]
@tyranja yes, I close it, maybe it's just me having problems with it
