### ISSUE TITLE
Translate new FAQ and How To into english

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#970]
We need a translation of this text into english:

https://gist.github.com/zaziemo/5427aa21433493e8fbebc6ae5e2e0276

Some of the texts are similar to our current FAQ: https://speakerinnen.org/en/faq

**Comment by nicolaiparlog** [comment]
Would it be possible to do this question-by-question, spread out across several contributors? If you open a pull request, people could propose their translations as comments. Or you translate the questions and people propose their translations as reviews. Either way would make it obvious for contributors what's left to be translated.

**Comment by nicolaiparlog** [comment]
Until then, I'll add a Q&As here... :smiley_cat: 

# Who can register on Speakerinnen.org?

The goal of Speakerinnen.org is to get more women on stages and podiums, to conferences, workshops, meetings, and into media. Hence, everybody who identifies as a women can register herself. The Speakerinnen team vets every submission for completeness before publishing it.

**Comment by nicolaiparlog** [comment]
# Which topics can I choose?

You can freely choose your own topics. Upon entering one, you'll get suggestions of similar topics - you can choose one of them or create a new topic. Topics can be in any language. We organize topics into categories, which are then displayed on the Speakerinnen site.

**Comment by nicolaiparlog** [comment]
# Which languages can I use for my profile?

You can create your profile in either exclusively German, exclusively English, or once in each language. If you create your profile in just one of the languages, it will only be shown in the [German](https://speakerinnen.org/de) or [English](https://speakerinnen.org/en) version of the site. If you create your profile in both languages, it will be shown in both language versions.

**Comment by nicolaiparlog** [comment]
# Why is my profile not yet published?

The Speakerinnen team consists of volunteers and is not constantly online. If you just submitted your profile, it can take a moment before it is reviewed and published. If you only provided very little information, we may assume that it's not yet complete. If you want to publish it anyways, send a mail to team@speakerinnen.org.

**Comment by zaziemo** [comment]
@nicolaiparlog thank you so much :)

**Comment by zaziemo** [comment]
![kaputt](https://user-images.githubusercontent.com/2119496/73201766-0a9a1480-413a-11ea-85cc-c537e2d72927.png)
![Schritt3-Referenzen-en-1](https://user-images.githubusercontent.com/2119496/73201767-0b32ab00-413a-11ea-9c91-be39dbe0cab8.png)
![Schritt3-Referenzen-en](https://user-images.githubusercontent.com/2119496/73201769-0b32ab00-413a-11ea-890a-7c678f4c7e72.png)
![Schritt2-Profil2-en](https://user-images.githubusercontent.com/2119496/73201770-0b32ab00-413a-11ea-9fbb-14c10dda9dd4.png)
![Schritt2-Profil2-de](https://user-images.githubusercontent.com/2119496/73201771-0b32ab00-413a-11ea-9131-e3a16d5b1d4b.png)
![Schritt2-Profil1-en](https://user-images.githubusercontent.com/2119496/73201773-0bcb4180-413a-11ea-975d-36f3052fd3a7.png)
![Schritt2-Profil1-de](https://user-images.githubusercontent.com/2119496/73201774-0bcb4180-413a-11ea-8fa0-a93ffd0567c1.png)
![Schritt1-Anmeldung-en](https://user-images.githubusercontent.com/2119496/73201775-0bcb4180-413a-11ea-8a8a-2ac0e7361915.png)
![Schritt1-Anmeldung-de](https://user-images.githubusercontent.com/2119496/73201776-0bcb4180-413a-11ea-9e43-1381a0ddaf3c.png)

**Comment by kolja-lucht** [comment]
Hey @zaziemo and @langjoh, do you still need help with the translations? I'm happy to pick something up :)

**Comment by zaziemo** [comment]
hey @kolja-lucht, as far as I remember this work is done. But this is a good reminder to actually close the ticket :)
If you are interested in doing something I can get back to you after our team call this evening and propose you some tickets.
