### ISSUE TITLE
Exchange inspired logo with this smaller one

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#973]
as a result of website speed test and suggested compression of the image. As it is loaded in the footer every time it is worth the effort :)

![inspired_logo_small](https://user-images.githubusercontent.com/2119496/69613717-55ac8400-1032-11ea-90a9-b1395da1e5d8.png)

**Comment by MichalFrontEnd** [comment]
Is this already done? 
If not, I would love to do it.

**Comment by langjoh** [comment]
@MichalFrontEnd No, this isn't done yet, please go ahead. I'll unassign myself from the issue.

**Comment by zaziemo** [comment]
Logo was now completely removed, thus no necessary anymore.
