### ISSUE TITLE
Flaky Elastic search tests

### ISSUE THREAD

**Issue by porras** [rubymonsters/speakerinnen_liste#976]
Tests that do a `Profile.__elasticsearch__.refresh_index!` fail sometimes. Looks like a race condition (the index happens asynchronously and sometimes is fast enough so that the assertion works, sometimes it's not).

**Comment by netagonen** [comment]
Lets check if this happens also after upgrade and the wait for elastic script added

**Comment by netagonen** [comment]
fixed with https://github.com/rubymonsters/speakerinnen_liste/pull/1091
