### ISSUE TITLE
Change address in impressum

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#982]
into:
Kombüse e.V.
Ottersbekallee 14
20255 Hamburg

- [x] https://speakerinnen.org/de/impressum 
- [x] https://speakerinnen.org/en/impressum
- [x] https://50prozent.speakerinnen.org/de/p/imprint (redirect to https://speakerinnen.org/de/impressum)
- [x] https://50prozent.speakerinnen.org/en/p/imprint (redirect to https://speakerinnen.org/en/impressum)

**Comment by sabrina-ulbrich** [comment]
done in pr #990
