### ISSUE TITLE
Social Networks buttons

### ISSUE THREAD

**Issue by netagonen** [rubymonsters/speakerinnen_liste#986]
Implement Instagram and Facebook buttons + links on speakerinnen.org

**Comment by zaziemo** [comment]
I didn't add buttons but links in the footer. I think that's ok for now
<img width="1110" alt="Bildschirmfoto 2020-06-19 um 10 27 05" src="https://user-images.githubusercontent.com/2119496/85113378-7a0ebe80-b217-11ea-85cf-c742380ad8dd.png">
