### ISSUE TITLE
Add a favorite feature

### ISSUE THREAD

**Issue by netagonen** [rubymonsters/speakerinnen_liste#996]
A nice feature to have, we still need to discuss how to implement it.

**Comment by netagonen** [comment]
## Thoughts so far:
### Phase 1:
* Implement with a cookie which has a 1 year expiration date. No login required
* Have a star/heart sign in the navigation bar to access the  list. 
* The favourites list is an index view (like the view of search results). 
* Each item in the list is a link to a profile view. 
* All profiles will have a heart/star sign to indicate whether they are in the favourites list or not (empty star/heart = not in the list, full star/heart is in the list). 
* Clicking on the sign will add/remove a profile from the list.    
* In the favourites view, when a clicking on a star/heart sign of a profile, the profile will be removed from the list

###Phase 2, do we want this???: 
*Enable  organisers login
*Favourites list will be saved in the DB

@zaziemo, @tyranja, @sabrina-ulbrich, @Powerglove  Comments? thoughts? can I start implement phase 1?

**Comment by zaziemo** [comment]
@netagonen if you find this still interesting please bring it up on our monday meeting. If not we could "archive" this issue
