### ISSUE TITLE
Add a new attributes to Profile

### ISSUE THREAD

**Issue by netagonen** [rubymonsters/speakerinnen_liste#999]
* [x] Add a new copy-right column to the pics table in the database
  - When a speaker upload a picture she can add a copyright to it (not mandatory)
  - show the copy-right attribute under the picture in the profile view
* [x] Add new attribute: format. 
* [x] Add 2 binary attributes: 
 - willing_to_travel_for_talk
 - willing_to_talk_for_nonprofit
 * [x] Add a new attribute `personal infos`
 Above the "Bio", no more than 175 characters to show it in the short profile view.
 ![personal-note](https://user-images.githubusercontent.com/22200510/74321854-47dde380-4d83-11ea-8668-5d0644abf2ed.png)
* [x] Make a hover tooltip for the profiles index view with: languages, city, willing to travel and nonprofit
* [ ] tests

**Comment by netagonen** [comment]
Hi @tyranja, @zaziemo and @sabrina-ulbrich : 
Should the attribute be added to the Profiles table?

**Comment by tyranja** [comment]
yes please!

**Comment by netagonen** [comment]
Cool, I wrote the migration, but when I ran `rails db:migrate` it removed modifiers (like limit: 255, null: ...) from the entire data base and I am not sure if this is how it's suppose to be (without modifiers) or not, therefor, I can't commit the new schema....

**Comment by tyranja** [comment]
Just discovered that we still have the structure.sql file. we can delete that I guess.

**Comment by tyranja** [comment]
Can you make a PR?

**Comment by netagonen** [comment]
I am trying but as I am working on Alon's computer I get this message: `ERROR: Permission to rubymonsters/speakerinnen_liste.git denied to alonpeer.`
Can you please grant him access rights?

**Comment by netagonen** [comment]
Opened: #1006

**Comment by netagonen** [comment]
Unified this issue with #1015 and #1014 

1 question: what type should be the attribute format? text field? check boxes?

**Comment by tyranja** [comment]
check boxes please. So we have just 4 types of format predefined and the speaker can select them

**Comment by sabrina-ulbrich** [comment]
As far as I meant the format (in the #1011 issue I called it "offer" or "services" from Alon) should contain the types of presentation the women offer. They should select from the following formats:

- Speech (Vortrag)
- Moderation (Moderation)
- Workshop management (Seminarleitung)
- Consulting (Beratung)
- Coaching (Training)

These are my suggestions, there can be more (but not more than 7 I think) or other names for it.

An open question is, how we implement this. Do we want another model related to the profile or do we want an attribute inside the profile table.

**Comment by netagonen** [comment]
Ok, I discussed with Alon and read some online. it seems that a joined table would be a good solution. 
Also: do we want this for frauentag?? should we add the label/project or would it be better to focus on another issue?

**Comment by netagonen** [comment]
more todo's:
for copyright: show when hover
for personal note: add "in English", "auf Duetsch", add tooltip
